// @flow
import { makeStyles } from '@material-ui/styles';

export const styles = {
  container: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  scrollableContent: {
    flex: 1,
    overflow: 'auto',
    padding: '12px 16px 0 16px',
  },
  optionsRow: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 8,
    gap: 8,
  },
  searchInLabel: {
    opacity: 0.7,
  },
  searchButton: {
    marginLeft: 8,
  },
  resultsArea: {
    marginTop: '8px',
  },
  searchQueryHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 12px',
    marginBottom: 8,
    borderRadius: 4,
    border: '1px solid var(--event-sheet-conditions-border-color, #e2e2e2)',
    background: 'var(--event-sheet-conditions-background-color, #f1f2f209)',
  },
  searchQueryLabel: {
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase',
    opacity: 0.6,
    letterSpacing: '0.05em',
    fontFamily: 'var(--gdevelop-classic-font-family)',
  },
  searchQueryText: {
    fontSize: 14,
    fontWeight: 600,
    fontFamily: 'var(--gdevelop-classic-font-family)',
    display: 'flex',
    flex: 1,
    justifyContent: 'space-between',
  },
  groupHeaderContent: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  groupHeaderIcon: {
    opacity: 0.7,
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    fontSize: 28,
    fontFamily: 'var(--gdevelop-classic-font-family)',
  },
  matchCountChip: {
    height: 20,
    fontSize: 12,
    flexShrink: 0,
  },
  accordionGroupContainer: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    width: '100%',
    gap: '8px',
  },
  eventRowIndicator: {
    width: 4,
    flexShrink: 0,
    background: 'var(--event-sheet-rst-move-handle-background-color, #a3b1c0)',
  },
  eventRowColumns: {
    display: 'flex',
    flex: 1,
    minHeight: 32,
    minWidth: 0,
  },
  eventRowConditions: {
    flex: '0 0 40%',
    background: 'var(--event-sheet-conditions-background-color, #f1f2f2)',
    color: 'var(--event-sheet-conditions-color, black)',
    borderRight:
      '1px solid var(--event-sheet-conditions-border-right-color, #e2e2e2)',
    padding: '6px 10px',
    fontSize: 13,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
  },
  eventRowActions: {
    flex: 1,
    background: 'var(--event-sheet-actions-background-color, #FFFFFF)',
    color: 'var(--event-sheet-actions-color, black)',
    padding: '6px 10px',
    fontSize: 13,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
  },
  eventRowConditionsFull: {
    flex: 1,
    background: 'var(--event-sheet-conditions-background-color, #f1f2f2)',
    color: 'var(--event-sheet-conditions-color, black)',
    padding: '6px 10px',
    fontSize: 13,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
  },
  eventRowActionsFull: {
    flex: 1,
    background: 'var(--event-sheet-actions-background-color, #FFFFFF)',
    color: 'var(--event-sheet-actions-color, black)',
    padding: '6px 10px',
    fontSize: 13,
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
  },
  eventRowOther: {
    flex: 1,
    background: 'var(--event-sheet-actions-background-color, #FFFFFF)',
    color: 'var(--event-sheet-actions-color, black)',
    padding: '6px 10px',
    fontSize: 13,
    overflow: 'hidden',
    fontStyle: 'italic',
    display: 'flex',
    alignItems: 'center',
  },
  eventRowText: {
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '20px',
    flex: 1,
    minWidth: 0,
    fontFamily: 'var(--gdevelop-classic-font-family) !important',
    fontSize: '16px',
  },
  searchMatchText: {
    backgroundColor: 'rgba(252, 100, 33, 0.25)',
    borderRadius: 2,
    padding: '0 2px',
  },
  emptyStateContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 24px',
    gap: 12,
    opacity: 0.5,
  },
  emptyStateIcon: {
    fontSize: 48,
    opacity: 0.4,
  },
  noMatchesContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 24px',
    gap: 8,
    opacity: 0.6,
  },
};

export const useEventRowStyles: () => {
  eventRow: string,
  groupLableText: string,
} = makeStyles({
  eventRow: {
    cursor: 'pointer',
    display: 'flex',
    borderBottom:
      '1px solid var(--event-sheet-conditions-border-color, #e2e2e2)',
    marginBottom: 3,
    '&:last-child': {
      marginBottom: 0,
    },
  },
  groupLableText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    flex: 1,
  },
});
