// @flow
import {
  type Usages,
  type Subscription,
  type Limits,
} from '../../Utils/GDevelopServices/Usage';
import { User as FirebaseUser } from 'firebase/auth';
import { type Profile } from '../../Utils/GDevelopServices/Authentication';
import { type Release } from '../../Utils/GDevelopServices/Release';
import { type Build } from '../../Utils/GDevelopServices/Build';
import { type CloudProjectWithUserAccessInfo } from '../../Utils/GDevelopServices/Project';
import {
  type ExtensionShortHeader,
  type ExtensionHeader,
} from '../../Utils/GDevelopServices/Extension';
import { type ExampleShortHeader } from '../../Utils/GDevelopServices/Example';
import {
  type Game,
  type ShowcasedGame,
} from '../../Utils/GDevelopServices/Game';
import { type GameMetrics } from '../../Utils/GDevelopServices/Analytics';
import { type AuthenticatedUser } from '../../Profile/AuthenticatedUserContext';
import {
  type AssetShortHeader,
  type Asset,
  type PublicAssetPacks,
} from '../../Utils/GDevelopServices/Asset';
import { formatISO, subDays } from 'date-fns';
import { type Comment } from '../../Utils/GDevelopServices/Play';
import { type Announcement } from '../../Utils/GDevelopServices/Announcement';
import { type PrivateGameTemplateListingData } from '../../Utils/GDevelopServices/Shop';

export const indieFirebaseUser: FirebaseUser = {
  uid: 'indie-user',
  providerId: 'fake-provider.com',
  email: 'indie-user@example.com',
  emailVerified: false,
};

export const indieVerifiedFirebaseUser: FirebaseUser = {
  uid: 'indie-user',
  providerId: 'fake-provider.com',
  email: 'indie-user@example.com',
  emailVerified: true,
};

export const cloudProjectsForIndieUser: Array<CloudProjectWithUserAccessInfo> = [
  {
    id: 'af7a8282-746d-4d3a-8cb8-bb8cd9372143',
    name: 'Worms 2D',
    createdAt: '2022-02-05T00:36:53.972Z',
    updatedAt: '2022-02-07T00:36:53.972Z',
    lastModifiedAt: '2022-02-07T00:36:53.972Z',
  },
  {
    id: 'fb4d878a-1935-4916-b681-f9235475d35c',
    name: 'Crash Bandicoot',
    createdAt: '2020-01-24T00:36:53.972Z',
    updatedAt: '2022-02-07T00:36:53.972Z',
    lastModifiedAt: '2020-02-06T00:36:53.972Z',
  },
];

const tenCloudProjects: Array<CloudProjectWithUserAccessInfo> = [
  {
    id: 'af7a8282-746d-4d3a-8cb8-bb8cd9372141',
    name: 'Worms 2D 1',
    createdAt: '2022-02-05T00:36:53.972Z',
    updatedAt: '2022-02-07T00:36:53.972Z',
    lastModifiedAt: '2022-02-07T00:36:53.972Z',
  },
  {
    id: 'fb4d878a-1935-4916-b681-f9235475d352',
    name: 'Crash Bandicoot 2',
    createdAt: '2020-01-24T00:36:53.972Z',
    updatedAt: '2022-02-07T00:36:53.972Z',
    lastModifiedAt: '2020-02-06T00:36:53.972Z',
  },
  {
    id: 'af7a8282-746d-4d3a-8cb8-bb8cd9372143',
    name: 'Worms 2D 3',
    createdAt: '2022-02-05T00:36:53.972Z',
    updatedAt: '2022-02-05T00:36:53.972Z',
    lastModifiedAt: '2022-02-07T00:36:53.972Z',
  },
  {
    id: 'fb4d878a-1935-4916-b681-f9235475d354',
    name: 'Crash Bandicoot 4',
    createdAt: '2020-01-24T00:36:53.972Z',
    updatedAt: '2022-02-07T00:36:53.972Z',
    lastModifiedAt: '2020-02-06T00:36:53.972Z',
  },
  {
    id: 'af7a8282-746d-4d3a-8cb8-bb8cd9372145',
    name: 'Worms 2D 5',
    createdAt: '2022-02-05T00:36:53.972Z',
    updatedAt: '2022-02-05T00:36:53.972Z',
    lastModifiedAt: '2022-02-07T00:36:53.972Z',
  },
  {
    id: 'fb4d878a-1935-4916-b681-f9235475d356',
    name: 'Crash Bandicoot 6',
    createdAt: '2020-01-24T00:36:53.972Z',
    updatedAt: '2020-01-24T00:36:53.972Z',
    lastModifiedAt: '2020-02-06T00:36:53.972Z',
  },
  {
    id: 'af7a8282-746d-4d3a-8cb8-bb8cd9372147',
    name: 'Worms 2D 7',
    createdAt: '2022-02-05T00:36:53.972Z',
    updatedAt: '2022-02-05T00:36:53.972Z',
    lastModifiedAt: '2022-02-07T00:36:53.972Z',
  },
  {
    id: 'fb4d878a-1935-4916-b681-f9235475d358',
    name: 'Crash Bandicoot 8',
    createdAt: '2020-01-24T00:36:53.972Z',
    updatedAt: '2020-01-24T00:36:53.972Z',
    lastModifiedAt: '2020-02-06T00:36:53.972Z',
  },
  {
    id: 'af7a8282-746d-4d3a-8cb8-bb8cd9372149',
    name: 'Worms 2D 9',
    createdAt: '2022-02-05T00:36:53.972Z',
    updatedAt: '2022-02-05T00:36:53.972Z',
    lastModifiedAt: '2022-02-07T00:36:53.972Z',
  },
  {
    id: 'fb4d878a-1935-4916-b681-f9235475d350',
    name: 'Crash Bandicoot 10',
    createdAt: '2020-01-24T00:36:53.972Z',
    updatedAt: '2020-01-24T00:36:53.972Z',
    lastModifiedAt: '2020-02-06T00:36:53.972Z',
  },
];

export const indieUserProfile: Profile = {
  id: 'indie-user',
  email: 'indie-user@example.com',
  username: 'im-the-indie-user',
  description: 'Just here to develop indie games',
  getGameStatsEmail: false,
  getNewsletterEmail: true,
  createdAt: 12345,
  updatedAt: 12345,
  appLanguage: null,
  isCreator: true,
  isPlayer: false,
  isTeacher: false,
  isStudent: false,
  isEmailAutogenerated: false,
  donateLink: 'https://www.paypal.me/indie-user',
  discordUsername: 'indie-user#1234',
  communityLinks: {
    personalWebsiteLink: 'https://indie-user.com',
    personalWebsite2Link: 'https://indie-user2.com',
    twitterUsername: 'indie-user',
    facebookUsername: 'indie-user',
    youtubeUsername: 'indie-user',
    tiktokUsername: 'indie-user',
    instagramUsername: 'indie-user',
    redditUsername: 'indie-user',
    snapchatUsername: 'indie-user',
    discordServerLink: 'https://discord.gg/indie-user',
  },
};

export const usagesForIndieUser: Usages = [
  {
    id: '1',
    userId: 'indie-user',
    type: 'cordova-build',
    createdAt: 1515084391000,
  },
  {
    id: '56',
    userId: 'indie-user',
    type: 'cordova-build',
    createdAt: 1515084351000,
  },
  {
    id: '75',
    userId: 'indie-user',
    type: 'cordova-build',
    createdAt: 1515084311000,
  },
];

export const subscriptionForIndieUser: Subscription = {
  planId: 'gdevelop_indie',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'indie-user',
  pricingSystemId: 'indie_1month',
};

export const subscriptionForProUser: Subscription = {
  planId: 'gdevelop_pro',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'pro-user',
  pricingSystemId: 'pro_1month',
};

export const subscriptionForSilverUser: Subscription = {
  planId: 'gdevelop_silver',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'silver-user',
  pricingSystemId: 'silver_1month',
};

export const subscriptionForGoldUser: Subscription = {
  planId: 'gdevelop_gold',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'gold-user',
  pricingSystemId: 'gold_1month',
};

export const subscriptionForStartupUser: Subscription = {
  planId: 'gdevelop_startup',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'startup-user',
  pricingSystemId: 'startup_1month',
};

export const subscriptionForBusinessUser: Subscription = {
  planId: 'gdevelop_business',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'business-user',
  pricingSystemId: 'business_1month',
};

export const subscriptionForEducationPlan: Subscription = {
  planId: 'gdevelop_education',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'teacher-user',
  pricingSystemId: 'education_1month',
};

export const subscriptionForGoldUserFromEducationPlan: Subscription = {
  planId: 'gdevelop_gold',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'silver-user',
  benefitsFromEducationPlan: true,
  pricingSystemId: 'TEAM_MEMBER',
};

export const purchaselyGoldSubscription: Subscription = {
  planId: 'gdevelop_gold',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'silver-user',
  purchaselyPlan: 'gdevelop_gold_whatever',
  pricingSystemId: 'PURCHASELY_gdevelop_gold_whatever',
};

export const silverSubscriptionWithRedemptionCode: Subscription = {
  planId: 'gdevelop_silver',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'silver-user',
  redemptionCode: 'test-123-code',
  redemptionCodeValidUntil: 1923400438000,
  pricingSystemId: 'REDEMPTION_CODE',
};

export const silverSubscriptionWithExpiredRedemptionCode: Subscription = {
  planId: 'gdevelop_silver',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'silver-user',
  redemptionCode: 'test-123-code',
  redemptionCodeValidUntil: Date.now() - 1000,
  pricingSystemId: 'REDEMPTION_CODE',
};

export const silverSubscriptionButCancelAtPeriodEnd: Subscription = {
  planId: 'gdevelop_silver',
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'silver-user',
  cancelAtPeriodEnd: true,
  pricingSystemId: 'silver_1month',
};

export const noSubscription: Subscription = {
  planId: null,
  createdAt: 1515084011000,
  updatedAt: 1515084011000,
  userId: 'no-subscription-user',
  pricingSystemId: null,
};

export const subscriptionPlansWithPricingSystems = [
  {
    id: 'free',
    isLegacy: false,
    nameByLocale: { en: 'GDevelop Free & Open-source' },
    descriptionByLocale: {
      en:
        'Use GDevelop for free, forever. We also give you access to these additional online services for free.',
      'ar-SA':
        'استخدم GDevelop مجانًا للأبد. نقدم لك أيضًا وصولًا إلى هذه الخدمات الإلكترونية الإضافية مجانًا.',
      'de-DE':
        'Verwenden Sie GDevelop kostenlos, für immer. Wir bieten Ihnen auch kostenlosen Zugang zu diesen zusätzlichen Online-Diensten.',
      'es-ES':
        'Usa GDevelop de forma gratuita, para siempre. También te ofrecemos acceso a estos servicios en línea adicionales de forma gratuita.',
      'fr-FR':
        'Utilisez GDevelop gratuitement pour toujours. Nous vous donnons également accès à ces services supplémentaires en ligne gratuitement.',
      'it-IT':
        "Usa GDevelop gratuitamente, per sempre. Ti offriamo anche l'accesso a questi servizi online aggiuntivi gratuitamente.",
      'ja-JP':
        'GDevelopを無料でずっとご利用いただけます。また、これらの追加のオンラインサービスも無料でご利用いただけます。',
      'ko-KR':
        'GDevelop를 무료로 영구히 사용하세요. 또한 이 추가 온라인 서비스에 무료로 액세스할 수 있습니다.',
      'pl-PL':
        'Korzystaj z GDevelop za darmo, na zawsze. Oferujemy również darmowy dostęp do tych dodatkowych usług online.',
      'pt-BR':
        'Use o GDevelop gratuitamente, para sempre. Também oferecemos acesso gratuito a esses serviços online adicionais.',
      'ru-RU':
        'Используйте GDevelop бесплатно, навсегда. Мы также предоставляем вам бесплатный доступ к этим дополнительным онлайн-сервисам.',
      'sl-SI':
        'Uporabite GDevelop brezplačno, za vedno. Prav tako vam ponujamo brezplačen dostop do teh dodatnih spletnih storitev.',
      'uk-UA':
        'Використовуйте GDevelop безкоштовно, назавжди. Ми також надаємо вам безкоштовний доступ до цих додаткових онлайн-сервісів.',
      'zh-CN': '永久免费使用GDevelop。我们还免费为您提供这些额外的在线服务。',
    },
    bulletPointsByLocale: [
      {
        en: '10 cloud projects with 50MB of resources per project.',
        'ar-SA': '10 مشاريع سحابية بسعة 50 ميجابايت لكل مشروع.',
        'de-DE': '10 Cloud-Projekte mit 50 MB Ressourcen pro Projekt.',
        'es-ES': '10 proyectos en la nube con 50 MB de recursos por proyecto.',
        'fr-FR': '10 projets cloud de 50 Mo de ressources par projet.',
        'it-IT': '10 progetti cloud con 50 MB di risorse per progetto.',
        'ja-JP':
          '1つのプロジェクトあたり50MBのリソースを備えた10のクラウドプロジェクト。',
        'ko-KR': '프로젝트당 50MB의 자원이 포함된 10개의 클라우드 프로젝트.',
        'pl-PL': '10 projektów w chmurze z 50 MB zasobów na projekt.',
        'pt-BR': '10 projetos na nuvem com 50 MB de recursos por projeto.',
        'ru-RU': '10 проектов в облаке с ресурсами объемом 50 МБ на проект.',
        'sl-SI': '10 oblak projektov z 50MB virov na projekt.',
        'uk-UA': '10 хмарних проектів з ресурсами обсягом 50 МБ на проект.',
        'zh-CN': '每个项目有50MB资源的10个云项目。',
      },
      {
        en: '2 packagings per day for Android and for desktop.',
        'ar-SA': '2 حزم يوميًا لنظام Android ولسطح المكتب.',
        'de-DE': '2 Verpackungen pro Tag für Android und Desktop.',
        'es-ES': '2 empaquetados por día para Android y para escritorio.',
        'fr-FR': '2 packagings par jour pour Android et ordinateur.',
        'it-IT': '2 confezioni al giorno per Android e desktop.',
        'ja-JP': 'Androidおよびデスクトップ用に1日2回のパッケージ。',
        'ko-KR': '하루에 안드로이드 및 데스크톱용 2개의 패키지.',
        'pl-PL': '2 opakowania dziennie dla Androida i komputera.',
        'pt-BR': '2 embalagens por dia para Android e desktop.',
        'ru-RU': '2 упаковки в день для Android и настольных компьютеров.',
        'sl-SI': '2 pakiranji na dan za Android in namizje.',
        'uk-UA': "2 упаковки на день для Android та настільних комп'ютерів.",
        'zh-CN': '每天为Android和桌面提供2个包装。',
      },
      {
        en:
          '3 leaderboards per game and 10 player feedback responses per game.',
        'ar-SA':
          '3 جداول الصدارة لكل لعبة و10 استجابات لتعليقات اللاعبين لكل لعبة.',
        'de-DE':
          '3 Bestenlisten pro Spiel und 10 Spieler-Feedback-Antworten pro Spiel.',
        'es-ES':
          '3 tablas de clasificación por juego y 10 respuestas de retroalimentación de jugadores por juego.',
        'fr-FR':
          '3 tableaux de classements par jeux et 10 retours de joueurs par jeux.',
        'it-IT':
          '3 classifiche per gioco e 10 risposte ai feedback dei giocatori per gioco.',
        'ja-JP':
          '1ゲームあたり3つのリーダーボードと1ゲームあたり10のプレイヤーフィードバックレスポンス。',
        'ko-KR': '게임당 3개의 리더보드 및 게임당 10개의 플레이어 피드백 응답.',
        'pl-PL':
          '3 tabele wyników na grę i 10 odpowiedzi na opinie graczy na grę.',
        'pt-BR':
          '3 quadros de líderes por jogo e 10 respostas de feedback de jogadores por jogo.',
        'ru-RU':
          '3 таблицы лидеров на игру и 10 ответов на обратную связь от игроков на игру.',
        'sl-SI':
          '3 lestvice za vsako igro in 10 odgovorov na povratne informacije igralcev za vsako igro.',
        'uk-UA':
          '3 таблиці лідерів на гру та 10 відповідей на відгуки гравців на гру.',
        'zh-CN': '每款游戏有3个排行榜，每款游戏有10个玩家反馈响应。',
      },
    ],
    pricingSystems: [],
  },
  {
    id: 'gdevelop_silver',
    isLegacy: false,
    nameByLocale: { en: 'GDevelop Silver' },
    descriptionByLocale: {
      en: 'Build more and faster.',
      'ar-SA': 'ابنِ المزيد بسرعة أكبر.',
      'de-DE': 'Baue mehr und schneller.',
      'es-ES': 'Construye más y más rápido.',
      'fr-FR': "Construire d'avantage et plus rapidement.",
      'it-IT': 'Costruisci di più e più velocemente.',
      'ja-JP': 'もっと多く、もっと速く建設する。',
      'ko-KR': '더 많이 빨리 더 많이 건설하십시오.',
      'pl-PL': 'Buduj więcej i szybciej.',
      'pt-BR': 'Construa mais e mais rápido.',
      'ru-RU': 'Стройте больше и быстрее.',
      'sl-SI': 'Gradite več in hitreje.',
      'uk-UA': 'Будуйте більше та швидше.',
      'zh-CN': '更多、更快地构建。',
    },
    bulletPointsByLocale: [
      {
        en: '50 cloud projects with 250MB of resources per project.',
        'ar-SA': '50 مشروع سحابي بسعة 250 ميجابايت لكل مشروع.',
        'de-DE': '50 Cloud-Projekte mit 250 MB Ressourcen pro Projekt.',
        'es-ES': '50 proyectos en la nube con 250 MB de recursos por proyecto.',
        'fr-FR': '50 projets cloud de 250 Mo de ressources par projet.',
        'it-IT': '50 progetti cloud con 250 MB di risorse per progetto.',
        'ja-JP':
          '1つのプロジェクトあたり250MBのリソースを備えた50のクラウドプロジェクト。',
        'ko-KR': '프로젝트당 250MB의 자원이 포함된 50개의 클라우드 프로젝트.',
        'pl-PL': '50 projektów w chmurze z 250 MB zasobów na projekt.',
        'pt-BR': '50 projetos na nuvem com 250 MB de recursos por projeto.',
        'ru-RU': '50 проектов в облаке с ресурсами объемом 250 МБ на проект.',
        'sl-SI': '50 oblak projektov z 250MB virov na projekt.',
        'uk-UA': '50 хмарних проектів з ресурсами обсягом 250 МБ на проект.',
        'zh-CN': '每个项目有250MB资源的50个云项目。',
      },
      {
        en: '10 packagings per day for Android and for desktop.',
        'ar-SA': '10 حزم يوميًا لنظام Android ولسطح المكتب.',
        'de-DE': '10 Verpackungen pro Tag für Android und Desktop.',
        'es-ES': '10 empaquetados por día para Android y para escritorio.',
        'fr-FR': '10 packagings par jour pour Android et ordinateur.',
        'it-IT': '10 confezioni al giorno per Android e desktop.',
        'ja-JP': 'Androidおよびデスクトップ用に1日10回のパッケージ。',
        'ko-KR': '하루에 안드로이드 및 데스크톱용 10개의 패키지.',
        'pl-PL': '10 opakowań dziennie dla Androida i komputera.',
        'pt-BR': '10 embalagens por dia para Android e desktop.',
        'ru-RU': '10 упаковок в день для Android и настольных компьютеров.',
        'sl-SI': '10 pakiranj na dan za Android in namizje.',
        'uk-UA': "10 упаковок на день для Android та настільних комп'ютерів.",
        'zh-CN': '每天为Android和桌面提供10个包装。',
      },
      {
        en: 'Unlimited leaderboards and unlimited player feedback responses.',
        'ar-SA': 'لا حدود للجداول الصدارة ولا حدود لاستجابات تعليقات اللاعبين.',
        'de-DE':
          'Unbegrenzte Bestenlisten und unbegrenzte Spieler-Feedback-Antworten.',
        'es-ES':
          'Tablas de clasificación ilimitadas y respuestas ilimitadas de retroalimentación de jugadores.',
        'fr-FR':
          'Aucune limite sur les tableaux de classements et les retours de joueurs',
        'it-IT':
          'Classifiche illimitate e risposte illimitate ai feedback dei giocatori.',
        'ja-JP':
          '無制限のリーダーボードと無制限のプレイヤーフィードバックレスポンス。',
        'ko-KR': '무제한 리더보드 및 무제한 플레이어 피드백 응답.',
        'pl-PL':
          'Nieograniczone tabele wyników i nieograniczone odpowiedzi na opinie graczy.',
        'pt-BR':
          'Quadros de líderes ilimitados e respostas ilimitadas de feedback de jogadores.',
        'ru-RU':
          'Неограниченные таблицы лидеров и неограниченные ответы на обратную связь от игроков.',
        'sl-SI':
          'Neomejene lestvice in neomejeni odgovori na povratne informacije igralcev.',
        'uk-UA':
          'Необмежені таблиці лідерів і необмежені відповіді на відгуки гравців.',
        'zh-CN': '无限排行榜和无限玩家反馈响应。',
      },
      {
        en:
          'Immerse your players by removing the GDevelop watermark or the GDevelop logo when the game loads.',
        'ar-SA':
          'تعمل على اختفاء علامة GDevelop أو شعار GDevelop عند تحميل اللعبة لتغمر لاعبيك باللعبة.',
        'de-DE':
          'Tauchen Sie Ihre Spieler ein, indem Sie das GDevelop-Wasserzeichen oder das GDevelop-Logo beim Laden des Spiels entfernen.',
        'es-ES':
          'Sumérgete a tus jugadores eliminando la marca de agua de GDevelop o el logotipo de GDevelop cuando se carga el juego.',
        'fr-FR':
          'Immergez vos joueurs en supprimant le filigrane GDevelop ou le logo GDevelop lors du chargement du jeu.',
        'it-IT':
          'Immergi i tuoi giocatori rimuovendo il watermark di GDevelop o il logo GDevelop quando il gioco si carica.',
        'ja-JP':
          'ゲームの読み込み時にGDevelopのウォーターマークまたはGDevelopロゴを削除して、プレイヤーを没入させます。',
        'ko-KR':
          '게임 로딩 시 GDevelop 워터마크 또는 GDevelop 로고를 제거하여 플레이어를 몰입시킵니다.',
        'pl-PL':
          'Zanurz swoich graczy, usuwając znak wodny GDevelop lub logo GDevelop podczas ładowania gry.',
        'pt-BR':
          "Mergulhe seus jogadores removendo a marca d'água do GDevelop ou o logotipo do GDevelop quando o jogo é carregado.",
        'ru-RU':
          'Погрузите своих игроков, удалив водяной знак GDevelop или логотип GDevelop при загрузке игры.',
        'sl-SI':
          'Potopite svoje igralce, tako da odstranite GDevelop watermark ali logotip GDevelop, ko se igra naloži.',
        'uk-UA':
          'Занурте своїх гравців, видаливши водяний знак GDevelop або логотип GDevelop під час завантаження гри.',
        'zh-CN':
          '在游戏加载时去除GDevelop水印或GDevelop标志，让您的玩家沉浸其中。',
      },
    ],
    pricingSystems: [
      {
        id: 'silver_1month',
        planId: 'gdevelop_silver',
        period: 'month',
        periodCount: 1,
        currency: 'EUR',
        amountInCents: 499,
        region: 'everywhere',
      },
    ],
  },
  {
    id: 'gdevelop_gold',
    isLegacy: false,
    nameByLocale: { en: 'GDevelop Gold' },
    descriptionByLocale: {
      en: 'Experimented creators, ambitious games.',
      'ar-SA': 'مبدعين مجربين، ألعاب طموحة.',
      'de-DE': 'Erfahrene Entwickler, ambitionierte Spiele.',
      'es-ES': 'Creadores experimentados, juegos ambiciosos.',
      'fr-FR': 'Créateurs expérimentés, jeux ambitieux.',
      'it-IT': 'Creatori esperti, giochi ambiziosi.',
      'ja-JP': '経験豊富なクリエイター、野心的なゲーム。',
      'ko-KR': '경험 많은 개발자, 야심 찬 게임.',
      'pl-PL': 'Doświadczeni twórcy, ambitne gry.',
      'pt-BR': 'Criadores experientes, jogos ambiciosos.',
      'ru-RU': 'Опытные создатели, амбициозные игры.',
      'sl-SI': 'Izkušeni ustvarjalci, ambiciozne igre.',
      'uk-UA': 'Досвідчені розробники, амбіційні ігри.',
      'zh-CN': '有经验的创作者，有抱负的游戏。',
    },
    bulletPointsByLocale: [
      {
        en: '100 cloud projects with 500MB of resources per project.',
        'ar-SA': '100 مشروع سحابي بسعة 500 ميجابايت لكل مشروع.',
        'de-DE': '100 Cloud-Projekte mit 500 MB Ressourcen pro Projekt.',
        'es-ES':
          '100 proyectos en la nube con 500 MB de recursos por proyecto.',
        'fr-FR': '100 projets cloud de 500 Mo de ressources par projet.',
        'it-IT': '100 progetti cloud con 500 MB di risorse per progetto.',
        'ja-JP':
          '1つのプロジェクトあたり500MBのリソースを備えた100のクラウドプロジェクト。',
        'ko-KR': '프로젝트당 500MB의 자원이 포함된 100개의 클라우드 프로젝트.',
        'pl-PL': '100 projektów w chmurze z 500 MB zasobów na projekt.',
        'pt-BR': '100 projetos na nuvem com 500 MB de recursos por projeto.',
        'ru-RU': '100 проектов в облаке с ресурсами объемом 500 МБ на проект.',
        'sl-SI': '100 oblak projektov z 500MB virov na projekt.',
        'uk-UA': '100 хмарних проектів з ресурсами обсягом 500 МБ на проект.',
        'zh-CN': '每个项目有500MB资源的100个云项目。',
      },
      {
        en: '20 packagings per day for Android and for desktop.',
        'ar-SA': '20 حزم يوميًا لنظام Android ولسطح المكتب.',
        'de-DE': '20 Verpackungen pro Tag für Android und Desktop.',
        'es-ES': '20 empaquetados por día para Android y para escritorio.',
        'fr-FR': '20 packagings par jour pour Android et ordinateur.',
        'it-IT': '20 confezioni al giorno per Android e desktop.',
        'ja-JP': 'Androidおよびデスクトップ用に1日20回のパッケージ。',
        'ko-KR': '하루에 안드로이드 및 데스크톱용 20개의 패키지.',
        'pl-PL': '20 opakowań dziennie dla Androida i komputera.',
        'pt-BR': '20 embalagens por dia para Android e desktop.',
        'ru-RU': '20 упаковок в день для Android и настольных компьютеров.',
        'sl-SI': '20 pakiranj na dan za Android in namizje.',
        'uk-UA': "20 упаковок на день для Android та настільних комп'ютерів.",
        'zh-CN': '每天为Android和桌面提供20个包装。',
      },
      {
        en: 'Unlimited leaderboards and unlimited player feedback responses.',
        'ar-SA': 'لا حدود للجداول الصدارة ولا حدود لاستجابات تعليقات اللاعبين.',
        'de-DE':
          'Unbegrenzte Bestenlisten und unbegrenzte Spieler-Feedback-Antworten.',
        'es-ES':
          'Tablas de clasificación ilimitadas y respuestas ilimitadas de retroalimentación de jugadores.',
        'fr-FR':
          'Aucune limite sur les tableaux de classements et les retours de joueurs',
        'it-IT':
          'Classifiche illimitate e risposte illimitate ai feedback dei giocatori.',
        'ja-JP':
          '無制限のリーダーボードと無制限のプレイヤーフィードバックレスポンス。',
        'ko-KR': '무제한 리더보드 및 무제한 플레이어 피드백 응답.',
        'pl-PL':
          'Nieograniczone tabele wyników i nieograniczone odpowiedzi na opinie graczy.',
        'pt-BR':
          'Quadros de líderes ilimitados e respostas ilimitadas de feedback de jogadores.',
        'ru-RU':
          'Неограниченные таблицы лидеров и неограниченные ответы на обратную связь от игроков.',
        'sl-SI':
          'Neomejene lestvice in neomejeni odgovori na povratne informacije igralcev.',
        'uk-UA':
          'Необмежені таблиці лідерів і необмежені відповіді на відгуки гравців.',
        'zh-CN': '无限排行榜和无限玩家反馈响应。',
      },
      {
        en:
          'Immerse your players by removing the GDevelop watermark or the GDevelop logo when the game loads.',
        'ar-SA':
          'تعمل على اختفاء علامة GDevelop أو شعار GDevelop عند تحميل اللعبة لتغمر لاعبيك باللعبة.',
        'de-DE':
          'Tauchen Sie Ihre Spieler ein, indem Sie das GDevelop-Wasserzeichen oder das GDevelop-Logo beim Laden des Spiels entfernen.',
        'es-ES':
          'Sumérgete a tus jugadores eliminando la marca de agua de GDevelop o el logotipo de GDevelop cuando se carga el juego.',
        'fr-FR':
          'Immergez vos joueurs en supprimant le filigrane GDevelop ou le logo GDevelop lors du chargement du jeu.',
        'it-IT':
          'Immergi i tuoi giocatori rimuovendo il watermark di GDevelop o il logo GDevelop quando il gioco si carica.',
        'ja-JP':
          'ゲームの読み込み時にGDevelopのウォーターマークまたはGDevelopロゴを削除して、プレイヤーを没入させます。',
        'ko-KR':
          '게임 로딩 시 GDevelop 워터마크 또는 GDevelop 로고를 제거하여 플레이어를 몰입시킵니다.',
        'pl-PL':
          'Zanurz swoich graczy, usuwając znak wodny GDevelop lub logo GDevelop podczas ładowania gry.',
        'pt-BR':
          "Mergulhe seus jogadores removendo a marca d'água do GDevelop ou o logotipo do GDevelop quando o jogo é carregado.",
        'ru-RU':
          'Погрузите своих игроков, удалив водяной знак GDevelop или логотип GDevelop при загрузке игры.',
        'sl-SI':
          'Potopite svoje igralce, tako da odstranite GDevelop watermark ali logotip GDevelop, ko se igra naloži.',
        'uk-UA':
          'Занурте своїх гравців, видаливши водяний знак GDevelop або логотип GDevelop під час завантаження гри.',
        'zh-CN':
          '在游戏加载时去除GDevelop水印或GDevelop标志，让您的玩家沉浸其中。',
      },
    ],
    pricingSystems: [
      {
        id: 'gold_1month',
        planId: 'gdevelop_gold',
        period: 'month',
        periodCount: 1,
        currency: 'EUR',
        amountInCents: 999,
        region: 'everywhere',
      },
    ],
  },
  {
    id: 'gdevelop_startup',
    isLegacy: false,
    nameByLocale: { en: 'GDevelop Startup' },
    descriptionByLocale: {
      en: 'Small game studios and startups',
      'ar-SA': 'الاستديوهات الصغيرة للألعاب والشركات الناشئة.',
      'de-DE': 'Kleine Spielestudios und Startups.',
      'es-ES': 'Pequeños estudios de juegos y startups.',
      'fr-FR': 'Petits studios de jeux et startups.',
      'it-IT': 'Piccoli studi di giochi e start-up.',
      'ja-JP': '小規模ゲームスタジオとスタートアップ。',
      'ko-KR': '소규모 게임 스튜디오 및 스타트업.',
      'pl-PL': 'Małe studia gier i start-upy.',
      'pt-BR': 'Pequenos estúdios de jogos e startups.',
      'ru-RU': 'Маленькие студии игр и стартапы.',
      'sl-SI': 'Mala studia iger in začetniki.',
      'uk-UA': 'Малі студії ігор та стартапи.',
      'zh-CN': '小型游戏工作室和初创企业。',
    },
    bulletPointsByLocale: [
      {
        en: '500 cloud projects with 5GB of resources per project.',
        'ar-SA': '500 مشروع سحابي بسعة 5 غيغابايت لكل مشروع.',
        'de-DE': '500 Cloud-Projekte mit 5 GB Ressourcen pro Projekt.',
        'es-ES': '500 proyectos en la nube con 5 GB de recursos por proyecto.',
        'fr-FR': '500 projets cloud de 5 Go de ressources par projet.',
        'it-IT': '500 progetti cloud con 5 GB di risorse per progetto.',
        'ja-JP':
          '1つのプロジェクトあたり5GBのリソースを備えた500のクラウドプロジェクト。',
        'ko-KR': '프로젝트당 5GB의 자원이 포함된 500개의 클라우드 프로젝트.',
        'pl-PL': '500 projektów w chmurze z 5 GB zasobów na projekt.',
        'pt-BR': '500 projetos na nuvem com 5 GB de recursos por projeto.',
        'ru-RU': '500 проектов в облаке с ресурсами объемом 5 ГБ на проект.',
        'sl-SI': '500 oblak projektov z 5GB virov na projekt.',
        'uk-UA': '500 хмарних проектів з ресурсами обсягом 5 ГБ на проект.',
        'zh-CN': '每个项目有5GB资源的500个云项目。',
      },
      {
        en: 'Unlimited packagings per day for Android, web, and desktop.',
        'ar-SA':
          'عدد غير محدود من التعبئة يوميًا لنظام Android والويب وسطح المكتب.',
        'de-DE':
          'Unbegrenzte Verpackungen pro Tag für Android, Web und Desktop.',
        'es-ES':
          'Empaquetados ilimitados por día para Android, web y escritorio.',
        'fr-FR':
          'Emballages illimités par jour pour Android, le web et le bureau.',
        'it-IT': 'Confezioni illimitate al giorno per Android, web e desktop.',
        'ja-JP': 'Android、Web、デスクトップ向けの1日無制限のパッケージ。',
        'ko-KR': '안드로이드, 웹 및 데스크톱용으로 하루에 무제한 패키징.',
        'pl-PL':
          'Nieograniczone opakowania dziennie dla Androida, sieci i komputera.',
        'pt-BR': 'Embalagens ilimitadas por dia para Android, web e desktop.',
        'ru-RU':
          'Неограниченное количество упаковок в день для Android, веба и рабочего стола.',
        'sl-SI': 'Neomejeno pakiranje na dan za Android, splet in namizje.',
        'uk-UA':
          'Необмежена кількість упаковок на день для Android, вебу та робочого столу.',
        'zh-CN': '每天为Android、Web和桌面提供无限次打包。',
      },
      {
        en: 'Unlimited leaderboards and unlimited player feedback responses.',
        'ar-SA':
          'الجداول الصدارة غير المحدودة وردود فعل اللاعبين غير المحدودة.',
        'de-DE':
          'Unbegrenzte Bestenlisten und unbegrenzte Spieler-Feedback-Antworten.',
        'es-ES':
          'Tablas de clasificación ilimitadas y respuestas ilimitadas de retroalimentación de jugadores.',
        'fr-FR':
          'Classements illimités et réponses illimitées aux commentaires des joueurs.',
        'it-IT':
          'Classifiche illimitate e risposte illimitate ai feedback dei giocatori.',
        'ja-JP':
          '無制限のリーダーボードと無制限のプレイヤーフィードバックレスポンス。',
        'ko-KR': '무제한 리더보드 및 무제한 플레이어 피드백 응답.',
        'pl-PL':
          'Nieograniczone tabele wyników i nieograniczone odpowiedzi na opinie graczy.',
        'pt-BR':
          'Quadros de líderes ilimitados e respostas ilimitadas de feedback de jogadores.',
        'ru-RU':
          'Неограниченные таблицы лидеров и неограниченные ответы на обратную связь от игроков.',
        'sl-SI':
          'Neomejene lestvice in neomejeni odgovori na povratne informacije igralcev.',
        'uk-UA':
          'Необмежені таблиці лідерів і необмежені відповіді на відгуки гравців.',
        'zh-CN': '无限排行榜和无限玩家反馈响应。',
      },
      {
        en:
          'Immerse your players by removing the GDevelop watermark or the GDevelop logo when the game loads.',
        'ar-SA':
          'تعمل على اختفاء علامة GDevelop أو شعار GDevelop عند تحميل اللعبة لتغمر لاعبيك باللعبة.',
        'de-DE':
          'Tauchen Sie Ihre Spieler ein, indem Sie das GDevelop-Wasserzeichen oder das GDevelop-Logo beim Laden des Spiels entfernen.',
        'es-ES':
          'Sumérgete a tus jugadores eliminando la marca de agua de GDevelop o el logotipo de GDevelop cuando se carga el juego.',
        'fr-FR':
          'Immergez vos joueurs en supprimant le filigrane GDevelop ou le logo GDevelop lors du chargement du jeu.',
        'it-IT':
          'Immergi i tuoi giocatori rimuovendo il watermark di GDevelop o il logo GDevelop quando il gioco si carica.',
        'ja-JP':
          'ゲームの読み込み時にGDevelopのウォーターマークまたはGDevelopロゴを削除して、プレイヤーを没入させます。',
        'ko-KR':
          '게임 로딩 시 GDevelop 워터마크 또는 GDevelop 로고를 제거하여 플레이어를 몰입시킵니다.',
        'pl-PL':
          'Zanurz swoich graczy, usuwając znak wodny GDevelop lub logo GDevelop podczas ładowania gry.',
        'pt-BR':
          "Mergulhe seus jogadores removendo a marca d'água do GDevelop ou o logotipo do GDevelop quando o jogo é carregado.",
        'ru-RU':
          'Погрузите своих игроков, удалив водяной знак GDevelop или логотип GDevelop при загрузке игры.',
        'sl-SI':
          'Potopite svoje igralce, tako da odstranite GDevelop watermark ali logotip GDevelop, ko se igra naloži.',
        'uk-UA':
          'Занурте своїх гравців, видаливши водяний знак GDevelop або логотип GDevelop під час завантаження гри.',
        'zh-CN':
          '在游戏加载时去除GDevelop水印或GDevelop标志，让您的玩家沉浸其中。',
      },
      {
        en:
          'Access your cloud projects history and easily get back to a previous version.',
        'ar-SA':
          'الوصول إلى تاريخ مشاريعك في السحابة والعودة بسهولة إلى إصدار سابق.',
        'de-DE':
          'Zugriff auf die Historie Ihrer Cloud-Projekte und einfaches Zurückkehren zu einer früheren Version.',
        'es-ES':
          'Accede al historial de tus proyectos en la nube y vuelve fácilmente a una versión anterior.',
        'fr-FR':
          "Accédez à l'historique de vos projets cloud et revenez facilement à une version précédente.",
        'it-IT':
          'Accedi alla cronologia dei tuoi progetti cloud e torna facilmente a una versione precedente.',
        'ja-JP':
          'クラウドプロジェクトの履歴にアクセスし、以前のバージョンに簡単に戻ります。',
        'ko-KR':
          '클라우드 프로젝트 기록에 액세스하고 이전 버전으로 쉽게 돌아갑니다.',
        'pl-PL':
          'Otrzymuj dostęp do historii projektów w chmurze i łatwo wracaj do poprzednich wersji.',
        'pt-BR':
          'Acesse o histórico de seus projetos na nuvem e volte facilmente para uma versão anterior.',
        'ru-RU':
          'Получайте доступ к истории ваших проектов в облаке и легко возвращайтесь к предыдущей версии.',
        'sl-SI':
          'Dostopajte do zgodovine svojih projektov v oblaku in se enostavno vrnete na prejšnjo različico.',
        'uk-UA':
          'Отримуйте доступ до історії ваших проектів в хмарі та легко повертайтесь до попередньої версії.',
        'zh-CN': '访问您的云项目历史记录并轻松返回以前的版本。',
      },
      {
        en:
          'Add 1 guest user or unlimited startup team members to collaborate on every project.',
        'ar-SA':
          'أضف مستخدم ضيف واحد أو أعضاء فريق بدء التشغيل غير المحددين للتعاون في كل مشروع.',
        'de-DE':
          'Fügen Sie 1 Gastbenutzer oder unbegrenzte Teammitglieder des Startups hinzu, um an jedem Projekt zusammenzuarbeiten.',
        'es-ES':
          'Agrega 1 usuario invitado o miembros ilimitados del equipo de inicio para colaborar en cada proyecto.',
        'fr-FR':
          "Ajoutez 1 utilisateur invité ou un nombre illimité de membres de l'équipe de démarrage pour collaborer sur chaque projet.",
        'it-IT':
          'Aggiungi 1 utente ospite o membri illimitati del team di startup per collaborare su ogni progetto.',
        'ja-JP':
          'ゲストユーザー1人または無制限のスタートアップチームメンバーを追加して、すべてのプロジェクトで協力します。',
        'ko-KR':
          '모든 프로젝트에서 협력할 수 있도록 게스트 사용자 1명 또는 무제한 스타트업 팀 멤버를 추가하세요.',
        'pl-PL':
          'Dodaj 1 gościa lub nieograniczoną liczbę członków zespołu startupowego do współpracy przy każdym projekcie.',
        'pt-BR':
          'Adicione 1 usuário convidado ou membros ilimitados da equipe de startups para colaborar em cada projeto.',
        'ru-RU':
          'Добавьте 1 гостевого пользователя или неограниченное количество участников стартап-команды для совместной работы над каждым проектом.',
        'sl-SI':
          'Dodajte 1 gostu ali neomejeno število članov ekipe začetnega zagona za sodelovanje pri vsakem projektu.',
        'uk-UA':
          'Додайте 1 гостевого користувача або необмежену кількість учасників команди стартапу для співпраці в кожному проекті.',
        'zh-CN': '添加1个访客用户或无限的初创团队成员，共同合作每个项目。',
      },
    ],
    pricingSystems: [
      {
        id: 'startup_1month',
        planId: 'gdevelop_startup',
        period: 'month',
        periodCount: 1,
        currency: 'EUR',
        amountInCents: 3000,
        region: 'everywhere',
      },
    ],
  },
  {
    id: 'gdevelop_education',
    isLegacy: false,
    nameByLocale: { en: 'GDevelop Education' },
    descriptionByLocale: {
      en: 'Schools and Universities.',
      'ar-SA': 'المدارس والجامعات.',
      'de-DE': 'Schulen und Universitäten.',
      'es-ES': 'Escuelas y universidades.',
      'fr-FR': 'Écoles et universités.',
      'it-IT': 'Scuole e università.',
      'ja-JP': '学校と大学。',
      'ko-KR': '학교 및 대학.',
      'pl-PL': 'Szkoły i uniwersytety.',
      'pt-BR': 'Escolas e universidades.',
      'ru-RU': 'Школы и университеты.',
      'sl-SI': 'Šole in univerze.',
      'uk-UA': 'Школи і університети.',
      'zh-CN': '学校和大学。',
    },
    bulletPointsByLocale: [
      {
        en: 'Students anonymity.',
        'ar-SA': 'سرية الطلاب.',
        'de-DE': 'Anonymität der Schüler.',
        'es-ES': 'Anonimato de los estudiantes.',
        'fr-FR': 'Anonymat des étudiants.',
        'it-IT': 'Anonimato degli studenti.',
        'ja-JP': '学生の匿名性。',
        'ko-KR': '학생 익명성.',
        'pl-PL': 'Anonimowość uczniów.',
        'pt-BR': 'Anonimato dos alunos.',
        'ru-RU': 'Анонимность студентов.',
        'sl-SI': 'Anonimnost študentov.',
        'uk-UA': 'Анонімність студентів.',
        'zh-CN': '学生匿名性。',
      },
      {
        en: 'Organize students per classroom.',
        'ar-SA': 'تنظيم الطلاب حسب الصف.',
        'de-DE': 'Schüler pro Klassenzimmer organisieren.',
        'es-ES': 'Organizar estudiantes por aulas.',
        'fr-FR': 'Organiser les étudiants par classe.',
        'it-IT': 'Organizza gli studenti per classe.',
        'ja-JP': 'クラスごとに学生を組織化。',
        'ko-KR': '학생을 강의실별로 정리하십시오.',
        'pl-PL': 'Organizuj uczniów według sal lekcyjnych.',
        'pt-BR': 'Organize os alunos por sala de aula.',
        'ru-RU': 'Организация студентов по классам.',
        'sl-SI': 'Organizacija študentov po učilnicah.',
        'uk-UA': 'Організація студентів за класами.',
        'zh-CN': '根据教室组织学生。',
      },
      {
        en: "Access your students' projects",
        'ar-SA': 'الوصول إلى مشاريع الطلاب الخاصة بك',
        'de-DE': 'Zugriff auf die Projekte Ihrer Schüler.',
        'es-ES': 'Acceda a los proyectos de sus estudiantes.',
        'fr-FR': 'Accédez aux projets de vos étudiants.',
        'it-IT': 'Accedi ai progetti dei tuoi studenti.',
        'ja-JP': '生徒のプロジェクトにアクセス。',
        'ko-KR': '학생 프로젝트에 액세스하십시오.',
        'pl-PL': 'Dostęp do projektów uczniów.',
        'pt-BR': 'Acesse os projetos dos seus alunos.',
        'ru-RU': 'Доступ к проектам ваших студентов.',
        'sl-SI': 'Dostop do projektov vaših študentov.',
        'uk-UA': 'Доступ до проектів ваших студентів.',
        'zh-CN': '访问您的学生项目。',
      },
      {
        en: 'You and your students receive a Gold subscription.',
        'ar-SA': 'أنت وطلابك تتلقون اشتراكًا ذهبيًا.',
        'de-DE': 'Sie und Ihre Schüler erhalten ein Gold-Abonnement.',
        'es-ES': 'Usted y sus estudiantes reciben una suscripción Gold.',
        'fr-FR': 'Vous et vos étudiants recevrez un abonnement Gold.',
        'it-IT': 'Tu e i tuoi studenti riceverete un abbonamento Gold.',
        'ja-JP':
          'あなたとあなたの生徒はゴールドサブスクリプションを受け取ります。',
        'ko-KR': '당신과 당신의 학생들은 골드 구독을 받습니다.',
        'pl-PL': 'Ty i Twoi uczniowie otrzymają subskrypcję Gold.',
        'pt-BR': 'Você e seus alunos recebem uma assinatura Gold.',
        'ru-RU': 'Вы и ваши студенты получите золотую подписку.',
        'sl-SI': 'Vi in vaši študenti boste prejeli zlato naročnino.',
        'uk-UA': 'Ви і ваші студенти отримаєте золоту підписку.',
        'zh-CN': '您和您的学生将收到金牌订阅。',
      },
      {
        en: 'You and your students can use the cloud project version history.',
        'ar-SA': 'يمكنك وطلابك استخدام تاريخ إصدار مشروع السحابة.',
        'de-DE':
          'Sie und Ihre Schüler können die Versionsgeschichte des Cloud-Projekts verwenden.',
        'es-ES':
          'Usted y sus estudiantes pueden utilizar el historial de versiones del proyecto en la nube.',
        'fr-FR':
          "Vous et vos étudiants pouvez utiliser l'historique des versions du projet cloud.",
        'it-IT':
          'Tu e i tuoi studenti possono utilizzare la cronologia delle versioni del progetto cloud.',
        'ja-JP':
          'あなたとあなたの生徒はクラウドプロジェクトのバージョン履歴を使用できます。',
        'ko-KR':
          '당신과 당신의 학생들은 클라우드 프로젝트 버전 히스토리를 사용할 수 있습니다.',
        'pl-PL':
          'Ty i Twoi uczniowie możecie korzystać z historii wersji projektu w chmurze.',
        'pt-BR':
          'Você e seus alunos podem usar o histórico de versões do projeto na nuvem.',
        'ru-RU':
          'Вы и ваши студенты можете использовать историю версий проекта в облаке.',
        'sl-SI':
          'Vi in vaši študenti lahko uporabljate zgodovino različic projekta v oblaku.',
        'uk-UA':
          'Ви і ваші студенти можете використовувати історію версій проекту в хмарі.',
        'zh-CN': '您和您的学生可以使用云项目版本历史。',
      },
    ],
    pricingSystems: [
      {
        id: 'education_1month',
        planId: 'gdevelop_education',
        period: 'month',
        periodCount: 1,
        currency: 'EUR',
        amountInCents: 299,
        isPerUser: true,
        region: 'everywhere',
      },
      {
        id: 'education_1year',
        planId: 'gdevelop_education',
        period: 'year',
        periodCount: 1,
        currency: 'EUR',
        amountInCents: 2999,
        isPerUser: true,
        region: 'everywhere',
      },
    ],
  },
  {
    id: 'gdevelop_indie',
    isLegacy: true,
    nameByLocale: { en: 'GDevelop Indie (Legacy)' },
    descriptionByLocale: { en: 'Build more and faster' },
    bulletPointsByLocale: [
      {
        en:
          '50 cloud projects with 250MB of resources per project and 3-month version history.',
      },
      { en: '10 packagings per day for Android and for desktop.' },
      { en: 'Unlimited leaderboards and unlimited player feedback responses.' },
    ],
    pricingSystems: [
      {
        id: 'indie_1month',
        planId: 'gdevelop_indie',
        period: 'month',
        periodCount: 1,
        currency: 'EUR',
        amountInCents: 200,
        region: 'everywhere',
      },
    ],
  },
  {
    id: 'gdevelop_pro',
    isLegacy: true,
    nameByLocale: { en: 'GDevelop Pro (Legacy)' },
    descriptionByLocale: { en: 'Experimented creators, ambitious games' },
    bulletPointsByLocale: [
      {
        en:
          '100 cloud projects with 500MB of resources per project and one-year version history.',
      },
      { en: '70 packagings per day for Android and for desktop.' },
      { en: 'Unlimited leaderboards and unlimited player feedback responses.' },
      {
        en:
          'Immerse your players by removing GDevelop logo when the game loads.',
      },
    ],
    pricingSystems: [
      {
        id: 'pro_1month',
        planId: 'gdevelop_pro',
        period: 'month',
        periodCount: 1,
        currency: 'EUR',
        amountInCents: 700,
        region: 'everywhere',
      },
    ],
  },
];

export const limitsForNoSubscriptionUser: Limits = {
  capabilities: {
    analytics: {
      sessions: true,
      players: false,
      retention: false,
      sessionsTimeStats: false,
      platforms: false,
    },
    cloudProjects: {
      maximumCount: 10,
      canMaximumCountBeIncreased: true,
      maximumGuestCollaboratorsPerProject: 0,
    },
    leaderboards: {
      maximumCountPerGame: 3,
      canMaximumCountPerGameBeIncreased: true,
      themeCustomizationCapabilities: 'NONE',
      canUseCustomCss: false,
    },
  },
  quotas: {
    'cordova-build': {
      current: 0,
      max: 2,
      limitReached: false,
    },
    'ai-project-generation': {
      current: 0,
      max: 3,
      limitReached: false,
    },
  },
  credits: {
    userBalance: {
      amount: 0,
    },
    prices: {},
    purchasableQuantities: {},
  },
  message: undefined,
};

export const limitsForSilverUser: Limits = {
  capabilities: {
    analytics: {
      sessions: true,
      players: true,
      retention: true,
      sessionsTimeStats: true,
      platforms: true,
    },
    cloudProjects: {
      maximumCount: 50,
      canMaximumCountBeIncreased: true,
      maximumGuestCollaboratorsPerProject: 0,
    },
    leaderboards: {
      maximumCountPerGame: -1,
      canMaximumCountPerGameBeIncreased: false,
      themeCustomizationCapabilities: 'BASIC',
      canUseCustomCss: false,
    },
  },
  quotas: {
    'cordova-build': {
      current: 2,
      max: 10,
      limitReached: false,
    },
    'ai-project-generation': {
      current: 3,
      max: 1000,
      limitReached: false,
    },
  },
  credits: {
    userBalance: {
      amount: 0,
    },
    prices: {},
    purchasableQuantities: {},
  },
  message: undefined,
};

export const limitsForGoldUser: Limits = {
  capabilities: {
    analytics: {
      sessions: true,
      players: true,
      retention: true,
      sessionsTimeStats: true,
      platforms: true,
    },
    cloudProjects: {
      maximumCount: 100,
      canMaximumCountBeIncreased: false,
      maximumGuestCollaboratorsPerProject: 0,
    },
    leaderboards: {
      maximumCountPerGame: -1,
      canMaximumCountPerGameBeIncreased: false,
      themeCustomizationCapabilities: 'FULL',
      canUseCustomCss: false,
    },
  },
  quotas: {
    'cordova-build': {
      current: 2,
      max: 70,
      limitReached: false,
    },
    'ai-project-generation': {
      current: 3,
      max: 1000,
      limitReached: false,
    },
  },
  credits: {
    userBalance: {
      amount: 0,
    },
    prices: {},
    purchasableQuantities: {},
  },
  message: undefined,
};

export const limitsForStartupUser: Limits = {
  capabilities: {
    analytics: {
      sessions: true,
      players: true,
      retention: true,
      sessionsTimeStats: true,
      platforms: true,
    },
    cloudProjects: {
      maximumCount: 500,
      canMaximumCountBeIncreased: false,
      maximumGuestCollaboratorsPerProject: 1,
    },
    leaderboards: {
      maximumCountPerGame: -1,
      canMaximumCountPerGameBeIncreased: false,
      themeCustomizationCapabilities: 'FULL',
      canUseCustomCss: false,
    },
  },
  quotas: {
    'cordova-build': {
      current: 2,
      max: 1000,
      limitReached: false,
    },
    'ai-project-generation': {
      current: 3,
      max: 1000,
      limitReached: false,
    },
  },
  credits: {
    userBalance: {
      amount: 0,
    },
    prices: {},
    purchasableQuantities: {},
  },
  message: undefined,
};

export const limitsForBusinessUser: Limits = {
  capabilities: {
    analytics: {
      sessions: true,
      players: true,
      retention: true,
      sessionsTimeStats: true,
      platforms: true,
    },
    cloudProjects: {
      maximumCount: 500,
      canMaximumCountBeIncreased: false,
      maximumGuestCollaboratorsPerProject: 1,
    },
    leaderboards: {
      maximumCountPerGame: -1,
      canMaximumCountPerGameBeIncreased: false,
      themeCustomizationCapabilities: 'FULL',
      canUseCustomCss: true,
    },
  },
  quotas: {
    'cordova-build': {
      current: 2,
      max: 1000,
      limitReached: false,
    },
    'ai-project-generation': {
      current: 3,
      max: 1000,
      limitReached: false,
    },
  },
  credits: {
    userBalance: {
      amount: 0,
    },
    prices: {},
    purchasableQuantities: {},
  },
  message: undefined,
};

export const limitsReached: Limits = {
  capabilities: {
    analytics: {
      sessions: true,
      players: true,
      retention: true,
      sessionsTimeStats: true,
      platforms: true,
    },
    cloudProjects: {
      maximumCount: 10,
      canMaximumCountBeIncreased: true,
      maximumGuestCollaboratorsPerProject: 0,
    },
    leaderboards: {
      maximumCountPerGame: 3,
      canMaximumCountPerGameBeIncreased: true,
      themeCustomizationCapabilities: 'BASIC',
      canUseCustomCss: false,
    },
  },
  quotas: {
    'cordova-build': {
      current: 10,
      max: 10,
      limitReached: true,
    },
    'ai-project-generation': {
      current: 3,
      max: 3,
      limitReached: true,
    },
  },
  credits: {
    userBalance: {
      amount: 0,
    },
    prices: {},
    purchasableQuantities: {},
  },
  message: undefined,
};

export const limitsForNoSubscriptionUserWithCredits: Limits = {
  capabilities: {
    analytics: {
      sessions: true,
      players: false,
      retention: false,
      sessionsTimeStats: false,
      platforms: false,
    },
    cloudProjects: {
      maximumCount: 10,
      canMaximumCountBeIncreased: true,
      maximumGuestCollaboratorsPerProject: 0,
    },
    leaderboards: {
      maximumCountPerGame: 3,
      canMaximumCountPerGameBeIncreased: true,
      themeCustomizationCapabilities: 'NONE',
      canUseCustomCss: false,
    },
  },
  quotas: {
    'cordova-build': {
      current: 0,
      max: 2,
      limitReached: false,
    },
    'ai-project-generation': {
      current: 0,
      max: 3,
      limitReached: false,
    },
  },
  credits: {
    userBalance: {
      amount: 1000,
    },
    prices: {},
    purchasableQuantities: {},
  },
  message: undefined,
};

const defaultAuthenticatedUserWithNoSubscription: AuthenticatedUser = {
  authenticated: true,
  profile: indieUserProfile,
  loginState: 'done',
  creatingOrLoggingInAccount: false,
  authenticationError: null,
  badges: null,
  cloudProjects: null,
  recommendations: [
    {
      type: 'gdevelop-tutorial',
      id: 'playlist-get-started',
    },
    {
      type: 'gdevelop-tutorial',
      id: 'gdevelop-teaching-kids',
    },
    {
      type: 'gdevelop-tutorial',
      id: 'tween-behavior',
    },
    {
      type: 'gdevelop-tutorial',
      id: 'wiki-play-music-and-sounds',
    },
    {
      type: 'gdevelop-tutorial',
      id: 'wiki-prefabs',
    },
    {
      type: 'guided-lessons',
      lessonsIds: ['healthBar', 'timer', 'plinkoMultiplier'],
    },
    {
      type: 'plan',
      id: 'gold',
    },
  ],
  cloudProjectsFetchingErrorLabel: null,
  firebaseUser: indieFirebaseUser,
  subscription: noSubscription,
  usages: usagesForIndieUser,
  limits: limitsForNoSubscriptionUser,
  receivedAssetPacks: [
    {
      id: '07a9f974-aeca-4a3f-b501-4808400eda4f',
      createdAt: '2022-12-13T19:45:47.318Z',
      updatedAt: '2022-12-13T19:45:47.318Z',
      name: 'Gamepasses',
      longDescription: '',
      previewImageUrls: [
        'https://resources.gdevelop-app.com/staging/private-assets/Gamepasses/thumbnail.png',
      ],
      tag: 'gamepasses',
      content: {},
    },
  ],
  receivedGameTemplates: [],
  receivedAssetShortHeaders: [],
  onLogin: async () => {},
  onLoginWithProvider: async () => {},
  onLogout: async () => {},
  onCreateAccount: async () => {},
  onResetPassword: async () => {},
  onEditProfile: async () => {},
  onOpenLoginDialog: () => {},
  onOpenEditProfileDialog: () => {},
  onOpenChangeEmailDialog: () => {},
  onOpenCreateAccountDialog: () => {},
  onOpenEmailVerificationDialog: () => {},
  onBadgesChanged: async () => {},
  onCloudProjectsChanged: async () => {},
  onRefreshUserProfile: async () => {
    console.info('This should refresh the user profile');
  },
  onRefreshSubscription: async () => {
    console.info('This should refresh the subscription');
  },
  onRefreshLimits: async () => {
    console.info('This should refresh the limits');
  },
  onPurchaseSuccessful: async () => {
    console.info('This should refresh the assets');
  },
  onRefreshFirebaseProfile: async () => {
    console.info('This should refresh the firebase profile');
  },
  onSendEmailVerification: async () => {
    console.info('This should send the email verification');
  },
  onAcceptGameStatsEmail: async () => {
    console.info('This should accept receiving game stats email');
  },
  getAuthorizationHeader: () => Promise.resolve('fake-authorization-header'),
};

export const fakeSilverAuthenticatedUser: AuthenticatedUser = {
  ...defaultAuthenticatedUserWithNoSubscription,
  subscription: subscriptionForSilverUser,
  limits: limitsForSilverUser,
};
export const fakeSilverButCancelAtPeriodEndAuthenticatedUser: AuthenticatedUser = {
  ...defaultAuthenticatedUserWithNoSubscription,
  subscription: silverSubscriptionButCancelAtPeriodEnd,
  limits: limitsForSilverUser,
};
export const fakeSilverAuthenticatedUserWithCloudProjects: AuthenticatedUser = {
  ...defaultAuthenticatedUserWithNoSubscription,
  cloudProjects: tenCloudProjects,
};

export const fakeGoldAuthenticatedUser: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  subscription: subscriptionForGoldUser,
  limits: limitsForGoldUser,
};
export const fakeStartupAuthenticatedUser: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  subscription: subscriptionForStartupUser,
  limits: limitsForStartupUser,
};
export const fakeBusinessAuthenticatedUser: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  subscription: subscriptionForBusinessUser,
  limits: limitsForBusinessUser,
};
export const fakeAuthenticatedUserWithEducationPlan: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  subscription: subscriptionForEducationPlan,
  limits: limitsForGoldUser,
};

export const fakeGoldWithPurchaselyAuthenticatedUser: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  subscription: purchaselyGoldSubscription,
  limits: limitsForGoldUser,
};

export const fakeAuthenticatedUserWithNoSubscription: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  subscription: noSubscription,
  limits: limitsForNoSubscriptionUser,
};

export const fakeAuthenticatedUserWithValidSilverRedemptionCode: AuthenticatedUser = {
  ...fakeAuthenticatedUserWithNoSubscription,
  subscription: silverSubscriptionWithRedemptionCode,
  limits: limitsForSilverUser,
};

export const fakeAuthenticatedUserWithExpiredSilverRedemptionCode: AuthenticatedUser = {
  ...fakeAuthenticatedUserWithNoSubscription,
  subscription: silverSubscriptionWithExpiredRedemptionCode,
  limits: limitsForSilverUser,
};

export const fakeAuthenticatedUserWithLegacyIndieSubscription = {
  ...fakeSilverAuthenticatedUser,
  subscription: subscriptionForIndieUser,
  limits: limitsForSilverUser,
};

export const fakeAuthenticatedUserWithLegacyProSubscription = {
  ...fakeSilverAuthenticatedUser,
  subscription: subscriptionForProUser,
  limits: limitsForGoldUser,
};

export const fakeAuthenticatedUserWithNoSubscriptionAndTooManyCloudProjects: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  cloudProjects: tenCloudProjects,
  subscription: noSubscription,
  limits: limitsReached,
};

export const fakeAuthenticatedUserWithEmailVerified: AuthenticatedUser = {
  ...defaultAuthenticatedUserWithNoSubscription,
  firebaseUser: indieVerifiedFirebaseUser,
};

export const fakeAuthenticatedUserLoggingIn: AuthenticatedUser = {
  ...defaultAuthenticatedUserWithNoSubscription,
  authenticated: true,
  loginState: 'loggingIn',
  profile: null,
  badges: null,
  cloudProjects: null,
  cloudProjectsFetchingErrorLabel: null,
  firebaseUser: null,
  subscription: null,
  usages: null,
  limits: null,
};

export const fakeAuthenticatedUserWithBadges: AuthenticatedUser = {
  ...defaultAuthenticatedUserWithNoSubscription,
  badges: [
    {
      seen: false,
      unlockedAt: '123',
      userId: indieUserProfile.id,
      achievementId: 'badge1',
    },
  ],
};

export const fakeAuthenticatedUserWithNoSubscriptionAndCredits: AuthenticatedUser = {
  ...fakeSilverAuthenticatedUser,
  subscription: noSubscription,
  limits: limitsForNoSubscriptionUserWithCredits,
};

export const fakeNotAuthenticatedUser: AuthenticatedUser = {
  ...defaultAuthenticatedUserWithNoSubscription,
  authenticated: false,
  profile: null,
  loginState: 'done',
  badges: null,
  cloudProjects: null,
  cloudProjectsFetchingErrorLabel: null,
  firebaseUser: null,
  subscription: null,
  usages: null,
  limits: null,
};

export const release: Release = {
  name: '5.0.0-beta62',
  publishedAt: '2019-01-14T23:32:41Z',
  url: 'https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta62',
  description:
    '> 💌Before listing the new features/improvements/bug fixes, a huge thanks to the contributors that allowed this new version to be what it is: @blurymind, @Bouh, @Lizard-13, @Wend1go, @zatsme 👏 GDevelop is growing thanks to you!\r\n\r\n## ✨New features\r\n\r\n* **Functions** are now "out of alpha testing" and always shown in the project manager. Functions are a powerful way to create new conditions, actions and expression using events. This allow to make your events and the logic of your game easier to understand and create. This also allow you to share common functions between games and create advanced features that are easy to use. [Learn more about functions on the wiki](https://wiki.gdevelop.io/gdevelop5/events/functions)\r\n* A brand new Physics engine: **Physics Engine 2.0**. (Thanks @Lizard-13 for creating it, testing it, improving it and creating examples and tests, and @zatsme for various update and examples!). While still based on the same internal physics engine, it is much more complete and powerful than the previous one:\r\n  * Support for a lot of joints (revolute, gear, mouse, prismatic, rope, pulley, wheel and more!)\r\n  * Support more options for bodies\r\n  * Support more shape and even custom polygons for objects.\r\n  * Look at the updated and **new examples** to learn how to use it and to see what\'s possible!\r\n\r\n  > Your existing games will continue to work with the old physics engine. You can still continue to use it. For new games, prefer to use the new Physics Engine 2.0. In your existing game, you can also replace *the behavior of all of your objects* by the new behavior, and replace *all the conditions and actions* by the conditions and actions from the new engine.\r\n* New **Screenshot** action, to take in-game screenshot for games running on Windows/macOS/Linux. (thanks @Wend1go!)\r\n  * This also come with new expressions to access to the **file system paths**, useful to save the screenshots in a folder of the user.\r\n\r\n## 💝 Improvements\r\n\r\n* Display missing files in resource editor as red (thanks @blurymind!)\r\n* Add option to set scale mode ("sampling") of the game to nearest (for "pixel perfect" or 8bit games) in the game properties.\r\n* Usability: autoclose project manager when opening an editor (thanks @blurymind!)\r\n* Add button to choose a new file for a resource in the resource editor (thanks @blurymind!)\r\n* New "Pixel perfect platform engine" example.\r\n* Usability: add shortcut to open Project Manager and focus search field when opening it.\r\n* Updated "Isometric Game" starter game to have better collision handling and mobile support.\r\n* Add GetAngle/GetXVelocity and GetYVelocity expressions to top-down movement behavior.\r\n* Extensions written in JavaScript can now be used to create new type of objects.\r\n* Usability: icons in the list of instructions or expressions are now displayed.\r\n\r\n## 🐛 Bug fixes \r\n\r\n* Update **Facebook Instant Games export** to have the now required bundle file (fbapp-config.json).\r\n* Fix the sentence in the events sheet of a Facebook Instant Games action. (thanks @Bouh!)\r\n* Fix descriptions of Storage actions to make clear that no "real" files are written.\r\n* Fix Left Shift key\r\n* Fix middle mouse button (thanks @Bouh!)\r\n* Fix visual artifacts when rendering rescaled games\r\n* Fix platform engine 1-pixel offset bug\r\n* Fix initial opacity undefined for text objects (thanks @Lizard-13)\r\n* Fix the condition checking if the cursor is on an object (thanks @Lizard-13)\r\n* Avoid crash of the debugger with Particle Emitters\r\n* Add explicit "OK" button in message box to fix issue on Linux\r\n* Usability: hide object drop-down list after an object is selected\r\n* Fix login dialog not showing on top of export dialog',
};

export const releaseWithBreakingChange: Release = {
  name: '5.0.0-beta60',
  publishedAt: '2019-01-07T23:32:41Z',
  url: 'https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta60',
  description:
    '> ⚠️ Blabla, beware there is a breaking change!!!\r\n\r\n## ✨New features\r\n\r\n* **Functions** are now "out of alpha testing" and always shown in the project manager. Functions are a powerful way to create new conditions, actions and expression using events. This allow to make your events and the logic of your game easier to understand and create. This also allow you to share common functions between games and create advanced features that are easy to use. [Learn more about functions on the wiki](https://wiki.gdevelop.io/gdevelop5/events/functions)\r\n* A brand new Physics engine: **Physics Engine 2.0**. (Thanks @Lizard-13 for creating it, testing it, improving it and creating examples and tests, and @zatsme for various update and examples!). While still based on the same internal physics engine, it is much more complete and powerful than the previous one:\r\n  * Support for a lot of joints (revolute, gear, mouse, prismatic, rope, pulley, wheel and more!)\r\n  * Support more options for bodies\r\n  * Support more shape and even custom polygons for objects.\r\n  * Look at the updated and **new examples** to learn how to use it and to see what\'s possible!\r\n\r\n  > Your existing games will continue to work with the old physics engine. You can still continue to use it. For new games, prefer to use the new Physics Engine 2.0. In your existing game, you can also replace *the behavior of all of your objects* by the new behavior, and replace *all the conditions and actions* by the conditions and actions from the new engine.\r\n* New **Screenshot** action, to take in-game screenshot for games running on Windows/macOS/Linux. (thanks @Wend1go!)\r\n  * This also come with new expressions to access to the **file system paths**, useful to save the screenshots in a folder of the user.\r\n\r\n## 💝 Improvements\r\n\r\n* Display missing files in resource editor as red (thanks @blurymind!)\r\n* Add option to set scale mode ("sampling") of the game to nearest (for "pixel perfect" or 8bit games) in the game properties.\r\n* Usability: autoclose project manager when opening an editor (thanks @blurymind!)\r\n* Add button to choose a new file for a resource in the resource editor (thanks @blurymind!)\r\n* New "Pixel perfect platform engine" example.\r\n* Usability: add shortcut to open Project Manager and focus search field when opening it.\r\n* Updated "Isometric Game" starter game to have better collision handling and mobile support.\r\n* Add GetAngle/GetXVelocity and GetYVelocity expressions to top-down movement behavior.\r\n* Extensions written in JavaScript can now be used to create new type of objects.\r\n* Usability: icons in the list of instructions or expressions are now displayed.\r\n\r\n## 🐛 Bug fixes \r\n\r\n* Update **Facebook Instant Games export** to have the now required bundle file (fbapp-config.json).\r\n* Fix the sentence in the events sheet of a Facebook Instant Games action. (thanks @Bouh!)\r\n* Fix descriptions of Storage actions to make clear that no "real" files are written.\r\n* Fix Left Shift key\r\n* Fix middle mouse button (thanks @Bouh!)\r\n* Fix visual artifacts when rendering rescaled games\r\n* Fix platform engine 1-pixel offset bug\r\n* Fix initial opacity undefined for text objects (thanks @Lizard-13)\r\n* Fix the condition checking if the cursor is on an object (thanks @Lizard-13)\r\n* Avoid crash of the debugger with Particle Emitters\r\n* Add explicit "OK" button in message box to fix issue on Linux\r\n* Usability: hide object drop-down list after an object is selected\r\n* Fix login dialog not showing on top of export dialog',
};

export const releaseWithoutDescription: Release = {
  name: '5.0.0-beta60',
  publishedAt: '2019-01-07T23:32:41Z',
  url: 'https://github.com/4ian/GDevelop/releases/tag/v5.0.0-beta60',
  description: null,
};

export const erroredCordovaBuild: Build = {
  id: 'errored-build-id',
  gameId: 'errored-game-id',
  status: 'error',
  logsKey: '/fake-error.log',
  createdAt: 1515084391000,
  updatedAt: Date.now(),
  userId: 'fake-user-id',
  type: 'cordova-build',
};

export const pendingCordovaBuild: Build = {
  id: 'pending-build-id',
  gameId: 'pending-game-id',
  status: 'pending',
  createdAt: 1515084391000,
  updatedAt: Date.now(),
  userId: 'fake-user-id',
  type: 'cordova-build',
};

export const pendingElectronBuild: Build = {
  id: 'pending-build-id',
  gameId: 'pending-game-id',
  status: 'pending',
  createdAt: 1515084391000,
  updatedAt: Date.now(),
  userId: 'fake-user-id',
  type: 'electron-build',
};

export const completeCordovaBuild: Build = {
  id: 'complete-build-id',
  gameId: 'complete-game-id',
  createdAt: 1515084391000,
  userId: 'fake-user-id',
  type: 'cordova-build',
  status: 'complete',
  logsKey: '/fake-error.log',
  apkKey: '/fake-game.apk',
  updatedAt: Date.now(),
};

export const completeElectronBuild: Build = {
  id: 'complete-build-id',
  gameId: 'complete-game-id',
  createdAt: 1515084391000,
  userId: 'fake-user-id',
  type: 'electron-build',
  status: 'complete',
  logsKey: '/fake-error.log',
  windowsExeKey: '/fake-windows-game.exe',
  windowsZipKey: '/fake-windows-game.zip',
  macosZipKey: '/fake-macos-game.zip',
  linuxAppImageKey: '/fake-linux-game.AppImage',
  updatedAt: Date.now(),
};

export const completeWebBuild: Build = {
  id: 'complete-build-id',
  gameId: 'complete-game-id',
  createdAt: 1515084391000,
  userId: 'fake-user-id',
  type: 'web-build',
  status: 'complete',
  logsKey: '/fake-error.log',
  s3Key: 'game-12345',
  updatedAt: Date.now(),
};

const spaceshipSerializedObject = {
  name: 'PlayerSpaceship',
  tags: '',
  type: 'Sprite',
  updateIfNotVisible: false,
  variables: [
    {
      name: 'State',
      value: 'Spaceship',
    },
  ],
  behaviors: [],
  animations: [
    {
      name: 'SpaceshipIdle',
      useMultipleDirections: false,
      directions: [
        {
          looping: true,
          timeBetweenFrames: 0.08,
          sprites: [
            {
              hasCustomCollisionMask: false,
              image: 'player-ship1.png',
              points: [],
              originPoint: {
                name: 'origine',
                x: 0,
                y: 0,
              },
              centerPoint: {
                automatic: true,
                name: 'centre',
                x: 0,
                y: 0,
              },
              customCollisionMask: [],
            },
            {
              hasCustomCollisionMask: false,
              image: 'player-ship2.png',
              points: [],
              originPoint: {
                name: 'origine',
                x: 0,
                y: 0,
              },
              centerPoint: {
                automatic: true,
                name: 'centre',
                x: 0,
                y: 0,
              },
              customCollisionMask: [],
            },
          ],
        },
      ],
    },
  ],
};

const spaceshipSerializedResources = [
  {
    alwaysLoaded: false,
    file: 'https://example.com/player-ship1.png',
    origin: {
      name: 'gdevelop-asset-store',
      identifier: 'https://example.com/player-ship1.png',
    },
    kind: 'image',
    metadata: '',
    name: 'player-ship1.png',
    smoothed: false,
    userAdded: false,
  },
  {
    alwaysLoaded: false,
    file: 'https://example.com/player-ship2.png',
    origin: {
      name: 'gdevelop-asset-store',
      identifier: 'https://example.com/player-ship2.png',
    },
    kind: 'image',
    metadata: '',
    name: 'player-ship2.png',
    smoothed: false,
    userAdded: false,
  },
];

export const fakeAsset1: Asset = {
  id: '123',
  name: 'My spaceship',
  shortDescription:
    'A spaceship that can be moved with the keyboard or by touching the screen',
  description: "A very nice way to start a shoot'em up.",
  previewImageUrls: [
    'https://asset-resources.gdevelop.io/public-resources/Simple Space/spaceships/b0e7ae371773ea6cf1e18a7db1d32ea1b4b9dd388f1f31aed5b7c1501437292c_Complex Spaceship_Type A.png',
  ],
  animationsCount: 6,
  maxFramesCount: 6,
  height: 36,
  width: 36,
  objectType: 'sprite',
  gdevelopVersion: '5.0.0-beta100',
  version: '1.0.0',
  authors: ['test author'],
  license: 'MIT',
  tags: ['space shooter', 'tag2'],
  dominantColors: [255],
  objectAssets: [
    {
      object: spaceshipSerializedObject,
      resources: spaceshipSerializedResources,
      requiredExtensions: [],
    },
  ],
};

export const fakePixelArtAsset1: Asset = {
  ...fakeAsset1,
  tags: ['space shooter', 'tag2', 'pixel art'],
};

export const fakeAssetWithCustomObject: Asset = {
  id: '123',
  name: 'YellowButton',
  authors: ['Kenney'],
  license: 'CC0 (public domain)',
  shortDescription: 'button',
  description: 'A button that can be clicked.',
  tags: ['custom objects', 'button'],
  objectAssets: [
    {
      object: {
        name: 'YellowButton',
        type: 'Button::PanelSpriteButton',
        content: {
          LeftPadding: 16,
          RightPadding: 16,
          PressedLabelOffsetY: 10,
          IdleLabelOffsetY: -8,
          BottomPadding: 32,
          TopPadding: 16,
          MinimalWidth: 300,
        },
        childrenContent: {
          Label: {
            bold: false,
            italic: false,
            smoothed: true,
            underlined: false,
            string: 'Start',
            font: '',
            characterSize: 60,
            color: { b: 42, g: 87, r: 139 },
          },
          Idle: {
            bottomMargin: 32,
            height: 106,
            leftMargin: 16,
            rightMargin: 16,
            texture: 'object_YellowButton_Idle.png',
            tiled: true,
            topMargin: 16,
            width: 256,
          },
          Hovered: {
            bottomMargin: 32,
            height: 106,
            leftMargin: 16,
            rightMargin: 16,
            texture: 'object_YellowButton_Hovered.png',
            tiled: true,
            topMargin: 16,
            width: 256,
          },
          Pressed: {
            bottomMargin: 16,
            height: 106,
            leftMargin: 16,
            rightMargin: 16,
            texture: 'object_YellowButton_Pressed.png',
            tiled: true,
            topMargin: 32,
            width: 256,
          },
        },
      },
      resources: [
        {
          alwaysLoaded: false,
          file:
            'https://resources.gdevelop-app.com/assets/Custom objects/object_YellowButton_Hovered.png',
          kind: 'image',
          metadata: '',
          name: 'object_YellowButton_Hovered.png',
          userAdded: false,
          origin: {
            name: 'gdevelop-asset-store',
            identifier:
              'https://resources.gdevelop-app.com/assets/Custom objects/object_YellowButton_Hovered.png',
          },
        },
        {
          alwaysLoaded: false,
          file:
            'https://resources.gdevelop-app.com/assets/Custom objects/object_YellowButton_Idle.png',
          kind: 'image',
          metadata: '',
          name: 'object_YellowButton_Idle.png',
          userAdded: false,
          origin: {
            name: 'gdevelop-asset-store',
            identifier:
              'https://resources.gdevelop-app.com/assets/Custom objects/object_YellowButton_Idle.png',
          },
        },
        {
          alwaysLoaded: false,
          file:
            'https://resources.gdevelop-app.com/assets/Custom objects/object_YellowButton_Pressed.png',
          kind: 'image',
          metadata: '',
          name: 'object_YellowButton_Pressed.png',
          userAdded: false,
          origin: {
            name: 'gdevelop-asset-store',
            identifier:
              'https://resources.gdevelop-app.com/assets/Custom objects/object_YellowButton_Pressed.png',
          },
        },
      ],
      requiredExtensions: [
        {
          extensionName: 'Button',
          extensionVersion: '1.0.0',
        },
      ],
    },
  ],
  gdevelopVersion: '5.0.0-beta100',
  version: '1.0.0',
  objectType: 'object',
  animationsCount: 1,
  maxFramesCount: 1,
  previewImageUrls: [
    'https://asset-resources.gdevelop.io/public-resources/Menu buttons/3e1b2da0279f60b6a6d1cfe4c79875b70a81b0bec7aa45ff18bff03eb26326eb_Yellow Button.preview.png',
  ],
  width: 256,
  height: 106,
  dominantColors: [16304136],
};

export const fakeAssetWithUnknownExtension1: Asset = {
  id: '123',
  name: 'My spaceship',
  shortDescription:
    'A spaceship that can be moved with the keyboard or by touching the screen',
  description: "A very nice way to start a shoot'em up.",
  previewImageUrls: ['res/GD-logo.png'],
  animationsCount: 6,
  maxFramesCount: 6,
  height: 36,
  width: 36,
  objectType: 'sprite',
  gdevelopVersion: '5.0.0-beta100',
  version: '1.0.0',
  authors: ['test author'],
  license: 'MIT',
  tags: ['space shooter', 'tag2'],
  dominantColors: [255],
  objectAssets: [
    {
      object: spaceshipSerializedObject,
      resources: spaceshipSerializedResources,
      requiredExtensions: [
        {
          extensionName: 'UnknownExtension',
          extensionVersion: '1.0.0',
        },
      ],
    },
  ],
};

export const fakeAssetWithFlashExtensionDependency1: Asset = {
  id: '123',
  name: 'My spaceship',
  shortDescription:
    'A spaceship that can be moved with the keyboard or by touching the screen',
  description: "A very nice way to start a shoot'em up.",
  previewImageUrls: ['res/GD-logo.png'],
  animationsCount: 6,
  maxFramesCount: 6,
  height: 36,
  width: 36,
  objectType: 'sprite',
  gdevelopVersion: '5.0.0-beta100',
  version: '1.0.0',
  authors: ['test author'],
  license: 'MIT',
  tags: ['space shooter', 'tag2'],
  dominantColors: [255],
  objectAssets: [
    {
      object: spaceshipSerializedObject,
      resources: spaceshipSerializedResources,
      requiredExtensions: [
        {
          extensionName: 'Flash',
          extensionVersion: '1.0.0',
        },
      ],
    },
  ],
};

export const fakeAssetShortHeader1: AssetShortHeader = {
  id: 'a4eb5460ffc062ece1f3ff45d24b07e40e9d4247d21602de70973049eb4f6ee5',
  license:
    'CC-BY 4.0 (Attribution to the artist is required, click for details)',
  animationsCount: 6,
  maxFramesCount: 6,
  height: 36,
  width: 36,
  name: 'Dino Doux',
  objectType: 'sprite',
  previewImageUrls: [
    'https://resources.gdevelop-app.com/assets/24x24 Dino Characters/Dino Doux_Crouch.png',
  ],
  shortDescription: 'with 6 animations',
  tags: [
    '24x24 dino characters',
    'side view',
    'pixel art',
    'character',
    'player',
    'enemy',
  ],
  dominantColors: [255],
};

export const fakeAssetShortHeader2: AssetShortHeader = {
  id: 'faaa5460ffc062ece1f3ff45d24b07e40e9d4247d21602de70973049eb4f6ee6',
  license:
    'CC-BY 4.0 (Attribution to the artist is required, click for details)',
  animationsCount: 6,
  maxFramesCount: 6,
  height: 36,
  width: 36,
  name: 'Dino Doux 2',
  objectType: 'sprite',
  previewImageUrls: [
    'https://resources.gdevelop-app.com/assets/24x24 Dino Characters/Dino Doux_Crouch.png',
  ],
  shortDescription: 'with 5 animations',
  tags: [
    '24x24 dino characters',
    'side view',
    'pixel art',
    'character',
    'player',
    'enemy',
  ],
  dominantColors: [255],
};

export const fakePrivateAssetShortHeader1: AssetShortHeader = {
  id: 'bcdef460ffc062ece1f3ff45d24b07e40e9d4247d21602de70973049eb4f6ee5',
  license:
    'CC-BY 4.0 (Attribution to the artist is required, click for details)',
  animationsCount: 6,
  maxFramesCount: 6,
  height: 36,
  width: 36,
  name: 'Premium Dino Doux',
  objectType: 'sprite',
  previewImageUrls: ['https://private-assets.gdevelop.io/fake-preview.png'],
  shortDescription: 'with 10 animations',
  tags: [
    '24x24 dino characters',
    'side view',
    'pixel art',
    'character',
    'player',
    'enemy',
  ],
  dominantColors: [255],
};

export const fakePrivateAsset1: Asset = {
  ...fakePrivateAssetShortHeader1,
  description: 'A very nice Dino.',
  gdevelopVersion: '5.0.0-beta100',
  version: '1.0.0',
  authors: ['test author'],
  dominantColors: [255],
  objectAssets: [
    {
      object: {},
      resources: [],
      requiredExtensions: [],
    },
  ],
};

export const fireBulletExtensionShortHeader: ExtensionShortHeader = {
  tier: 'reviewed',
  authorIds: [],
  shortDescription:
    'Allow the object to fire bullets, with customizable speed, angle and fire rate.',
  extensionNamespace: '',
  fullName: 'Fire bullets',
  name: 'FireBullet',
  version: '0.0.2',
  url: 'https://resources.gdevelop-app.com/extensions/FireBullet.json',
  headerUrl:
    'https://resources.gdevelop-app.com/extensions/FireBullet-header.json',
  tags: ['fire', 'bullets', 'spawn', 'firerate'],
  category: 'Movement',
  previewIconUrl: 'https://resources.gdevelop-app.com/assets/Icons/repeat.svg',
  eventsBasedBehaviorsCount: 1,
  eventsFunctionsCount: 0,
};

export const fireBulletExtensionHeader: ExtensionHeader = {
  ...fireBulletExtensionShortHeader,
  description:
    'This is a longer description explaining:\n* How to\n* Use the extension\n\nWith *some* **markdown** :)',
  helpPath: 'https://example.com',
  iconUrl: 'https://resources.gdevelop-app.com/assets/Icons/repeat.svg',
};

export const uncompatibleFireBulletExtensionShortHeader: ExtensionShortHeader = {
  ...fireBulletExtensionShortHeader,
  gdevelopVersion: '2000.0.0',
};

export const alreadyInstalledExtensionShortHeader: ExtensionShortHeader = {
  ...fireBulletExtensionShortHeader,
  name: 'SomeAlreadyInstalledExtension',
  version: '1.2.3',
};

export const newerVersionExtensionShortHeader: ExtensionShortHeader = {
  ...fireBulletExtensionShortHeader,
  name: 'SomeAlreadyInstalledExtension',
  version: '1.2.4',
};

export const alreadyInstalledCommunityExtensionShortHeader: ExtensionShortHeader = {
  ...fireBulletExtensionShortHeader,
  tier: 'community',
  name: 'SomeAlreadyInstalledExtension',
};

export const flashExtensionShortHeader: ExtensionShortHeader = {
  tier: 'reviewed',
  authorIds: [],
  shortDescription:
    'Make the object flash (blink) for a period of time, so that it is alternately visible and invisible.\nTrigger the effect by using the Flash action.',
  extensionNamespace: '',
  fullName: 'Flash (blink)',
  name: 'Flash',
  version: '1.0.0',
  url: 'Extensions/Flash.json',
  headerUrl: 'Extensions/Flash-header.json',
  tags: ['flash', 'blink', 'visible', 'invisible', 'hit', 'damage'],
  category: 'Visual effect',
  previewIconUrl: 'https://resources.gdevelop-app.com/assets/Icons/repeat.svg',
  eventsBasedBehaviorsCount: 1,
  eventsFunctionsCount: 0,
};

export const buttonV1ExtensionShortHeader: ExtensionShortHeader = {
  tier: 'reviewed',
  authorIds: [],
  shortDescription: 'An extension that is already installed in the project.',
  extensionNamespace: '',
  fullName: 'Button',
  name: 'Button',
  version: '1.0.0',
  url: 'Extensions/Button.json',
  headerUrl: '',
  tags: [],
  category: '',
  previewIconUrl: '',
  eventsBasedBehaviorsCount: 1,
  eventsFunctionsCount: 0,
};

export const buttonV2ExtensionShortHeader: ExtensionShortHeader = {
  ...buttonV1ExtensionShortHeader,
  version: '2.0.0',
};

export const communityTierExtensionShortHeader: ExtensionShortHeader = {
  tier: 'community',
  authorIds: [],
  shortDescription:
    'This is an example of an extension that is a community extension (not reviewed).',
  extensionNamespace: '',
  fullName: 'Fake Community extension',
  name: 'FakeCommunityExtension',
  version: '0.0.2',
  url:
    'https://resources.gdevelop-app.com/extensions/FakeCommunityExtension.json',
  headerUrl:
    'https://resources.gdevelop-app.com/extensions/FakeCommunityExtension-header.json',
  tags: ['fire', 'bullets', 'spawn', 'firerate'],
  category: '',
  previewIconUrl: 'https://resources.gdevelop-app.com/assets/Icons/repeat.svg',
  eventsBasedBehaviorsCount: 1,
  eventsFunctionsCount: 0,
};

export const communityTierExtensionHeader: ExtensionHeader = {
  ...communityTierExtensionShortHeader,
  description:
    'This is a longer description explaining:\n* How to\n* Use the extension\n\nWith *some* **markdown** :)',
  helpPath: 'https://example.com',
  iconUrl: 'https://resources.gdevelop-app.com/assets/Icons/repeat.svg',
};

export const fakeGame: Game = {
  id: 'complete-game-id',
  authorName: 'SonicFan',
  gameName: 'Sonic1995',
  createdAt: 1606065498,
  publicWebBuildId: 'fake-public-web-build-id-sonic',
  displayAdsOnGamePage: true,
};

export const game1: Game = {
  id: 'fake-game1-id',
  authorName: 'My company',
  gameName: 'My Great Game',
  createdAt: 1606065498,
  publicWebBuildId: 'fake-publicwebbuild-id',
  displayAdsOnGamePage: true,
};

export const game2: Game = {
  id: 'fake-game2-id',
  authorName: 'My company',
  gameName: 'My Other Game',
  createdAt: 1607065498,
};

export const gameWithDisplayAdsOnGamePageEnabled: Game = {
  ...game1,
  displayAdsOnGamePage: true,
};

export const gameWithDisplayAdsOnGamePageDisabled: Game = {
  ...game1,
  displayAdsOnGamePage: false,
};

/**
 * It uses the ANSI C one because Number.MAX_SAFE_INTEGER is 2^53
 * and this one multiply a seed of 2^15 with a multiplier of 2^32.
 * https://en.wikipedia.org/wiki/Linear_congruential_generator
 * The randomization is poor, but ok for placeholder values.
 */
class NumberGenerator {
  x: number;

  constructor(x = 1) {
    this.x = x % 2 ** 15;
  }

  /**
   * @returns a number inside [0 ; 1[.
   */
  getNextRandomNumber(): number {
    // Masks would more efficient but less readable.
    this.x = (1103515245 * this.x + 12345) % 2 ** 31 >> 16;
    return this.x / 2 ** 15;
  }
}

const interpolateWithNoise = (
  leftValue: number,
  rightValue: number,
  ratio: number,
  numberGenerator: NumberGenerator
) =>
  ((1 - ratio) * leftValue + ratio * rightValue) *
  (0.95 + 0.1 * numberGenerator.getNextRandomNumber());

const generateGameRollingMetricsFor364Days = () => {
  const numberGenerator = new NumberGenerator();
  const metrics = [];
  const count = 364;
  for (let index = 0; index < count; index++) {
    const ratio = 1 - index / count;
    const playersCount = Math.round(
      interpolateWithNoise(50, 250, ratio, numberGenerator)
    );
    metrics.push({
      date: formatISO(subDays(new Date(), index)),

      sessions: {
        d0Sessions: Math.round(
          interpolateWithNoise(80, 350, ratio, numberGenerator)
        ),
        d0SessionsDurationTotal: Math.round(
          interpolateWithNoise(15000, 175000, ratio, numberGenerator)
        ),
      },
      players: {
        d0Players: playersCount,
        d0NewPlayers: Math.round(
          interpolateWithNoise(80, 120, ratio, numberGenerator)
        ),
        d0PlayersBelow60s: Math.round(
          playersCount * interpolateWithNoise(0.8, 0.4, ratio, numberGenerator)
        ),
        d0PlayersBelow180s: Math.round(
          playersCount * interpolateWithNoise(0.9, 0.55, ratio, numberGenerator)
        ),
        d0PlayersBelow300s: Math.round(
          playersCount * interpolateWithNoise(0.95, 0.6, ratio, numberGenerator)
        ),
        d0PlayersBelow600s: Math.round(
          playersCount * interpolateWithNoise(0.98, 0.7, ratio, numberGenerator)
        ),
        d0PlayersBelow900s: Math.round(
          playersCount *
            Math.min(1, interpolateWithNoise(1, 0.9, ratio, numberGenerator))
        ),
      },
      retention: {
        d1RetainedPlayers: 193,
        d2RetainedPlayers: 153,
        d3RetainedPlayers: 121,
        d4RetainedPlayers: 83,
        d5RetainedPlayers: 74,
        d6RetainedPlayers: 73,
        d7RetainedPlayers: 67,
      },
    });
  }
  return metrics;
};

const deleteDurationMetrics = (
  gameMetrics: GameMetrics[],
  startDays: number
): GameMetrics[] => {
  for (let index = startDays; index < gameMetrics.length; index++) {
    const gameMetric = gameMetrics[index];
    const sessions = gameMetric.sessions;
    const players = gameMetric.players;
    if (sessions) {
      sessions.d0SessionsDurationTotal = undefined;
    }
    if (players) {
      players.d0PlayersBelow60s = undefined;
      players.d0PlayersBelow180s = undefined;
      players.d0PlayersBelow300s = undefined;
      players.d0PlayersBelow600s = undefined;
      players.d0PlayersBelow900s = undefined;
    }
  }
  return gameMetrics;
};

export const gameRollingMetricsFor364Days: GameMetrics[] = generateGameRollingMetricsFor364Days();
export const gameRollingMetricsWithUndefinedDurationMetrics: GameMetrics[] = deleteDurationMetrics(
  generateGameRollingMetricsFor364Days(),
  17
);
export const gameRollingMetricsWithOnly19Days: GameMetrics[] = gameRollingMetricsFor364Days.slice(
  0,
  19
);
export const gameRollingMetricsWithOnly1Day: GameMetrics[] = gameRollingMetricsFor364Days.slice(
  0,
  1
);
export const gameRollingMetricsWithHoles: GameMetrics[] = [
  4,
  12,
  13,
  25,
  33,
  107,
  108,
  109,
  110,
  230,
].map(index => gameRollingMetricsFor364Days[index]);
export const gameRollingMetricsWithoutPlayersAndRetention1: GameMetrics[] = [
  {
    date: '2020-10-01',

    sessions: {
      d0Sessions: 350,
      d0SessionsDurationTotal: 175000,
    },
    players: null,
    retention: null,
  },
];

export const showcasedGame1: ShowcasedGame = {
  title: "Lil BUB's HELLO EARTH",
  author: "Lil BUB's Team",
  description:
    'BUB is a very special, one of a kind critter. More specifically, she is the [most amazing cat on the planet](http://lilbub.com)... and her game is made with GDevelop!\n\nThe game is a retro 8-bit game, with beautiful arts and soundtrack, which alternates between platformers levels, with hidden secrets, and shooter levels with bosses, multiple enemies and bonuses.',
  tags: [
    'Action',
    'Platform',
    'Shooter',
    'Adventure',
    'Android',
    'iOS',
    'Windows',
    'macOS',
    'Linux',
  ],
  genres: ['Action', 'Platform', 'Shooter', 'Adventure'],
  platforms: ['Android', 'iOS', 'Windows', 'macOS', 'Linux'],
  imageUrls: [
    'https://resources.gdevelop-app.com/games-showcase/images/18JKXDTWljabX3O09SW2VKYOThZkIf1jG',
  ],
  links: [
    {
      url:
        'https://itunes.apple.com/us/app/lil-bubs-hello-earth/id1123383033?mt=8',
      type: 'app-store',
    },
    {
      url: 'https://play.google.com/store/apps/details?id=com.lilbub.game',
      type: 'play-store',
    },
    {
      url: 'http://compilgames.net/bub-landing-page',
      type: 'download-win-mac-linux',
    },
    { url: '/games/lil-bub-hello-earth', type: 'learn-more' },
  ],
  isFeatured: false,
  bannerUrl:
    'https://resources.gdevelop-app.com/games-showcase/images/bub-game-banner.jpg',
  bannerBackgroundPosition: '',
  thumbnailUrl:
    'https://resources.gdevelop-app.com/games-showcase/images/bub-animated-logo.gif',
  editorDescription: '',
};

export const exampleFromFutureVersion: ExampleShortHeader = {
  id: 'fake-id',
  slug: 'fake-slug',
  name: 'Fake example',
  shortDescription: 'This is a fake example made in a future GDevelop version',
  license: 'MIT',
  tags: [],
  previewImageUrls: [],
  gdevelopVersion: '99.0.0',
  codeSizeLevel: 'small',
};

export const geometryMonsterExampleShortHeader: ExampleShortHeader = {
  id: '2ff24efa0de9b1340d7e8c8aedb494af6b4db9a72c6a643303734755efb977df',
  name: 'Geometry monster',
  slug: 'geometry-monster',
  shortDescription:
    'A hyper casual endless game where you have to collect shapes and avoid bombs, with a progressively increasing difficulty.\n',
  license: 'MIT',
  previewImageUrls: [
    'https://resources.gdevelop-app.com/examples/geometry-monster/thumbnail.png',
  ],
  authorIds: [],
  tags: [
    'geometry-monster',
    '',
    'Advanced control features',
    'Audio',
    'Standard Conversions',
    'Builtin events',
    'Keyboard features',
    'Mathematical tools',
    'Mouse and touch',
    'Features for all objects',
    'Scene management features',
    'Time',
    'Variable features',
    'Particle system',
    'Sprite',
    'Text object',
    'Stay On Screen',
    'Sine (or ellipsis) Movement',
    'Flash (blink)',
    'Health (life points and damages for objects)',
  ],
  gdevelopVersion: '',
  codeSizeLevel: 'small',
};

export const fakePrivateGameTemplateListingData: PrivateGameTemplateListingData = {
  name: 'Fake private game template',
  description: 'This is a fake private game template',
  id: 'fake-id',
  sellerId: 'fake-seller-id',
  isSellerGDevelop: false,
  productType: 'GAME_TEMPLATE',
  listing: 'GAME_TEMPLATE',
  categories: ['adventure'],
  updatedAt: '2020-01-01',
  createdAt: '2020-01-01',
  thumbnailUrls: [],
  prices: [],
  appStoreProductId: 'fake-app-store-product-id',
  includedListableProductIds: [],
  sellerStripeAccountId: 'fake-seller-stripe-account-id',
  stripeProductId: 'fake-stripe-product-id',
};

export const fakeAssetPacks: PublicAssetPacks = {
  starterPacks: [
    {
      name: 'GDevelop Platformer',
      tag: 'platformer',
      categories: ['full-game-pack'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/platformer.png',
      assetsCount: 16,
      authors: [],
      licenses: [],
    },
    {
      name: 'Space Shooter',
      tag: 'space shooter',
      categories: [],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/space shooter.png',
      assetsCount: 140,
      authors: [],
      licenses: [],
    },
    {
      name: 'Tanks',
      tag: 'tank pack',
      categories: [],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/tank pack.png',
      assetsCount: 32,
      authors: [],
      licenses: [],
    },
    {
      name: 'Pixel Adventure',
      tag: 'pixel adventure pack',
      categories: ['full-game-pack'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/pixel adventure pack.png',
      assetsCount: 80,
      authors: [],
      licenses: [],
    },
    {
      name: 'Fake Paid External',
      tag: 'pirate bomb pack',
      categories: ['full-game-pack'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/pirate bomb pack.png',
      assetsCount: 48,
      authors: [],
      licenses: [],
      externalWebLink: 'https://example.com',
      userFriendlyPrice: '$4.99',
    },
    {
      name: 'Particles',
      tag: 'pixel effects pack',
      categories: ['visual-effect'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/pixel effects pack.png',
      assetsCount: 20,
      authors: [],
      licenses: [],
    },
    {
      name: 'Emotes',
      tag: 'emote',
      categories: [],
      thumbnailUrl: 'https://resources.gdevelop-app.com/assets/Packs/emote.png',
      assetsCount: 176,
      authors: [],
      licenses: [],
    },
    {
      name: 'Dinosaurus Characters',
      tag: '24x24 dino characters',
      categories: ['character'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/24x24 dino characters.png',
      assetsCount: 5,
      authors: [],
      licenses: [],
    },
    {
      name: 'Fake Paid Spinning Items',
      tag: '16x16 pixel art spinning items',
      categories: ['props'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/16x16 pixel art spinning items.png',
      assetsCount: 30,
      authors: [],
      licenses: [],
      userFriendlyPrice: '$4.99',
    },
    {
      name: 'RPG Items #2',
      tag: '16x16 pixel art rpg items',
      categories: ['props'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/16x16 pixel art rpg items.png',
      assetsCount: 64,
      authors: [],
      licenses: [],
    },
    {
      name: 'RPG Items',
      tag: '16x16 rpg item pack',
      categories: ['props'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/16x16 rpg item pack.png',
      assetsCount: 144,
      authors: [],
      licenses: [],
    },
    {
      name: 'Fantasy Icons',
      tag: '32x32 fantasy icons pack v2',
      categories: [],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/32x32 fantasy icons pack v2.png',
      assetsCount: 285,
      authors: [],
      licenses: [],
    },
    {
      name: 'On-Screen Controls',
      tag: 'on-screen controls',
      categories: ['interface'],
      thumbnailUrl:
        'https://resources.gdevelop-app.com/assets/Packs/on-screen controls.png',
      assetsCount: 287,
      authors: [],
      licenses: [],
    },
  ],
};

export const commentUnprocessed: Comment = {
  id: 'comment-unprocessed-id',
  type: 'FEEDBACK',
  gameId: 'complete-game-id',
  buildId: 'complete-build-id',
  text:
    "This is my honest feedback: I think the art is cute. Specially on the screen when it jumps over the chickens. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
  ratings: {
    version: 1,
    visuals: 2,
    sound: 4,
    fun: 6,
    easeOfUse: 8,
  },
  playerName: 'playerName', // For non-authenticated comments.
  createdAt: 1515084391000,
  updatedAt: 1515084393000,
};

export const commentProcessed: Comment = {
  id: 'comment-processed-id',
  type: 'FEEDBACK',
  gameId: 'complete-game-id',
  buildId: 'complete-build-id',
  text:
    "This is my honest feedback: I think the art is cute. Specially on the screen when it jumps over the chickens. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
  ratings: {
    version: 1,
    visuals: 2,
    sound: 4,
    fun: 6,
    easeOfUse: 8,
  },
  playerName: 'playerName', // For non-authenticated comments.
  createdAt: 1515084391000,
  updatedAt: 1515084393000,
  processedAt: 1515084393000,
};

export const fakeAnnouncements: Announcement[] = [
  {
    id: '123',
    type: 'info',
    level: 'normal',
    titleByLocale: {
      en: 'Some title',
    },
    markdownMessageByLocale: {
      en:
        'Something to announce which is really really cool [with a link](https://gdevelop.io) and *other* **markdown** ~~formatting~~!',
    },
  },
  {
    id: '124',
    type: 'info',
    level: 'urgent',
    titleByLocale: {
      en: 'Some title',
    },
    markdownMessageByLocale: {
      en:
        'Something nothing important but urgent to announce, with a button and [with a link](https://gdevelop.io) too.',
    },
    buttonLabelByLocale: { en: 'View' },
    buttonUrl: 'https://gdevelop.io',
  },
  {
    id: '125',
    type: 'warning',
    level: 'urgent',
    titleByLocale: {
      en: 'Some title',
    },
    markdownMessageByLocale: {
      en: 'Something important and urgent to announce.\n\n- With\n- a list',
    },
    buttonLabelByLocale: { en: 'View' },
    buttonUrl: 'https://gdevelop.io',
  },
  {
    id: '126',
    type: 'warning',
    level: 'normal',
    titleByLocale: {
      en: 'Some title',
    },
    markdownMessageByLocale: {
      en:
        'Something important but not urgent to announce, with a big image.\n\n![some image](https://raw.githubusercontent.com/4ian/GDevelop/master/newIDE/GDevelop%20banner.png)',
    },
    buttonLabelByLocale: { en: 'View' },
    buttonUrl: 'https://gdevelop.io',
  },
  {
    id: '127',
    level: 'normal',
    titleByLocale: {
      en: '',
    },
    markdownMessageByLocale: {
      en:
        '[![GDevelop Android](https://resources.gdevelop.io/announcements/GDevelop_Android.png)](https://play.google.com/store/apps/details?id=io.gdevelop.ide)',
    },
  },
];
