// @flow
// This file is generated by update-fixtures-from-resources-examples.js script

import exampleFile0 from '../../fixtures/admob/admob.json';
import exampleFile1 from '../../fixtures/advanced-shape-based-painter/advanced-shape-based-painter.json';
import exampleFile2 from '../../fixtures/animation-speed-scale/animation-speed-scale.json';
import exampleFile3 from '../../fixtures/asteroids/asteroids.json';
import exampleFile4 from '../../fixtures/basic-ai-with-pathfinding/basic-ai-with-pathfinding.json';
import exampleFile5 from '../../fixtures/basic-artificial-intelligence/basic-artificial-intelligence.json';
import exampleFile6 from '../../fixtures/basic-topdown-car-driving/basic-topdown-car-driving.json';
import exampleFile7 from '../../fixtures/bbtext-object-demo/bbtext-object-demo.json';
import exampleFile8 from '../../fixtures/betabox-basics-learning-experience/betabox-basics-learning-experience.json';
import exampleFile9 from '../../fixtures/bomb-the-crate/bomb-the-crate.json';
import exampleFile10 from '../../fixtures/bouncing-ball-and-rope/bouncing-ball-and-rope.json';
import exampleFile11 from '../../fixtures/breakout/breakout.json';
import exampleFile12 from '../../fixtures/buttons/buttons.json';
import exampleFile13 from '../../fixtures/car-physics/car-physics.json';
import exampleFile14 from '../../fixtures/center-object-within-another/center-object-within-another.json';
import exampleFile15 from '../../fixtures/change-position-of-object/change-position-of-object.json';
import exampleFile16 from '../../fixtures/change-scale-of-sprites/change-scale-of-sprites.json';
import exampleFile17 from '../../fixtures/change-sprite-animation/change-sprite-animation.json';
import exampleFile18 from '../../fixtures/change-sprite-color/change-sprite-color.json';
import exampleFile19 from '../../fixtures/character-selection/character-selection.json';
import exampleFile20 from '../../fixtures/count-down-timer/count-down-timer.json';
import exampleFile21 from '../../fixtures/create-object-with-mouseclick/create-object-with-mouseclick.json';
import exampleFile22 from '../../fixtures/create-random-object/create-random-object.json';
import exampleFile23 from '../../fixtures/custom-font/custom-font.json';
import exampleFile24 from '../../fixtures/custom-mouse-pointer/custom-mouse-pointer.json';
import exampleFile25 from '../../fixtures/customize-keys-with-lastpressedkey/customize-keys-with-lastpressedkey.json';
import exampleFile26 from '../../fixtures/device-orientation-ballgame/device-orientation-ballgame.json';
import exampleFile27 from '../../fixtures/device-orientation-compass/device-orientation-compass.json';
import exampleFile28 from '../../fixtures/device-vibration/device-vibration.json';
import exampleFile29 from '../../fixtures/dialogue-tree-with-yarn/dialogue-tree-with-yarn.json';
import exampleFile30 from '../../fixtures/downhill-bike-physics-demo/downhill-bike-physics-demo.json';
import exampleFile31 from '../../fixtures/drag-camera-with-mouse/drag-camera-with-mouse.json';
import exampleFile32 from '../../fixtures/drop-collect-items-from-storage/drop-collect-items-from-storage.json';
import exampleFile33 from '../../fixtures/endless-up-runner/endless-up-runner.json';
import exampleFile34 from '../../fixtures/exit-app/exit-app.json';
import exampleFile35 from '../../fixtures/facebook-instant-game/facebook-instant-game.json';
import exampleFile36 from '../../fixtures/filesystem-create-directory/filesystem-create-directory.json';
import exampleFile37 from '../../fixtures/find-diagonals/find-diagonals.json';
import exampleFile38 from '../../fixtures/geodash/geodash.json';
import exampleFile39 from '../../fixtures/geometry-monster/geometry-monster.json';
import exampleFile40 from '../../fixtures/health-bar/health-bar.json';
import exampleFile41 from '../../fixtures/infinite-scrolling-background/infinite-scrolling-background.json';
import exampleFile42 from '../../fixtures/inventory-system/inventory-system.json';
import exampleFile43 from '../../fixtures/isometric-game/isometric-game.json';
import exampleFile44 from '../../fixtures/javascript-blocks-in-platformer/javascript-blocks-in-platformer.json';
import exampleFile45 from '../../fixtures/keyboard-practice/keyboard-practice.json';
import exampleFile46 from '../../fixtures/level-editor/level-editor.json';
import exampleFile47 from '../../fixtures/level-selection-unlock/level-selection-unlock.json';
import exampleFile48 from '../../fixtures/load-image-from-url/load-image-from-url.json';
import exampleFile49 from '../../fixtures/magnet/magnet.json';
import exampleFile50 from '../../fixtures/manipulate-text-object/manipulate-text-object.json';
import exampleFile51 from '../../fixtures/menu-with-functions-and-text-effects/menu-with-functions-and-text-effects.json';
import exampleFile52 from '../../fixtures/move-camera-to-position/move-camera-to-position.json';
import exampleFile53 from '../../fixtures/move-object-back-and-forth/move-object-back-and-forth.json';
import exampleFile54 from '../../fixtures/move-object-in-circle/move-object-in-circle.json';
import exampleFile55 from '../../fixtures/move-object-toward-position/move-object-toward-position.json';
import exampleFile56 from '../../fixtures/move-object-with-mouse-joint/move-object-with-mouse-joint.json';
import exampleFile57 from '../../fixtures/move-object-with-physics/move-object-with-physics.json';
import exampleFile58 from '../../fixtures/multi-language-menu/multi-language-menu.json';
import exampleFile59 from '../../fixtures/multiplayer-platformer-with-gamepads/multiplayer-platformer-with-gamepads.json';
import exampleFile60 from '../../fixtures/multitouch/multitouch.json';
import exampleFile61 from '../../fixtures/object-gravity/object-gravity.json';
import exampleFile62 from '../../fixtures/object-selection/object-selection.json';
import exampleFile63 from '../../fixtures/objects-timers/objects-timers.json';
import exampleFile64 from '../../fixtures/open-url-in-browser/open-url-in-browser.json';
import exampleFile65 from '../../fixtures/pairs/pairs.json';
import exampleFile66 from '../../fixtures/parallax/parallax.json';
import exampleFile67 from '../../fixtures/parallax-scrolling/parallax-scrolling.json';
import exampleFile68 from '../../fixtures/parse-json-from-api/parse-json-from-api.json';
import exampleFile69 from '../../fixtures/parse-json-string/parse-json-string.json';
import exampleFile70 from '../../fixtures/particles-explosions/particles-explosions.json';
import exampleFile71 from '../../fixtures/particles-various-effects/particles-various-effects.json';
import exampleFile72 from '../../fixtures/pathfinding/pathfinding.json';
import exampleFile73 from '../../fixtures/pathfinding-basics/pathfinding-basics.json';
import exampleFile74 from '../../fixtures/physics/physics.json';
import exampleFile75 from '../../fixtures/physics-joints-demo/physics-joints-demo.json';
import exampleFile76 from '../../fixtures/physics-joints-settings-demo/physics-joints-settings-demo.json';
import exampleFile77 from '../../fixtures/pin-object-to-another/pin-object-to-another.json';
import exampleFile78 from '../../fixtures/pin-object-to-another-multiple-parents/pin-object-to-another-multiple-parents.json';
import exampleFile79 from '../../fixtures/pixel-perfect-platform-game/pixel-perfect-platform-game.json';
import exampleFile80 from '../../fixtures/plane-and-clouds/plane-and-clouds.json';
import exampleFile81 from '../../fixtures/platformer/platformer.json';
import exampleFile82 from '../../fixtures/platformer-double-jump/platformer-double-jump.json';
import exampleFile83 from '../../fixtures/play-music-on-mobile/play-music-on-mobile.json';
import exampleFile84 from '../../fixtures/play-stop-sprite-animation/play-stop-sprite-animation.json';
import exampleFile85 from '../../fixtures/racing-game/racing-game.json';
import exampleFile86 from '../../fixtures/ragdoll/ragdoll.json';
import exampleFile87 from '../../fixtures/rain/rain.json';
import exampleFile88 from '../../fixtures/random-color-picker/random-color-picker.json';
import exampleFile89 from '../../fixtures/rotate-toward-mouse/rotate-toward-mouse.json';
import exampleFile90 from '../../fixtures/rotate-toward-position/rotate-toward-position.json';
import exampleFile91 from '../../fixtures/rotate-with-keypress/rotate-with-keypress.json';
import exampleFile92 from '../../fixtures/save-load/save-load.json';
import exampleFile93 from '../../fixtures/screen-shake/screen-shake.json';
import exampleFile94 from '../../fixtures/shoot-bullet-in-parabola/shoot-bullet-in-parabola.json';
import exampleFile95 from '../../fixtures/shoot-bullets/shoot-bullets.json';
import exampleFile96 from '../../fixtures/shooting-bullets-explanation/shooting-bullets-explanation.json';
import exampleFile97 from '../../fixtures/simple-space-shooter/simple-space-shooter.json';
import exampleFile98 from '../../fixtures/snap-object-to-grid/snap-object-to-grid.json';
import exampleFile99 from '../../fixtures/space-invaders/space-invaders.json';
import exampleFile100 from '../../fixtures/space-shooter/space-shooter.json';
import exampleFile101 from '../../fixtures/splash-screen/splash-screen.json';
import exampleFile102 from '../../fixtures/sprite-fade-in-out/sprite-fade-in-out.json';
import exampleFile103 from '../../fixtures/take-screenshot/take-screenshot.json';
import exampleFile104 from '../../fixtures/text-entry-object/text-entry-object.json';
import exampleFile105 from '../../fixtures/text-fade-in-out/text-fade-in-out.json';
import exampleFile106 from '../../fixtures/text-to-speech/text-to-speech.json';
import exampleFile107 from '../../fixtures/toggle-music-play-sound/toggle-music-play-sound.json';
import exampleFile108 from '../../fixtures/type-on-text-effect/type-on-text-effect.json';
import exampleFile109 from '../../fixtures/unlock-items/unlock-items.json';
import exampleFile110 from '../../fixtures/video-player/video-player.json';
import exampleFile111 from '../../fixtures/z-depth/z-depth.json';
import exampleFile112 from '../../fixtures/zombie-laser/zombie-laser.json';

// prettier-ignore
export default {
  'example://admob': exampleFile0,
  'example://advanced-shape-based-painter': exampleFile1,
  'example://animation-speed-scale': exampleFile2,
  'example://asteroids': exampleFile3,
  'example://basic-ai-with-pathfinding': exampleFile4,
  'example://basic-artificial-intelligence': exampleFile5,
  'example://basic-topdown-car-driving': exampleFile6,
  'example://bbtext-object-demo': exampleFile7,
  'example://betabox-basics-learning-experience': exampleFile8,
  'example://bomb-the-crate': exampleFile9,
  'example://bouncing-ball-and-rope': exampleFile10,
  'example://breakout': exampleFile11,
  'example://buttons': exampleFile12,
  'example://car-physics': exampleFile13,
  'example://center-object-within-another': exampleFile14,
  'example://change-position-of-object': exampleFile15,
  'example://change-scale-of-sprites': exampleFile16,
  'example://change-sprite-animation': exampleFile17,
  'example://change-sprite-color': exampleFile18,
  'example://character-selection': exampleFile19,
  'example://count-down-timer': exampleFile20,
  'example://create-object-with-mouseclick': exampleFile21,
  'example://create-random-object': exampleFile22,
  'example://custom-font': exampleFile23,
  'example://custom-mouse-pointer': exampleFile24,
  'example://customize-keys-with-lastpressedkey': exampleFile25,
  'example://device-orientation-ballgame': exampleFile26,
  'example://device-orientation-compass': exampleFile27,
  'example://device-vibration': exampleFile28,
  'example://dialogue-tree-with-yarn': exampleFile29,
  'example://downhill-bike-physics-demo': exampleFile30,
  'example://drag-camera-with-mouse': exampleFile31,
  'example://drop-collect-items-from-storage': exampleFile32,
  'example://endless-up-runner': exampleFile33,
  'example://exit-app': exampleFile34,
  'example://facebook-instant-game': exampleFile35,
  'example://filesystem-create-directory': exampleFile36,
  'example://find-diagonals': exampleFile37,
  'example://geodash': exampleFile38,
  'example://geometry-monster': exampleFile39,
  'example://health-bar': exampleFile40,
  'example://infinite-scrolling-background': exampleFile41,
  'example://inventory-system': exampleFile42,
  'example://isometric-game': exampleFile43,
  'example://javascript-blocks-in-platformer': exampleFile44,
  'example://keyboard-practice': exampleFile45,
  'example://level-editor': exampleFile46,
  'example://level-selection-unlock': exampleFile47,
  'example://load-image-from-url': exampleFile48,
  'example://magnet': exampleFile49,
  'example://manipulate-text-object': exampleFile50,
  'example://menu-with-functions-and-text-effects': exampleFile51,
  'example://move-camera-to-position': exampleFile52,
  'example://move-object-back-and-forth': exampleFile53,
  'example://move-object-in-circle': exampleFile54,
  'example://move-object-toward-position': exampleFile55,
  'example://move-object-with-mouse-joint': exampleFile56,
  'example://move-object-with-physics': exampleFile57,
  'example://multi-language-menu': exampleFile58,
  'example://multiplayer-platformer-with-gamepads': exampleFile59,
  'example://multitouch': exampleFile60,
  'example://object-gravity': exampleFile61,
  'example://object-selection': exampleFile62,
  'example://objects-timers': exampleFile63,
  'example://open-url-in-browser': exampleFile64,
  'example://pairs': exampleFile65,
  'example://parallax': exampleFile66,
  'example://parallax-scrolling': exampleFile67,
  'example://parse-json-from-api': exampleFile68,
  'example://parse-json-string': exampleFile69,
  'example://particles-explosions': exampleFile70,
  'example://particles-various-effects': exampleFile71,
  'example://pathfinding': exampleFile72,
  'example://pathfinding-basics': exampleFile73,
  'example://physics': exampleFile74,
  'example://physics-joints-demo': exampleFile75,
  'example://physics-joints-settings-demo': exampleFile76,
  'example://pin-object-to-another': exampleFile77,
  'example://pin-object-to-another-multiple-parents': exampleFile78,
  'example://pixel-perfect-platform-game': exampleFile79,
  'example://plane-and-clouds': exampleFile80,
  'example://platformer': exampleFile81,
  'example://platformer-double-jump': exampleFile82,
  'example://play-music-on-mobile': exampleFile83,
  'example://play-stop-sprite-animation': exampleFile84,
  'example://racing-game': exampleFile85,
  'example://ragdoll': exampleFile86,
  'example://rain': exampleFile87,
  'example://random-color-picker': exampleFile88,
  'example://rotate-toward-mouse': exampleFile89,
  'example://rotate-toward-position': exampleFile90,
  'example://rotate-with-keypress': exampleFile91,
  'example://save-load': exampleFile92,
  'example://screen-shake': exampleFile93,
  'example://shoot-bullet-in-parabola': exampleFile94,
  'example://shoot-bullets': exampleFile95,
  'example://shooting-bullets-explanation': exampleFile96,
  'example://simple-space-shooter': exampleFile97,
  'example://snap-object-to-grid': exampleFile98,
  'example://space-invaders': exampleFile99,
  'example://space-shooter': exampleFile100,
  'example://splash-screen': exampleFile101,
  'example://sprite-fade-in-out': exampleFile102,
  'example://take-screenshot': exampleFile103,
  'example://text-entry-object': exampleFile104,
  'example://text-fade-in-out': exampleFile105,
  'example://text-to-speech': exampleFile106,
  'example://toggle-music-play-sound': exampleFile107,
  'example://type-on-text-effect': exampleFile108,
  'example://unlock-items': exampleFile109,
  'example://video-player': exampleFile110,
  'example://z-depth': exampleFile111,
  'example://zombie-laser': exampleFile112,
};
