// @flow
import panable, { type PanMoveEvent } from '../Utils/PixiSimpleGesture/pan';
import transformRect from '../Utils/TransformRect';
import * as PIXI from 'pixi.js-legacy';
import { type ScreenType } from '../UI/Responsive/ScreenTypeMeasurer';
import InstancesSelection from './InstancesSelection';
import {
  type ResizeGrabbingLocation,
  resizeGrabbingLocationValues,
  resizeGrabbingRelativePositions,
  canMoveOnX,
  canMoveOnY,
} from './InstancesResizer';
import { type InstanceMeasurer } from './InstancesRenderer';
import Rectangle from '../Utils/Rectangle';
import KeyboardShortcuts from '../UI/KeyboardShortcuts';
import {
  flipPolygon,
  rotatePolygon,
  type Polygon,
} from '../Utils/PolygonHelper';

type Props = {|
  instancesSelection: InstancesSelection,
  instanceMeasurer: InstanceMeasurer,
  shouldDisplayHandles: () => boolean,
  onResize: (
    deltaX: number,
    deltaY: number,
    grabbingLocation: ResizeGrabbingLocation
  ) => void,
  onResizeEnd: () => void,
  onRotate: (number, number) => void,
  onRotateEnd: () => void,
  toCanvasCoordinates: (x: number, y: number) => [number, number],
  screenType: ScreenType,
  keyboardShortcuts: KeyboardShortcuts,
  onPanMove: (deltaX: number, deltaY: number, x: number, y: number) => void,
  onPanEnd: () => void,
  getFillColor: (isLocked: boolean) => {| color: number, alpha: number |},
  instancesRotator: any,
  instancesResizer: any,
|};

const getButtonSizes = (screenType: ScreenType) => {
  if (screenType === 'touch') {
    return {
      bigButtonSize: 14,
      smallButtonSize: 12,
      buttonPadding: 5,
      hitAreaPadding: 12,
    };
  }

  return {
    bigButtonSize: 10,
    smallButtonSize: 8,
    buttonPadding: 5,
    hitAreaPadding: 5,
  };
};

const RECTANGLE_BUTTON_SHAPE = 0;
const CIRCLE_BUTTON_SHAPE = 1;

const resizeGrabbingIconNames = {
  TopLeft: 'nwse-resize',
  BottomLeft: 'nesw-resize',
  BottomRight: 'nwse-resize',
  TopRight: 'nesw-resize',
  Top: 'ns-resize',
  Left: 'ew-resize',
  Bottom: 'ns-resize',
  Right: 'ew-resize',
};

// Calculate the appropriate cursor for a resize direction based on rotation angle
const getRotatedCursor = (
  grabbingLocation: ResizeGrabbingLocation,
  angleDegrees: number
): string => {
  // For corner handles, calculate the actual direction after rotation
  const cornerDirections = {
    TopLeft: -135, // northwest
    TopRight: -45, // northeast
    BottomRight: 45, // southeast
    BottomLeft: 135, // southwest
  };

  if (cornerDirections[grabbingLocation] !== undefined) {
    // Calculate actual angle of the handle direction
    const handleAngle = (cornerDirections[grabbingLocation] + angleDegrees) % 360;
    // Normalize to -180 to 180
    const normalized = handleAngle > 180 ? handleAngle - 360 : handleAngle;

    // Map to closest cursor (4 directions)
    if (normalized >= -22.5 && normalized < 22.5) {
      return 'ew-resize'; // horizontal
    } else if (normalized >= 22.5 && normalized < 67.5) {
      return 'nwse-resize'; // diagonal \
    } else if (normalized >= 67.5 && normalized < 112.5) {
      return 'ns-resize'; // vertical
    } else if (normalized >= 112.5 && normalized < 157.5) {
      return 'nesw-resize'; // diagonal /
    } else if (normalized >= 157.5 || normalized < -157.5) {
      return 'ew-resize'; // horizontal
    } else if (normalized >= -157.5 && normalized < -112.5) {
      return 'nesw-resize'; // diagonal /
    } else if (normalized >= -112.5 && normalized < -67.5) {
      return 'ns-resize'; // vertical
    } else {
      return 'nwse-resize'; // diagonal \
    }
  }

  // For non-corner handles, return default
  return resizeGrabbingIconNames[grabbingLocation] || 'default';
};

/**
 * Render selection rectangle for selected instances.
 */
export default class SelectedInstances {
  instancesSelection: InstancesSelection;
  instanceMeasurer: InstanceMeasurer;
  shouldDisplayHandles: () => boolean;
  onResize: (
    deltaX: number,
    deltaY: number,
    grabbingLocation: ResizeGrabbingLocation
  ) => void;
  onResizeEnd: () => void;
  onRotate: (number, number) => void;
  onRotateEnd: () => void;
  toCanvasCoordinates: (x: number, y: number) => [number, number];
  _screenType: ScreenType;
  keyboardShortcuts: KeyboardShortcuts;
  onPanMove: (deltaX: number, deltaY: number, x: number, y: number) => void;
  onPanEnd: () => void;
  getFillColor: (isLocked: boolean) => {| color: number, alpha: number |};

  pixiContainer = new PIXI.Container();
  rectanglesContainer = new PIXI.Container();
  selectedRectangles = [];
  resizeButtons: { [ResizeGrabbingLocation]: PIXI.Graphics } = {};
  rotateButton = new PIXI.Graphics();
  /**
   * When moving the view, a click on the buttons generated by this class
   * won't trigger a resize and interrupt the move of the view.
   * Similarly, when resizing an instance, if we start to move the view
   * (space key pressed), the resizing is interrupted to move the view.
   * This state is used to detect the change and call the "end" function
   * associated of the proper interaction (buttonInteraction or viewMoving).
   */
  _currentPanMovingGoal: null | 'buttonInteraction' | 'viewMoving' = null;
  /**
   * The scene position of the rotate button, used to initialize rotation correctly
   * when the selection is already rotated.
   */
  _rotateButtonScenePosition: [number, number] | null = null;
  /**
   * Track whether rotation has started to set initial button position only once
   */
  _rotationStarted: boolean = false;
  /**
   * Track whether resize has started to set initial grabbing position only once
   */
  _resizeStarted: boolean = false;
  /**
   * Store the scene positions of resize handles for rotated instances
   * Format: [sceneX, sceneY, aabbGrabbingLocation]
   */
  _resizeHandleScenePositions: { [ResizeGrabbingLocation]: Array<any> } = {};
  /**
   * Store the current effective grabbing location (AABB-relative) for the active resize
   */
  _currentResizeGrabbingLocation: ResizeGrabbingLocation | null = null;
  /**
   * Store the cursor styles for each resize button (for rotated instances)
   */
  _resizeButtonCursors: { [ResizeGrabbingLocation]: string } = {};

  instancesRotator: any;
  instancesResizer: any;

  constructor({
    instancesSelection,
    instanceMeasurer,
    shouldDisplayHandles,
    onResize,
    onResizeEnd,
    onRotate,
    onRotateEnd,
    toCanvasCoordinates,
    screenType,
    keyboardShortcuts,
    onPanMove,
    onPanEnd,
    getFillColor,
    instancesRotator,
    instancesResizer,
  }: Props) {
    this.instanceMeasurer = instanceMeasurer;
    this.onResize = onResize;
    this.shouldDisplayHandles = shouldDisplayHandles;
    this.onResizeEnd = onResizeEnd;
    this.onRotate = onRotate;
    this.onRotateEnd = onRotateEnd;
    this.toCanvasCoordinates = toCanvasCoordinates;
    this.instancesSelection = instancesSelection;
    this._screenType = screenType;
    this.keyboardShortcuts = keyboardShortcuts;
    this.onPanMove = onPanMove;
    this.onPanEnd = onPanEnd;
    this.getFillColor = getFillColor;
    this.instancesRotator = instancesRotator;
    this.instancesResizer = instancesResizer;

    this.pixiContainer.addChild(this.rectanglesContainer);

    for (const resizeGrabbingLocation of resizeGrabbingLocationValues) {
      const resizeButton = new PIXI.Graphics();
      // Store the grabbing location on the button so we can look up the cursor later
      resizeButton._grabbingLocation = resizeGrabbingLocation;
      this.resizeButtons[resizeGrabbingLocation] = resizeButton;
      this._makeButton({
        objectButton: resizeButton,
        onMove: event => {
          // On the first resize movement, set the initial grabbing position and effective location
          if (!this._resizeStarted && this._resizeHandleScenePositions[resizeGrabbingLocation] && this.instancesResizer) {
            this._resizeStarted = true;
            const handleData = this._resizeHandleScenePositions[resizeGrabbingLocation];
            this.instancesResizer.setInitialGrabbingPosition(handleData[0], handleData[1]);
            // Use the AABB-relative location if available (for rotated instances)
            if (handleData.length > 2 && handleData[2]) {
              this._currentResizeGrabbingLocation = handleData[2];
            } else {
              this._currentResizeGrabbingLocation = resizeGrabbingLocation;
            }
          }
          // Use the stored effective location for all resize calls
          const effectiveLocation = this._currentResizeGrabbingLocation || resizeGrabbingLocation;
          this.onResize(event.deltaX, event.deltaY, effectiveLocation);
        },
        onEnd: () => {
          this._resizeStarted = false;
          this._currentResizeGrabbingLocation = null;
          this.onResizeEnd();
        },
        onPanMove: event => {
          this.onPanMove(
            event.deltaX,
            event.deltaY,
            event.data.global.x,
            event.data.global.y
          );
        },
        onPanEnd: () => {
          this.onPanEnd();
        },
        cursor: resizeGrabbingIconNames[resizeGrabbingLocation],
        getCursorForButton: (button) => {
          // Look up the dynamically calculated cursor for rotated instances
          const location = button._grabbingLocation;
          return this._resizeButtonCursors[location] || resizeGrabbingIconNames[location];
        },
      });
    }
    this._makeButton({
      objectButton: this.rotateButton,
      onMove: event => {
        // On the first rotation movement, set the initial button position
        if (!this._rotationStarted && this._rotateButtonScenePosition && this.instancesRotator) {
          this._rotationStarted = true;
          this.instancesRotator.setInitialButtonPosition(
            this._rotateButtonScenePosition[0],
            this._rotateButtonScenePosition[1]
          );
        }
        this.onRotate(event.deltaX, event.deltaY);
      },
      onEnd: () => {
        this._rotationStarted = false;
        this.onRotateEnd();
      },
      onPanMove: event => {
        this.onPanMove(
          event.deltaX,
          event.deltaY,
          event.data.global.x,
          event.data.global.y
        );
      },
      onPanEnd: () => {
        this.onPanEnd();
      },
      cursor: 'url("res/actions/rotate24_black.png"),auto',
    });
  }

  setScreenType(screenType: ScreenType) {
    this._screenType = screenType;
  }

  _makeButton({
    objectButton,
    onMove,
    onEnd,
    onPanMove,
    onPanEnd,
    cursor,
    getCursorForButton,
  }: {
    objectButton: PIXI.Graphics,
    onMove: (event: PanMoveEvent) => void,
    onEnd: () => void,
    onPanMove: (event: PanMoveEvent) => void,
    onPanEnd: () => void,
    cursor: string,
    getCursorForButton?: (button: PIXI.Graphics) => string,
  }) {
    objectButton.eventMode = 'static';
    objectButton.buttonMode = true;
    objectButton.cursor = cursor;
    panable(objectButton);

    // change cursor style if space is pressed
    objectButton.addEventListener('mousemove', event => {
      if (this.keyboardShortcuts.shouldMoveView()) {
        objectButton.cursor = 'grab';
      } else {
        // Use dynamic cursor if available, otherwise use the static one
        objectButton.cursor = getCursorForButton ? getCursorForButton(objectButton) : cursor;
      }
    });

    objectButton.addEventListener('panmove', event => {
      if (this.keyboardShortcuts.shouldMoveView()) {
        if (this._currentPanMovingGoal === 'buttonInteraction') {
          onEnd();
        }
        onPanMove(event);
        this._currentPanMovingGoal = 'viewMoving';
      } else {
        onMove(event);
        this._currentPanMovingGoal = 'buttonInteraction';
      }
    });

    objectButton.addEventListener('panend', event => {
      if (this.keyboardShortcuts.shouldMoveView()) {
        onPanEnd();
      } else {
        onEnd();
      }
      this._currentPanMovingGoal = null;
    });
    this.pixiContainer.addChild(objectButton);
  }

  getPixiContainer() {
    return this.pixiContainer;
  }

  _renderButton(
    show: boolean,
    buttonObject: PIXI.Graphics,
    canvasPosition: [number, number],
    size: number,
    shape: 0 | 1,
    hitAreaPadding: number
  ) {
    buttonObject.clear();
    if (!show) {
      buttonObject.hitArea = new PIXI.Rectangle(0, 0, 0, 0);
      return;
    }

    buttonObject.beginFill(0xffffff);
    buttonObject.lineStyle(1, 0x6868e8, 1);
    buttonObject.fill.alpha = 0.9;
    if (shape === RECTANGLE_BUTTON_SHAPE) {
      buttonObject.drawRect(canvasPosition[0], canvasPosition[1], size, size);
    } else if (shape === CIRCLE_BUTTON_SHAPE) {
      buttonObject.drawCircle(
        canvasPosition[0] + size / 2,
        canvasPosition[1] + size / 2,
        size / 2
      );
    }

    buttonObject.endFill();
    buttonObject.hitArea = new PIXI.Rectangle(
      canvasPosition[0] - hitAreaPadding,
      canvasPosition[1] - hitAreaPadding,
      size + hitAreaPadding * 2,
      size + hitAreaPadding * 2
    );
  }

  getSelectionAABB = (): Rectangle => {
    const selectionAABB = new Rectangle();
    const selection = this.instancesSelection.getSelectedInstances();
    let instanceRect = new Rectangle();
    for (var i = 0; i < selection.length; i++) {
      const instance = selection[i];

      instanceRect = this.instanceMeasurer.getInstanceAABB(
        instance,
        instanceRect
      );
      if (i === 0) {
        selectionAABB.setRectangle(instanceRect);
      } else {
        selectionAABB.union(instanceRect);
      }
    }
    return selectionAABB;
  };

  render() {
    const {
      bigButtonSize,
      smallButtonSize,
      buttonPadding,
      hitAreaPadding,
    } = getButtonSizes(this._screenType);
    const displayHandle = this.shouldDisplayHandles();
    const selection = this.instancesSelection.getSelectedInstances();
    let x1 = 0;
    let y1 = 0;
    let x2 = 0;
    let y2 = 0;
    let initialised = false;

    // Track if we have a single rotated/flipped instance for special handle positioning
    let singleRotatedInstanceCorners: Polygon | null = null;
    let singleInstanceAngleDegrees: number = 0;
    const isSingleInstance = selection.length === 1;
    if (isSingleInstance) {
      const instance = selection[0];
      const angle = (instance.getAngle() * Math.PI) / 180;
      const isFlippedX = instance.isFlippedX();
      const isFlippedY = instance.isFlippedY();
      if (angle !== 0 || isFlippedX || isFlippedY) {
        // We'll compute this later when we process the instance
        singleRotatedInstanceCorners = [[0, 0], [0, 0], [0, 0], [0, 0]];
        singleInstanceAngleDegrees = instance.getAngle();
      }
    }

    // Map corner visual position to AABB-relative grabbing location
    // based on rotation. This is needed because the resizer logic uses
    // isLeft/isTop which are based on AABB positions, not visual positions.
    const getAABBGrabbingLocation = (visualLocation: ResizeGrabbingLocation, angleDegrees: number): ResizeGrabbingLocation => {
      // Normalize angle to 0-360
      const normalizedAngle = ((angleDegrees % 360) + 360) % 360;

      // For angles close to 0, 90, 180, 270, snap to those values
      let snappedAngle = normalizedAngle;
      if (Math.abs(normalizedAngle - 0) < 5 || Math.abs(normalizedAngle - 360) < 5) snappedAngle = 0;
      else if (Math.abs(normalizedAngle - 90) < 5) snappedAngle = 90;
      else if (Math.abs(normalizedAngle - 180) < 5) snappedAngle = 180;
      else if (Math.abs(normalizedAngle - 270) < 5) snappedAngle = 270;

      // Map based on rotation quadrant
      if (snappedAngle >= 45 && snappedAngle < 135) {
        // Rotated ~90 degrees: top-left -> top-right, top-right -> bottom-right, etc.
        const mapping = {
          'TopLeft': 'TopRight',
          'TopRight': 'BottomRight',
          'BottomRight': 'BottomLeft',
          'BottomLeft': 'TopLeft',
        };
        return mapping[visualLocation] || visualLocation;
      } else if (snappedAngle >= 135 && snappedAngle < 225) {
        // Rotated ~180 degrees: top-left -> bottom-right, bottom-right -> top-left, etc.
        const mapping = {
          'TopLeft': 'BottomRight',
          'TopRight': 'BottomLeft',
          'BottomRight': 'TopLeft',
          'BottomLeft': 'TopRight',
        };
        return mapping[visualLocation] || visualLocation;
      } else if (snappedAngle >= 225 && snappedAngle < 315) {
        // Rotated ~270 degrees: top-left -> bottom-left, bottom-left -> bottom-right, etc.
        const mapping = {
          'TopLeft': 'BottomLeft',
          'TopRight': 'TopLeft',
          'BottomRight': 'TopRight',
          'BottomLeft': 'BottomRight',
        };
        return mapping[visualLocation] || visualLocation;
      }

      // For angles close to 0 or 360, no remapping needed
      return visualLocation;
    };

    // Update the selection rectangle of each instance.
    for (var i = 0; i < selection.length; i++) {
      if (this.selectedRectangles.length === i) {
        const newRectangle = new PIXI.Graphics();
        newRectangle.hitArea = new PIXI.Rectangle(0, 0, 0, 0);
        this.selectedRectangles.push(newRectangle);
        this.rectanglesContainer.addChild(newRectangle);
      }

      const instance = selection[i];
      const angle = (instance.getAngle() * Math.PI) / 180;
      const isFlippedX = instance.isFlippedX();
      const isFlippedY = instance.isFlippedY();
      const isRotatedOrFlipped = angle !== 0 || isFlippedX || isFlippedY;

      // Get the bounding box (rotated AABB for bounds calculation)
      const instanceRect = this.instanceMeasurer.getInstanceAABB(
        instance,
        new Rectangle()
      );

      this.selectedRectangles[i].clear();
      const { color, alpha } = this.getFillColor(instance.isLocked());
      this.selectedRectangles[i].beginFill(color, alpha);
      this.selectedRectangles[i].lineStyle(1, color, 1);
      this.selectedRectangles[i].fill.alpha = 0.3;
      this.selectedRectangles[i].alpha = 0.8;

      if (isRotatedOrFlipped) {
        // For rotated/flipped instances, draw a polygon that matches the rotation
        const unrotatedRect = this.instanceMeasurer.getUnrotatedInstanceAABB(
          instance,
          new Rectangle()
        );
        const unrotatedLeft = unrotatedRect.left;
        const unrotatedTop = unrotatedRect.top;
        const unrotatedRight = unrotatedLeft + unrotatedRect.width();
        const unrotatedBottom = unrotatedTop + unrotatedRect.height();

        // Create polygon corners in scene coordinates
        const corners: Polygon = [
          [unrotatedLeft, unrotatedTop],
          [unrotatedLeft, unrotatedBottom],
          [unrotatedRight, unrotatedBottom],
          [unrotatedRight, unrotatedTop],
        ];

        // Get the center point for rotation using the rendered instance
        let centerX;
        let centerY;
        const renderedInstance = this.instanceMeasurer.getRendererOfInstance(
          instance
        );
        if (renderedInstance) {
          centerX = unrotatedLeft + renderedInstance.getCenterX();
          centerY = unrotatedTop + renderedInstance.getCenterY();
        } else {
          // Fallback to geometric center if no renderer available
          centerX = (unrotatedLeft + unrotatedRight) / 2;
          centerY = (unrotatedTop + unrotatedBottom) / 2;
        }

        // Apply flip and rotation transformations
        flipPolygon(corners, centerX, centerY, isFlippedX, isFlippedY);
        rotatePolygon(corners, centerX, centerY, angle);

        // Store corners for single instance handle positioning
        if (singleRotatedInstanceCorners) {
          for (let j = 0; j < 4; j++) {
            singleRotatedInstanceCorners[j][0] = corners[j][0];
            singleRotatedInstanceCorners[j][1] = corners[j][1];
          }
        }

        // Convert to canvas coordinates and flatten for drawPolygon
        const canvasPoints = [];
        for (let j = 0; j < corners.length; j++) {
          const canvasCoords = this.toCanvasCoordinates(
            corners[j][0],
            corners[j][1]
          );
          canvasPoints.push(canvasCoords[0], canvasCoords[1]);
        }

        this.selectedRectangles[i].drawPolygon(canvasPoints);
      } else {
        // For non-rotated instances, use the simple rectangle (more efficient)
        const selectionRectangle = transformRect(
          this.toCanvasCoordinates,
          instanceRect
        );
        this.selectedRectangles[i].drawRect(
          selectionRectangle.left,
          selectionRectangle.top,
          selectionRectangle.width(),
          selectionRectangle.height()
        );
      }

      this.selectedRectangles[i].endFill();

      if (instance.isLocked()) {
        continue;
      }
      if (!initialised) {
        x1 = instanceRect.left;
        y1 = instanceRect.top;
        x2 = instanceRect.left + instanceRect.width();
        y2 = instanceRect.top + instanceRect.height();
        initialised = true;
      } else {
        if (instanceRect.left < x1) x1 = instanceRect.left;
        if (instanceRect.top < y1) y1 = instanceRect.top;
        if (instanceRect.left + instanceRect.width() > x2)
          x2 = instanceRect.left + instanceRect.width();
        if (instanceRect.top + instanceRect.height() > y2)
          y2 = instanceRect.top + instanceRect.height();
      }
    }

    while (this.selectedRectangles.length > selection.length) {
      this.rectanglesContainer.removeChild(this.selectedRectangles.pop());
    }

    // If there are no unlocked instances, hide the resize buttons.
    const show =
      selection.filter(instance => !instance.isLocked()).length !== 0 &&
      displayHandle;

    // Position the resize buttons.
    if (singleRotatedInstanceCorners) {
      // For a single rotated instance, position buttons on the rotated corners
      // Map corner indices to grabbing locations:
      // corners[0] = top-left, corners[1] = bottom-left,
      // corners[2] = bottom-right, corners[3] = top-right
      const cornerToGrabLocation = {
        0: 'TopLeft',
        1: 'BottomLeft',
        2: 'BottomRight',
        3: 'TopRight',
      };

      // Calculate the center of the rotated rectangle
      const centerX = (singleRotatedInstanceCorners[0][0] +
                       singleRotatedInstanceCorners[1][0] +
                       singleRotatedInstanceCorners[2][0] +
                       singleRotatedInstanceCorners[3][0]) / 4;
      const centerY = (singleRotatedInstanceCorners[0][1] +
                       singleRotatedInstanceCorners[1][1] +
                       singleRotatedInstanceCorners[2][1] +
                       singleRotatedInstanceCorners[3][1]) / 4;

      // Position corner buttons on the rotated corners
      for (let cornerIdx = 0; cornerIdx < 4; cornerIdx++) {
        const visualGrabbingLocation = cornerToGrabLocation[cornerIdx];
        const resizeButton = this.resizeButtons[visualGrabbingLocation];
        const corner = singleRotatedInstanceCorners[cornerIdx];

        // Map visual location to AABB-relative location for the resizer
        const aabbGrabbingLocation = getAABBGrabbingLocation(visualGrabbingLocation, singleInstanceAngleDegrees);

        // Store the corner position in scene coordinates with the AABB-relative location
        this._resizeHandleScenePositions[visualGrabbingLocation] = [corner[0], corner[1], aabbGrabbingLocation];

        // Calculate and store the appropriate cursor for this rotated handle
        this._resizeButtonCursors[visualGrabbingLocation] = getRotatedCursor(visualGrabbingLocation, singleInstanceAngleDegrees);

        const buttonSize = bigButtonSize;
        const padding = buttonPadding + buttonSize / 2;

        // Convert corner to canvas coordinates first
        const canvasCorner = this.toCanvasCoordinates(corner[0], corner[1]);

        // Calculate direction from center to corner (in canvas coordinates)
        const canvasCenter = this.toCanvasCoordinates(centerX, centerY);
        const dirX = canvasCorner[0] - canvasCenter[0];
        const dirY = canvasCorner[1] - canvasCenter[1];
        const dirLength = Math.sqrt(dirX * dirX + dirY * dirY);
        const normalizedDirX = dirX / dirLength;
        const normalizedDirY = dirY / dirLength;

        // Apply offset in canvas space (same as non-rotated case)
        const canvasCoords = [
          canvasCorner[0] - buttonSize / 2 + normalizedDirX * padding,
          canvasCorner[1] - buttonSize / 2 + normalizedDirY * padding
        ];

        this._renderButton(
          show,
          resizeButton,
          canvasCoords,
          buttonSize,
          RECTANGLE_BUTTON_SHAPE,
          hitAreaPadding
        );
      }

      // Hide edge buttons for rotated instances (only show corner buttons)
      for (const grabbingLocation of ['Top', 'Bottom', 'Left', 'Right']) {
        const resizeButton = this.resizeButtons[grabbingLocation];
        this._renderButton(
          false,
          resizeButton,
          [0, 0],
          smallButtonSize,
          RECTANGLE_BUTTON_SHAPE,
          hitAreaPadding
        );
      }

      // Position rotate button at the top-center of the rotated rectangle
      const topCenterX =
        (singleRotatedInstanceCorners[0][0] +
          singleRotatedInstanceCorners[3][0]) /
        2;
      const topCenterY =
        (singleRotatedInstanceCorners[0][1] +
          singleRotatedInstanceCorners[3][1]) /
        2;

      // Calculate the normal vector pointing outward from the top edge (in scene coordinates)
      // Top edge goes from corner[0] (top-left) to corner[3] (top-right)
      const topEdgeVector = [
        singleRotatedInstanceCorners[3][0] - singleRotatedInstanceCorners[0][0],
        singleRotatedInstanceCorners[3][1] - singleRotatedInstanceCorners[0][1],
      ];
      const topEdgeLength = Math.sqrt(
        topEdgeVector[0] ** 2 + topEdgeVector[1] ** 2
      );
      // Normal vector perpendicular to the top edge (pointing upward/outward)
      // For a counter-clockwise wound polygon, the outward normal is (dy, -dx)
      const normalVector = [
        topEdgeVector[1] / topEdgeLength,
        -topEdgeVector[0] / topEdgeLength,
      ];

      // Apply offset in scene coordinates
      const offset = buttonPadding * 8;
      const rotateButtonSceneX = topCenterX + normalVector[0] * offset;
      const rotateButtonSceneY = topCenterY + normalVector[1] * offset;

      // Store the scene position for rotation initialization
      this._rotateButtonScenePosition = [rotateButtonSceneX, rotateButtonSceneY];

      // Convert to canvas coordinates
      const rotateButtonPos = this.toCanvasCoordinates(
        rotateButtonSceneX,
        rotateButtonSceneY
      );
      rotateButtonPos[0] -= smallButtonSize / 2;
      rotateButtonPos[1] -= smallButtonSize / 2;

      this._renderButton(
        show,
        this.rotateButton,
        rotateButtonPos,
        smallButtonSize,
        CIRCLE_BUTTON_SHAPE,
        hitAreaPadding
      );
    } else {
      // For multiple instances or non-rotated, use AABB positioning
      // Clear stored handle positions and cursors so the resizer uses calculated positions
      this._resizeHandleScenePositions = {};
      this._resizeButtonCursors = {};

      for (const grabbingLocation of resizeGrabbingLocationValues) {
        const resizeButton = this.resizeButtons[grabbingLocation];
        const relativePositions =
          resizeGrabbingRelativePositions[grabbingLocation];

        const useBigButton =
          canMoveOnX(grabbingLocation) && canMoveOnY(grabbingLocation);
        const buttonSize = useBigButton ? bigButtonSize : smallButtonSize;
        const padding = buttonPadding + buttonSize / 2;
        const resizeButtonPos = this.toCanvasCoordinates(
          x1 + relativePositions[0] * (x2 - x1),
          y1 + relativePositions[1] * (y2 - y1)
        );
        resizeButtonPos[0] +=
          -buttonSize / 2 + padding * Math.sign(relativePositions[0] - 0.5);
        resizeButtonPos[1] +=
          -buttonSize / 2 + padding * Math.sign(relativePositions[1] - 0.5);

        this._renderButton(
          show,
          resizeButton,
          resizeButtonPos,
          buttonSize,
          RECTANGLE_BUTTON_SHAPE,
          hitAreaPadding
        );
      }

      const rotateButtonSceneX = x1 + (x2 - x1) / 2;
      const rotateButtonSceneY = y1;

      // Store the scene position for rotation initialization
      this._rotateButtonScenePosition = [rotateButtonSceneX, rotateButtonSceneY];

      const rotateButtonPos = this.toCanvasCoordinates(rotateButtonSceneX, rotateButtonSceneY);
      rotateButtonPos[0] -= smallButtonSize / 2;
      rotateButtonPos[1] -= buttonPadding * 8;

      this._renderButton(
        show,
        this.rotateButton,
        rotateButtonPos,
        smallButtonSize,
        CIRCLE_BUTTON_SHAPE,
        hitAreaPadding
      );
    }
  }
}
