#ifdef PYSUPPORT
// This file has been generated by Py++.

#ifndef sf_classes_3_hpp__pyplusplus_wrapper
#define sf_classes_3_hpp__pyplusplus_wrapper

void register_classes_3();

#endif//sf_classes_3_hpp__pyplusplus_wrapper
#endif
