// This file has been generated by Py++.
#ifdef PYSUPPORT
#ifndef sf_classes_2_hpp__pyplusplus_wrapper
#define sf_classes_2_hpp__pyplusplus_wrapper

void register_classes_2();

#endif//sf_classes_2_hpp__pyplusplus_wrapper
#endif
