// This file is generated by update-examples-extensions-usage-from-resources-examples.js script
// prettier-ignore
module.exports = {
  "admob": {
    "description": "Demonstrate how to show ads from AdMob in your game: banners, interstitial screen or reward videos. Also useful to test that your AdMob account is working properly.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "AdMob",
        "name": "AdMob"
      }
    ]
  },
  "advanced-shape-based-painter": {
    "description": "Show how to use Shape Painter objects to create a simple drawing app.",
    "usedExtensions": [
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "animation-speed-scale": {
    "description": "Change the speed of the animation of an object according to its movement speed.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      }
    ]
  },
  "asteroids": {
    "description": "An adptation of the classic arcade game Asteroids with GDevelop.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "basic-ai-with-pathfinding": {
    "description": "Show how to use pathfinding to make enemies chase the player.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Pathfinding behavior",
        "name": "PathfindingBehavior"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Linked objects",
        "name": "LinkedObjects"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      }
    ]
  },
  "basic-artificial-intelligence": {
    "description": "Show how to create enemies looking at the player and chasing him when spotted.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Linked objects",
        "name": "LinkedObjects"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      }
    ]
  },
  "basic-topdown-car-driving": {
    "description": "Show how to create a car that can be controlled by the player.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "betabox-basics-learning-experience": {
    "description": "Example level for teaching basic programming skills with extra features and assets.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Panel Sprite (9-patch) Object",
        "name": "PanelSpriteObject"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Particle system",
        "name": "ParticleSystem"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Anchor",
        "name": "AnchorBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "bomb-the-crate": {
    "description": "A basic bomberman like game, where the player can move on the map, drop bombs and destroy crates on the map.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "bouncing-ball-and-rope": {
    "description": "Simulate a bouncing ball with ropes that can be created to move the ball around anchors.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "Panel Sprite (9-patch) Object",
        "name": "PanelSpriteObject"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Advanced control features",
        "name": "BuiltinAdvanced"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Linked objects",
        "name": "LinkedObjects"
      }
    ]
  },
  "breakout": {
    "description": "The classic Breakout arcade game adapted in GDevelop.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "External layouts",
        "name": "BuiltinExternalLayouts"
      }
    ]
  },
  "buttons": {
    "description": "Learn how to make buttons for the menus in your game.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      }
    ]
  },
  "car-physics": {
    "description": "A fun, physics based driving game",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "center-object-within-another": {
    "description": "How to put an object on the center of another",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "change-position-of-object": {
    "description": "Show how to move an object by changing its X and Y position.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "change-scale-of-sprites": {
    "description": "Show how to change the scale of a sprite (to make a zoom effect for example).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "change-sprite-animation": {
    "description": "Learn how to change the animation of a Sprite object (useful for animating almost all objects in your game: characters, enemies, items...)",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "change-sprite-color": {
    "description": "Learn how to change the color of a Sprite object - useful to achieve effects like invincibility with a blue tint or taking damage with a red effect. ",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "character-selection": {
    "description": "Example showing how to remember the character selected by the player and use it in other scenes.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Anchor",
        "name": "AnchorBehavior"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "controller-input": {
    "description": "Use JavaScript to read the state of a gamepad and use it in your game.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Anchor",
        "name": "AnchorBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "create-object-with-mouseclick": {
    "description": "Show how to create an object at the position of the click.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "custom-font": {
    "description": "Example showing a text with a custom font applied on it.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      }
    ]
  },
  "custom-mouse-pointer": {
    "description": "Learn how to replace the mouse cursor by a custom image.\n",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "customize-keys-with-lastpressedkey": {
    "description": "This explains how to remember the last key that was pressed and customize the inputs of your game.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "device-orientation-ballgame": {
    "description": "Example showing how to use the device sensors to move a ball in a maze.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Device sensors",
        "name": "DeviceSensors"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "device-orientation-compass": {
    "description": "This shows how to use the device sensors to create a compass like app.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Device sensors",
        "name": "DeviceSensors"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "device-vibration": {
    "description": "Show how to make the device vibrate.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Device vibration",
        "name": "DeviceVibration"
      }
    ]
  },
  "downhill-bike-physics-demo": {
    "description": "A fun demo, using the Physics Engine to build an advanced simulation of a bike, with a person pedaling on it. Try to cross the finish line without falling and as fast as possible!",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Panel Sprite (9-patch) Object",
        "name": "PanelSpriteObject"
      },
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Advanced control features",
        "name": "BuiltinAdvanced"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Window features",
        "name": "BuiltinWindow"
      },
      {
        "fullName": "Device vibration",
        "name": "DeviceVibration"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      }
    ]
  },
  "drag-camera-with-mouse": {
    "description": "This shows how to allow the user to move on a map with the mouse.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "drop-collect-items-from-storage": {
    "description": "Show how to make the player collect objects from boxes on the map.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "endless-up-runner": {
    "description": "A game where the player have to jump on platforms and avoid falling down as the screen goes up. With special objects (spring, rocks), score and Game Over handling!",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      }
    ]
  },
  "exit-app": {
    "description": "Simple example showing how to close your game.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      }
    ]
  },
  "facebook-instant-game": {
    "description": "Learn how to use the various Facebook Instant Games APIs to get information about the player, share their scores and have a leaderboard!",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Facebook Instant Games",
        "name": "FacebookInstantGames"
      }
    ]
  },
  "find-diagonals": {
    "description": "Show how to delete objects that are located at the diagonals of the click of the player in a board game.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "geodash": {
    "description": "A fast paced game where you must jump and avoid obstacles.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Panel Sprite (9-patch) Object",
        "name": "PanelSpriteObject"
      },
      {
        "fullName": "Particle system",
        "name": "ParticleSystem"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      }
    ]
  },
  "health-bar": {
    "description": "The platform example game adapted to add a health bar to the player, that is decreased when the player touches an enemy.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Anchor",
        "name": "AnchorBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "infinite-scrolling-background": {
    "description": "Learn how to create a background that is scolling infinitely.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "inventory-system": {
    "description": "Learn how to display an inventory, with object that can be addded or removed, and how to persist it in storage.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Inventory",
        "name": "Inventory"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Linked objects",
        "name": "LinkedObjects"
      },
      {
        "fullName": "Storage",
        "name": "BuiltinFile"
      }
    ]
  },
  "isometric-game": {
    "description": "Example of making an isometric 2D game.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Top-down movement",
        "name": "TopDownMovementBehavior"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "javascript-blocks-in-platformer": {
    "description": "This shows how to reproduce the Platformer example using JavaScript code instead of events.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Anchor",
        "name": "AnchorBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "keyboard-practice": {
    "description": "A simple game where the player must press the right keys on the keyboard as fast as possible.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "level-editor": {
    "description": "Example showing a basic level editor, where you can save and load positions of objects put on the scene during the game. Also shows how to use simple functions.\n",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Storage",
        "name": "BuiltinFile"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "",
        "name": ""
      }
    ]
  },
  "load-image-from-url": {
    "description": "Advanced example showing how to use JavaScript to load an image from an external URL.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "magnet": {
    "description": "Show how to move a ball like if it's attracted by a magnet.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Linked objects",
        "name": "LinkedObjects"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "manipulate-text-object": {
    "description": "This shows how to change the text of a Text object displayed on the screen.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "move-camera-to-position": {
    "description": "This shows how to move the camera to the position of an object on a map.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "move-object-back-and-forth": {
    "description": "Use events to move objects back and forth vertically or horizontally.\n",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      }
    ]
  },
  "move-object-in-circle": {
    "description": "This shows how to make an object move in circle around some point.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "move-object-toward-position": {
    "description": "This shows how to have an object move to a given position on the screen.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "move-object-with-mouse-joint": {
    "description": "Show how to use physics engine to move an object around with the mouse and realistic movements.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "move-object-with-physics": {
    "description": "This shows how to use the forces built in GDevelop to move an object.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "multitouch": {
    "description": "This show how to create multiple markers when the player touches the screen.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "object-gravity": {
    "description": "Use the physics engine to simulate an object moving on a small planet.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      }
    ]
  },
  "object-selection": {
    "description": "Simple example showing how the engine of GDevelop select objects to be used in conditions and actions.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "objects-timers": {
    "description": "Example showing various usage of objects timers (timers that are stored into instances of objects on the scene, as opposed to scene timers which are stored by the scene).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      }
    ]
  },
  "open-url-in-browser": {
    "description": "This shows how to open a website on the system default browser.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Storage",
        "name": "BuiltinFile"
      }
    ]
  },
  "parallax": {
    "description": "Shows how to have multiple layers with a parallax effect (where the background layers move slower than the foreground).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "parallax-scrolling": {
    "description": "Another example showing how to have multiple layers with a parallax effect (where the background layers move slower than the foreground).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "parse-json-from-api": {
    "description": "Advanced example where JSON content is fetched from a website and information extracted from it.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Basic internet features",
        "name": "BuiltinNetwork"
      }
    ]
  },
  "parse-json-string": {
    "description": "Advanced example showing how to extract information from a JSON formatted string.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Basic internet features",
        "name": "BuiltinNetwork"
      }
    ]
  },
  "particles-explosions": {
    "description": "Create explosion effects with the particles engine.",
    "usedExtensions": [
      {
        "fullName": "Particle system",
        "name": "ParticleSystem"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "particles-various-effects": {
    "description": "Create various effects with the particles engine.",
    "usedExtensions": [
      {
        "fullName": "Particle system",
        "name": "ParticleSystem"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "pathfinding": {
    "description": "This show how to have an object moving from its position to another automatically avoiding obstacles.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Pathfinding behavior",
        "name": "PathfindingBehavior"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "pathfinding-basics": {
    "description": "Simpler example showing how to get started with Pathfinding, to have an object automatically find its way around obstacles.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Pathfinding behavior",
        "name": "PathfindingBehavior"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "physics": {
    "description": "Example showing various capabilities of the physics engine integrated to GDevelop.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "physics-joints-demo": {
    "description": "A demo of all the joints that can be created using the Physics engine.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "physics-joints-settings-demo": {
    "description": "A demo of all the joints, and the way they can be customized, using the Physics engine.",
    "usedExtensions": [
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "",
        "name": ""
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "pin-object-to-another": {
    "description": "Example showing how to have objects \"pinned\" to another, meaning that they will move/rotate and follow the object they are pinned too.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "pin-object-to-another-multiple-parents": {
    "description": "Example showing how to have objects \"pinned\" to multiple other objects, meaning that they will move/rotate and follow the object they are pinned too.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Linked objects",
        "name": "LinkedObjects"
      }
    ]
  },
  "pixel-perfect-platform-game": {
    "description": "Very simple example showing the settings to have a pixel-perfect platform game (also applicable to other kind of games).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      }
    ]
  },
  "plane-and-clouds": {
    "description": "Show how to randomly generate clouds to create an infinite sky.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Particle system",
        "name": "ParticleSystem"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  },
  "platformer": {
    "description": "An example of a basic platformer (Mario-like) game made with GDevelop.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Anchor",
        "name": "AnchorBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "platformer-double-jump": {
    "description": "The Platformer example modified to allow the player to do a double jump.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Anchor",
        "name": "AnchorBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "play-music-on-mobile": {
    "description": "This show how to properly launch a music on a game on mobile.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "play-stop-sprite-animation": {
    "description": "This shows how to pause the animation of a Sprite object.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "racing-game": {
    "description": "A top-down racing game made using the Physics engine.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "ragdoll": {
    "description": "Example of creating a ragdoll with physics joints.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Particle system",
        "name": "ParticleSystem"
      },
      {
        "fullName": "Physics Engine 2.0",
        "name": "Physics2"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Advanced control features",
        "name": "BuiltinAdvanced"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "rain": {
    "description": "Show how to simulate a rain effect by creating several objects.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Window features",
        "name": "BuiltinWindow"
      }
    ]
  },
  "random-color-picker": {
    "description": "This shows how to create a grid with random color, and let the player choose one.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "rotate-toward-mouse": {
    "description": "Show how to rotate an object so that it looks toward the player cursor.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "rotate-toward-position": {
    "description": "Show how to rotate an object so that it looks toward a specified position on the scene.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "rotate-with-keypress": {
    "description": "Basic example showing how to rotate an object.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "save-load": {
    "description": "Advanced example showing how to persist data and then reload them from storage (useful to store game progress, or save the state of some objects in a game).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Storage",
        "name": "BuiltinFile"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "screen-shake": {
    "description": "Make the screen shake when some event occurs.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Platform Behavior",
        "name": "PlatformBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "shoot-bullet-in-parabola": {
    "description": "Show how to use various mathematical expressions to move an object following a parabola shape",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      }
    ]
  },
  "shoot-bullets": {
    "description": "Basic example showing how to shoot bullets from an object.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "shooting-bullets-explanation": {
    "description": "Basic example showing how to shoot bullets from one or multiple objects at the same time.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "snap-object-to-grid": {
    "description": "Example showing how to create a grid and have objects snapped to the grid.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Draggable Behavior",
        "name": "DraggableBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Window features",
        "name": "BuiltinWindow"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "space-invaders": {
    "description": "A Space Invaders-like game, where you have a turret and shoot on enemies coming from the sky.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "System information",
        "name": "SystemInfo"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Window features",
        "name": "BuiltinWindow"
      }
    ]
  },
  "space-shooter": {
    "description": "A space shooter game (Shoot 'em up) made with GDevelop.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Top-down movement",
        "name": "TopDownMovementBehavior"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "space-shooter-with-functions": {
    "description": "The space shooter example with some events rewritten to be reusable functions (custom conditions/actions or expressions).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Tiled Sprite Object",
        "name": "TiledSpriteObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Top-down movement",
        "name": "TopDownMovementBehavior"
      },
      {
        "fullName": "Destroy Outside Screen Behavior",
        "name": "DestroyOutsideBehavior"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "",
        "name": ""
      }
    ]
  },
  "splash-screen": {
    "description": "Show how to create a splashscreen at the beginning of your game.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "sprite-fade-in-out": {
    "description": "This shows how to make a sprite fade in and out on the screen.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "take-screenshot": {
    "description": "Show how to save a screenshot of the game on the disk (on Windows/macOS/Linux only).",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Screenshot",
        "name": "Screenshot"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "text-entry-object": {
    "description": "This shows how to use the Text Entry object to capture what is written on the keyboard.",
    "usedExtensions": [
      {
        "fullName": "Text entry object",
        "name": "TextEntryObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      }
    ]
  },
  "text-fade-in-out": {
    "description": "This shows how to make a text fade in and out on the screen.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "text-to-speech": {
    "description": "Advanced example showing how to use JavaScript and HTML5 api to make a text read by your computer.",
    "usedExtensions": [
      {
        "fullName": "Text entry object",
        "name": "TextEntryObject"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      }
    ]
  },
  "toggle-music-play-sound": {
    "description": "Example showing how to play a music and add controls on the screen to pause it, change the volume or mute the sounds totally.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "type-on-text-effect": {
    "description": "This show how to create an effect where a text is progressively typed on the screen.",
    "usedExtensions": [
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Audio",
        "name": "BuiltinAudio"
      }
    ]
  },
  "z-depth": {
    "description": "Example where the player can move a character on a map, and the character is displayed behind or in front of other objects according to its position.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Standard events",
        "name": "BuiltinCommonInstructions"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Keyboard features",
        "name": "BuiltinKeyboard"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      }
    ]
  },
  "zombie-laser": {
    "description": "Simple game where the player must use his laser powered gun to destroy zombies running at him.",
    "usedExtensions": [
      {
        "fullName": "Sprite",
        "name": "Sprite"
      },
      {
        "fullName": "Primitive drawing",
        "name": "PrimitiveDrawing"
      },
      {
        "fullName": "Text object",
        "name": "TextObject"
      },
      {
        "fullName": "Pathfinding behavior",
        "name": "PathfindingBehavior"
      },
      {
        "fullName": "Scene management features",
        "name": "BuiltinScene"
      },
      {
        "fullName": "Variable features",
        "name": "BuiltinVariables"
      },
      {
        "fullName": "Mouse features",
        "name": "BuiltinMouse"
      },
      {
        "fullName": "Base object",
        "name": "BuiltinObject"
      },
      {
        "fullName": "Time",
        "name": "BuiltinTime"
      },
      {
        "fullName": "Cameras and layers features",
        "name": "BuiltinCamera"
      }
    ]
  }
};
