// Automatically generated by GDevelop.js/scripts/generate-types.js
// Automatically generated by GDevelop.js/scripts/generate-types.js
// Automatically generated by GDevelop.js/scripts/generate-types.js
// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdResourcesMergingHelper {
  constructor(fs: gdAbstractFileSystem): void;
  setBaseDirectory(basePath: string): void;
  getAllResourcesOldAndNewFilename(): gdMapStringString;
  delete(): void;
  ptr: number;
};