name: "🐛Bug report"
description: "Create a bug report about GDevelop or the game engine"
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        Please double check that the bug is not already reported in the issues list.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        * Please include a link to a game if possible!
        * If applicable, add screenshots to help explain your problem.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: dropdown
    attributes:
      label: GDevelop version
      description: Which version of GDevelop are you used?
      multiple: true
      options:
        - Desktop app
        - Web app
    validations:
      required: true
  - type: textarea
    attributes:
      label: Info
      value: |
        OS: 
        OS Version: 
        Browser(For Web app): 
        Device(For Smartphone): 
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
