name: 🐛Bug report
description: Create a bug report about GDevelop or the game engine
title: "[Bug]: "
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        Please double check that the bug is not already reported in the issues list.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        * Please include a link to a game if possible!
        * If applicable, add screenshots to help explain your problem.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other details
      description: |
        * Include any OS/browser version/smartphone that you're using
        * Which version of GDevelop are you using? The desktop app or the web-app?
        * Add any other context about the problem here.
      value: |
        OS:
        Browser version:
        GDevelop app type(desktop app or the web-app):
        GDevelop version:

