
post_install() {
	update-mime-database usr/share/mime
	update-desktop-database
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
	update-mime-database usr/share/mime
	update-desktop-database
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_remove() {
	update-mime-database usr/share/mime
	update-desktop-database
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
