// flow-typed signature: 20bcb1828794c8d0c2baa5d7faf45473
// flow-typed version: <<STUB>>/element-closest_v2.0.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'element-closest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'element-closest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'element-closest/element-closest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'element-closest/element-closest.js' {
  declare module.exports: $Exports<'element-closest/element-closest'>;
}
