// flow-typed signature: cd4eb447a86dcad9a7e4d10bb68d5a2c
// flow-typed version: <<STUB>>/unzip2_v^0.2.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unzip2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unzip2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unzip2/lib/entry' {
  declare module.exports: any;
}

declare module 'unzip2/lib/extract' {
  declare module.exports: any;
}

declare module 'unzip2/lib/parse' {
  declare module.exports: any;
}

declare module 'unzip2/test/compressed' {
  declare module.exports: any;
}

declare module 'unzip2/test/fileSizeUnknownFlag' {
  declare module.exports: any;
}

declare module 'unzip2/test/pipeSingleEntry' {
  declare module.exports: any;
}

declare module 'unzip2/test/uncompressed' {
  declare module.exports: any;
}

declare module 'unzip2/unzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unzip2/lib/entry.js' {
  declare module.exports: $Exports<'unzip2/lib/entry'>;
}
declare module 'unzip2/lib/extract.js' {
  declare module.exports: $Exports<'unzip2/lib/extract'>;
}
declare module 'unzip2/lib/parse.js' {
  declare module.exports: $Exports<'unzip2/lib/parse'>;
}
declare module 'unzip2/test/compressed.js' {
  declare module.exports: $Exports<'unzip2/test/compressed'>;
}
declare module 'unzip2/test/fileSizeUnknownFlag.js' {
  declare module.exports: $Exports<'unzip2/test/fileSizeUnknownFlag'>;
}
declare module 'unzip2/test/pipeSingleEntry.js' {
  declare module.exports: $Exports<'unzip2/test/pipeSingleEntry'>;
}
declare module 'unzip2/test/uncompressed.js' {
  declare module.exports: $Exports<'unzip2/test/uncompressed'>;
}
declare module 'unzip2/unzip.js' {
  declare module.exports: $Exports<'unzip2/unzip'>;
}
