// flow-typed signature: 9cd6a538a32b5355bc6e67de1893b05c
// flow-typed version: <<STUB>>/url-search-params_v^1.0.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-search-params'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-search-params' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url-search-params/build/url-search-params.amd' {
  declare module.exports: any;
}

declare module 'url-search-params/build/url-search-params' {
  declare module.exports: any;
}

declare module 'url-search-params/build/url-search-params.max.amd' {
  declare module.exports: any;
}

declare module 'url-search-params/build/url-search-params.max' {
  declare module.exports: any;
}

declare module 'url-search-params/build/url-search-params.node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url-search-params/build/url-search-params.amd.js' {
  declare module.exports: $Exports<'url-search-params/build/url-search-params.amd'>;
}
declare module 'url-search-params/build/url-search-params.js' {
  declare module.exports: $Exports<'url-search-params/build/url-search-params'>;
}
declare module 'url-search-params/build/url-search-params.max.amd.js' {
  declare module.exports: $Exports<'url-search-params/build/url-search-params.max.amd'>;
}
declare module 'url-search-params/build/url-search-params.max.js' {
  declare module.exports: $Exports<'url-search-params/build/url-search-params.max'>;
}
declare module 'url-search-params/build/url-search-params.node.js' {
  declare module.exports: $Exports<'url-search-params/build/url-search-params.node'>;
}
