// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdBehaviorParameterFiller {
  static fillBehaviorParameters(platform: gdPlatform, projectScopedContainers: gdProjectScopedContainers, instructionMetadata: gdInstructionMetadata, instruction: gdInstruction): void;
  delete(): void;
  ptr: number;
};