// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdBehavior {
  constructor(): void;
  setName(name: string): void;
  getName(): string;
  getTypeName(): string;
  getProperties(): gdMapStringPropertyDescriptor;
  updateProperty(name: string, value: string): boolean;
  removeProperty(name: string): void;
  initializeContent(): void;
  hasPropertyValue(name: string): boolean;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(element: gdSerializerElement): void;
  isFolded(): boolean;
  setFolded(folded: boolean): void;
  isDefaultBehavior(): boolean;
  getPropertiesQuickCustomizationVisibilities(): gdQuickCustomizationVisibilitiesContainer;
  delete(): void;
  ptr: number;
};