// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdBehaviorsSharedData {
  constructor(): void;
  getProperties(behaviorSharedDataContent: gdSerializerElement): gdMapStringPropertyDescriptor;
  updateProperty(behaviorSharedDataContent: gdSerializerElement, name: string, value: string): boolean;
  initializeContent(behaviorSharedDataContent: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};