// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdBehaviorContent {
  constructor(name: string, type: string): void;
  clone(): gdBehaviorContent;
  setName(name: string): void;
  getName(): string;
  getTypeName(): string;
  getContent(): gdSerializerElement;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(element: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};