// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdCaptureOptions {
  addScreenshot(screenshot: gdScreenshot): void;
  clearScreenshots(): void;
  getScreenshots(): gdVectorScreenshot;
  delete(): void;
  ptr: number;
};