// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdDiagnosticReport {
  constructor(): void;
  get(index: number): gdProjectDiagnostic;
  count(): number;
  getSceneName(): string;
  delete(): void;
  ptr: number;
};