// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEditorSettings {
  constructor(): void;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(element: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};