// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEffect {
  constructor(): void;
  setName(name_: string): void;
  getName(): string;
  setEffectType(effectType_: string): void;
  getEffectType(): string;
  setDoubleParameter(name: string, value: number): void;
  getDoubleParameter(name: string): number;
  setStringParameter(name: string, value: string): void;
  getStringParameter(name: string): string;
  setBooleanParameter(name: string, value: boolean): void;
  getBooleanParameter(name: string): boolean;
  getAllDoubleParameters(): gdMapStringDouble;
  getAllStringParameters(): gdMapStringString;
  getAllBooleanParameters(): gdMapStringBoolean;
  clearParameters(): void;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(element: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};