// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEffectMetadata {
  setFullName(fullName: string): gdEffectMetadata;
  setDescription(description: string): gdEffectMetadata;
  setHelpPath(helpPath: string): gdEffectMetadata;
  setIncludeFile(includeFile: string): gdEffectMetadata;
  addIncludeFile(includeFile: string): gdEffectMetadata;
  getType(): string;
  getFullName(): string;
  getDescription(): string;
  getHelpPath(): string;
  getProperties(): gdMapStringPropertyDescriptor;
  delete(): void;
  ptr: number;
};