// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEventsLeaderboardsRenamer {
  constructor(project: gdProject, leaderboardIdMap: gdMapStringString): void;
  launch(events: gdEventsList): void;
  delete(): void;
  ptr: number;
};