// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEventsBasedObjectsList {
  insertNew(name: string, pos: number): gdEventsBasedObject;
  insert(item: gdEventsBasedObject, pos: number): gdEventsBasedObject;
  has(name: string): boolean;
  get(name: string): gdEventsBasedObject;
  getAt(pos: number): gdEventsBasedObject;
  remove(name: string): void;
  move(oldIndex: number, newIndex: number): void;
  getCount(): number;
  getPosition(item: gdEventsBasedObject): number;
  size(): number;
  at(index: number): gdEventsBasedObject;
  delete(): void;
  ptr: number;
};