// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEventMetadata {
  getFullName(): string;
  getDescription(): string;
  getGroup(): string;
  delete(): void;
  ptr: number;
};