// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEventsVariablesFinder {
  constructor(): void;
  static findAllGlobalVariables(platform: gdPlatform, project: gdProject): gdSetString;
  static findAllLayoutVariables(platform: gdPlatform, project: gdProject, layout: gdLayout): gdSetString;
  static findAllObjectVariables(platform: gdPlatform, project: gdProject, layout: gdLayout, obj: gdObject): gdSetString;
  delete(): void;
  ptr: number;
};