// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEventsBasedObjectVariantHelper {
  static complyVariantsToEventsBasedObject(project: gdProject, eventsBasedObject: gdEventsBasedObject): void;
  static findAllChildrenCustomObjectType(project: gdProject, eventsBasedObject: gdEventsBasedObject): gdVectorString;
  delete(): void;
  ptr: number;
};