// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdEventsFunctionTools {
  static eventsFunctionToObjectsContainer(project: gdProject, eventsFunction: gdEventsFunction, outputGlobalObjectsContainer: gdObjectsContainer, outputObjectsContainer: gdObjectsContainer): void;
  delete(): void;
  ptr: number;
};