// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExternalLayoutFolderOrExternalLayout {
  constructor(): void;
  isFolder(): boolean;
  isRootFolder(): boolean;
  getItem(): gdExternalLayout;
  getFolderName(): string;
  setFolderName(name: string): void;
  hasItemNamed(name: string): boolean;
  getItemNamed(name: string): gdExternalLayoutFolderOrExternalLayout;
  getChildrenCount(): number;
  getChildAt(pos: number): gdExternalLayoutFolderOrExternalLayout;
  getItemChild(name: string): gdExternalLayoutFolderOrExternalLayout;
  getChildPosition(child: gdExternalLayoutFolderOrExternalLayout): number;
  getParent(): gdExternalLayoutFolderOrExternalLayout;
  insertNewFolder(name: string, newPosition: number): gdExternalLayoutFolderOrExternalLayout;
  moveFolderOrItemToAnotherFolder(folderOrItem: gdExternalLayoutFolderOrExternalLayout, newParentFolder: gdExternalLayoutFolderOrExternalLayout, newPosition: number): void;
  moveChild(oldIndex: number, newIndex: number): void;
  removeFolderChild(childToRemove: gdExternalLayoutFolderOrExternalLayout): void;
  isADescendantOf(otherFolderOrItem: gdExternalLayoutFolderOrExternalLayout): boolean;
  delete(): void;
  ptr: number;
};