// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExpressionSyntaxColoringHelper {
  static getColorationDescriptionsFor(platform: gdPlatform, projectScopedContainers: gdProjectScopedContainers, rootType: string, node: gdExpressionNode): gdVectorExpressionColorationDescription;
  getColorationDescriptions(): gdVectorExpressionColorationDescription;
  delete(): void;
  ptr: number;
};