// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExpressionCompletionFinder {
  static getCompletionDescriptionsFor(platform: gdPlatform, globalObjectsContainer: gdObjectsContainer, objectsContainer: gdObjectsContainer, rootType: string, node: gdExpressionNode, location: number, ignoreNodeType: boolean): gdVectorExpressionCompletionDescription;
  getCompletionDescriptions(): gdVectorExpressionCompletionDescription;
  delete(): void;
  ptr: number;
};