// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExpressionCompletionDescription {
  static Object: 0;
  static BehaviorWithPrefix: 1;
  static ExpressionWithPrefix: 2;
  static Variable: 3;
  static TextWithPrefix: 4;
  static Property: 5;
  static Parameter: 6;
  getCompletionKind(): ExpressionCompletionDescription_CompletionKind;
  getType(): string;
  getVariableType(): Variable_Type;
  getPrefix(): string;
  getCompletion(): string;
  getObjectName(): string;
  getBehaviorName(): string;
  isExact(): boolean;
  isLastParameter(): boolean;
  getReplacementStartPosition(): number;
  getReplacementEndPosition(): number;
  getParameterMetadata(): gdParameterMetadata;
  hasObjectConfiguration(): boolean;
  getObjectConfiguration(): gdObjectConfiguration;
  toString(): string;
  delete(): void;
  ptr: number;
};