// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExpressionNodeLocationFinder {
  static getNodeAtPosition(node: gdExpressionNode, searchedPosition: number): gdExpressionNode;
  delete(): void;
  ptr: number;
};