// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExpressionCodeGenerationInformation {
  setFunctionName(functionName: string): gdExpressionCodeGenerationInformation;
  setStatic(): gdExpressionCodeGenerationInformation;
  setIncludeFile(includeFile: string): gdExpressionCodeGenerationInformation;
  addIncludeFile(includeFile: string): gdExpressionCodeGenerationInformation;
  getIncludeFiles(): gdVectorString;
  delete(): void;
  ptr: number;
};