// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExpressionTypeFinder {
  static getType(platform: gdPlatform, projectScopedContainers: gdProjectScopedContainers, rootType: string, node: gdExpressionNode): string;
  delete(): void;
  ptr: number;
};