// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdjsExporter {
  constructor(fs: gdAbstractFileSystem, gdjsRoot: string): void;
  setCodeOutputDirectory(path: string): void;
  exportProjectForPixiPreview(options: gdPreviewExportOptions): boolean;
  exportWholePixiProject(options: gdExportOptions): boolean;
  getLastError(): string;
  delete(): void;
  ptr: number;
};