// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExampleExtensionUsagesFinder {
  static getUsedExtensions(project: gdProject): gdSetString;
  delete(): void;
  ptr: number;
};