// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExtensionAndEffectMetadata {
  getExtension(): gdPlatformExtension;
  getMetadata(): gdEffectMetadata;
  delete(): void;
  ptr: number;
};