// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExtensionAndInstructionMetadata {
  getExtension(): gdPlatformExtension;
  getMetadata(): gdInstructionMetadata;
  delete(): void;
  ptr: number;
};