// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdExpressionValidator extends gdExpressionParser2NodeWorker {
  constructor(platform: gdPlatform, projectScopedContainers: gdProjectScopedContainers, rootType: string): void;
  getAllErrors(): gdVectorExpressionParserDiagnostic;
  getFatalErrors(): gdVectorExpressionParserDiagnostic;
  delete(): void;
  ptr: number;
};