// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdForEachEvent extends gdBaseEvent {
  constructor(): void;
  setObjectToPick(objects: string): void;
  getObjectToPick(): string;
  getConditions(): gdInstructionsList;
  getActions(): gdInstructionsList;
  getLoopIndexVariableName(): string;
  setLoopIndexVariableName(name: string): void;
  getOrderBy(): string;
  setOrderBy(orderBy: string): void;
  getOrder(): string;
  setOrder(order: string): void;
  getLimit(): string;
  setLimit(limit: string): void;
  delete(): void;
  ptr: number;
};