// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdForEachChildVariableEvent {
  constructor(): void;
  getConditions(): gdInstructionsList;
  getActions(): gdInstructionsList;
  getIterableVariableName(): string;
  getKeyIteratorVariableName(): string;
  getValueIteratorVariableName(): string;
  setIterableVariableName(newName: string): void;
  setKeyIteratorVariableName(newName: string): void;
  setValueIteratorVariableName(newName: string): void;
  clone(): gdForEachChildVariableEvent;
  getType(): string;
  setType(type: string): void;
  isExecutable(): boolean;
  canHaveSubEvents(): boolean;
  hasSubEvents(): boolean;
  getSubEvents(): gdEventsList;
  isDisabled(): boolean;
  setDisabled(disable: boolean): void;
  isFolded(): boolean;
  setFolded(folded: boolean): void;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(project: gdProject, element: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};