// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdGroupVariableHelper {
  static mergeVariableContainers(objectsContainersList: gdObjectsContainersList, objectGroup: gdObjectGroup): gdVariablesContainer;
  delete(): void;
  ptr: number;
};