// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdInstructionOrExpressionGroupMetadata {
  constructor(): void;
  setIcon(icon: string): gdInstructionOrExpressionGroupMetadata;
  getIcon(): string;
  delete(): void;
  ptr: number;
};