// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdInitialInstancesContainer {
  constructor(): void;
  clone(): gdInitialInstancesContainer;
  getInstancesCount(): number;
  iterateOverInstances(func: gdInitialInstanceFunctor): void;
  iterateOverInstancesWithZOrdering(func: gdInitialInstanceFunctor, layer: string): void;
  moveInstancesToLayer(fromLayer: string, toLayer: string): void;
  removeAllInstancesOnLayer(layer: string): void;
  removeInitialInstancesOfObject(obj: string): void;
  hasInstancesOfObject(objectName: string): boolean;
  someInstancesAreOnLayer(layer: string): boolean;
  renameInstancesOfObject(oldName: string, newName: string): void;
  removeInstance(inst: gdInitialInstance): void;
  getLayerInstancesCount(layerName: string): number;
  insertNewInitialInstance(): gdInitialInstance;
  insertInitialInstance(inst: gdInitialInstance): gdInitialInstance;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(element: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};