// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdInstructionSentenceFormatter {
  static get(): gdInstructionSentenceFormatter;
  translate(instr: gdInstruction, metadat: gdInstructionMetadata): string;
  getAsFormattedText(instr: gdInstruction, metadat: gdInstructionMetadata): gdVectorPairStringTextFormatting;
  getFormattingFromType(type: string): gdTextFormatting;
  labelFromType(type: string): string;
  loadTypesFormattingFromConfig(): void;
  delete(): void;
  ptr: number;
};