// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdLayoutCodeGenerator {
  constructor(project: gdProject): void;
  generateLayoutCompleteCode(layout: gdLayout, includes: gdSetString, diagnosticReport: gdDiagnosticReport, compilationForRuntime: boolean, generateBreakpointInstrumentation: boolean): string;
  delete(): void;
  ptr: number;
};