// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdMapStringEventMetadata {
  get(name: string): gdEventMetadata;
  set(name: string, prop: gdEventMetadata): void;
  has(name: string): boolean;
  keys(): gdVectorString;
  delete(): void;
  ptr: number;
};