// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdMapExtensionProperties {
  get(name: string): gdMapStringPropertyDescriptor;
  set(name: string, prop: gdMapStringPropertyDescriptor): void;
  has(name: string): boolean;
  keys(): gdVectorString;
  delete(): void;
  ptr: number;
};