// Automatically generated by GDevelop.js/scripts/generate-types.js
// Automatically generated by GDevelop.js/scripts/generate-types.js
// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdMapStringVectorString {
  constructor(): void;
  get(name: string): gdVectorString;
  has(name: string): boolean;
  keys(): gdVectorString;
  delete(): void;
  ptr: number;
};