// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdMapStringBoolean {
  constructor(): void;
  get(name: string): boolean;
  set(name: string, value: boolean): void;
  has(name: string): boolean;
  keys(): gdVectorString;
  delete(): void;
  ptr: number;
};