// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdMapStringSerializerValue {
  constructor(): void;
  getOrCreate(name: string): gdSerializerValue;
  get(name: string): gdSerializerValue;
  set(name: string, prop: gdSerializerValue): void;
  has(name: string): boolean;
  keys(): gdVectorString;
  delete(): void;
  ptr: number;
};