// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdMetadataDeclarationHelper {
  constructor(): void;
  static declareExtension(extension: gdPlatformExtension, eventsFunctionsExtension: gdEventsFunctionsExtension): void;
  generateFreeFunctionMetadata(project: gdProject, extension: gdPlatformExtension, eventsFunctionsExtension: gdEventsFunctionsExtension, eventsFunction: gdEventsFunction): gdAbstractFunctionMetadata;
  static generateBehaviorMetadata(project: gdProject, extension: gdPlatformExtension, eventsFunctionsExtension: gdEventsFunctionsExtension, eventsBasedBehavior: gdEventsBasedBehavior, behaviorMethodMangledNames: gdMapStringString): gdBehaviorMetadata;
  static generateObjectMetadata(project: gdProject, extension: gdPlatformExtension, eventsFunctionsExtension: gdEventsFunctionsExtension, eventsBasedObject: gdEventsBasedObject, objectMethodMangledNames: gdMapStringString): gdObjectMetadata;
  static getExtensionCodeNamespacePrefix(eventsFunctionsExtension: gdEventsFunctionsExtension): string;
  static getFreeFunctionCodeName(eventsFunctionsExtension: gdEventsFunctionsExtension, eventsFunction: gdEventsFunction): string;
  static getFreeFunctionCodeNamespace(eventsFunction: gdEventsFunction, codeNamespacePrefix: string): string;
  static getBehaviorFunctionCodeNamespace(eventsBasedBehavior: gdEventsBasedBehavior, codeNamespacePrefix: string): string;
  static getObjectFunctionCodeNamespace(eventsBasedObject: gdEventsBasedObject, codeNamespacePrefix: string): string;
  static isBehaviorLifecycleEventsFunction(functionName: string): boolean;
  static isObjectLifecycleEventsFunction(functionName: string): boolean;
  static isExtensionLifecycleEventsFunction(functionName: string): boolean;
  static shiftSentenceParamIndexes(sentence: string, offset: number): string;
  delete(): void;
  ptr: number;
};