// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdModel3DAnimation {
  constructor(): void;
  setName(name: string): void;
  getName(): string;
  setSource(name: string): void;
  getSource(): string;
  delete(): void;
  ptr: number;
};