// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdObjectAssetSerializer {
  static serializeTo(project: gdProject, obj: gdObject, objectFullName: string, element: gdSerializerElement, usedResourceNames: gdVectorString, ExtensionDependencyCache: gdExtensionDependencyCache): void;
  delete(): void;
  ptr: number;
};