// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdObjectsContainersList {
  static makeNewObjectsContainersListForProjectAndLayout(project: gdProject, layout: gdLayout): gdObjectsContainersList;
  static makeNewObjectsContainersListForContainers(globalObjectsContainer: gdObjectsContainer, objectsContainer: gdObjectsContainer): gdObjectsContainersList;
  delete(): void;
  ptr: number;
};