// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdObjectsContainer {
  constructor(): void;
  insertNewObject(project: gdProject, type: string, name: string, pos: number): gdObject;
  insertObject(obj: gdObject, pos: number): gdObject;
  hasObjectNamed(name: string): boolean;
  getObject(name: string): gdObject;
  getObjectAt(pos: number): gdObject;
  getObjectPosition(name: string): number;
  removeObject(name: string): void;
  swapObjects(first: number, second: number): void;
  moveObject(oldIndex: number, newIndex: number): void;
  moveObjectToAnotherContainer(name: string, newObjectsContainer: gdObjectsContainer, newPosition: number): void;
  getObjectsCount(): number;
  getRootFolder(): gdObjectFolderOrObject;
  getObjectGroups(): gdObjectGroupsContainer;
  delete(): void;
  ptr: number;
};