// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdObject {
  constructor(name: string, type: string, configuration: gdObjectConfiguration): void;
  clone(): gdUniquePtrObject;
  setName(name: string): void;
  getName(): string;
  setAssetStoreId(assetStoreId: string): void;
  getAssetStoreId(): string;
  setType(type: string): void;
  getType(): string;
  getConfiguration(): gdObjectConfiguration;
  getVariables(): gdVariablesContainer;
  getEffects(): gdEffectsContainer;
  getAllBehaviorNames(): gdVectorString;
  hasBehaviorNamed(name: string): boolean;
  addNewBehavior(project: gdProject, type: string, name: string): gdBehavior;
  getBehavior(name: string): gdBehavior;
  removeBehavior(name: string): void;
  renameBehavior(oldName: string, name: string): boolean;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(project: gdProject, element: gdSerializerElement): void;
  resetPersistentUuid(): gdObject;
  clearPersistentUuid(): gdObject;
  delete(): void;
  ptr: number;
};