// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdParameterValidationResult {
  isValid(): boolean;
  hasDeprecationWarning(): boolean;
  delete(): void;
  ptr: number;
};