// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdPolygon2d {
  constructor(): void;
  getVertices(): gdVectorVector2f;
  move(x: number, y: number): void;
  rotate(angle: number): void;
  isConvex(): boolean;
  computeCenter(): gdVector2f;
  static createRectangle(width: number, height: number): gdPolygon2d;
  delete(): void;
  ptr: number;
};