// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdProjectResourcesCopier {
  static copyAllResourcesTo(project: gdProject, fs: gdAbstractFileSystem, destinationDirectory: string, updateOriginalProject: boolean, preserveAbsoluteFilenames: boolean, preserveDirectoryStructure: boolean): boolean;
  delete(): void;
  ptr: number;
};