// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdProjectExposerHelper {
  static exposeProjectEvents(project: gdProject, worker: gdArbitraryEventsWorker): void;
  delete(): void;
  ptr: number;
};