// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdProjectScopedContainers {
  static makeNewProjectScopedContainersForProjectAndLayout(project: gdProject, layout: gdLayout): gdProjectScopedContainers;
  static makeNewProjectScopedContainersForProject(project: gdProject): gdProjectScopedContainers;
  static makeNewProjectScopedContainersForEventsFunctionsExtension(project: gdProject, eventsFunctionsExtension: gdEventsFunctionsExtension): gdProjectScopedContainers;
  static makeNewProjectScopedContainersForFreeEventsFunction(project: gdProject, eventsFunctionsExtension: gdEventsFunctionsExtension, eventsFunction: gdEventsFunction, parameterObjectsContainer: gdObjectsContainer, parameterVariablesContainer: gdVariablesContainer): gdProjectScopedContainers;
  static makeNewProjectScopedContainersForBehaviorEventsFunction(project: gdProject, eventsFunctionsExtension: gdEventsFunctionsExtension, eventsBasedBehavior: gdEventsBasedBehavior, eventsFunction: gdEventsFunction, parameterObjectsContainer: gdObjectsContainer, parameterVariablesContainer: gdVariablesContainer, propertyVariablesContainer: gdVariablesContainer): gdProjectScopedContainers;
  static makeNewProjectScopedContainersForObjectEventsFunction(project: gdProject, eventsFunctionsExtension: gdEventsFunctionsExtension, eventsBasedObject: gdEventsBasedObject, eventsFunction: gdEventsFunction, parameterObjectsContainer: gdObjectsContainer, parameterVariablesContainer: gdVariablesContainer, propertyVariablesContainer: gdVariablesContainer): gdProjectScopedContainers;
  static makeNewProjectScopedContainersForEventsBasedObject(project: gdProject, eventsFunctionsExtension: gdEventsFunctionsExtension, eventsBasedObject: gdEventsBasedObject, outputObjectsContainer: gdObjectsContainer): gdProjectScopedContainers;
  static makeNewProjectScopedContainersWithLocalVariables(projectScopedContainers: gdProjectScopedContainers, event: gdBaseEvent): gdProjectScopedContainers;
  addPropertiesContainer(propertiesContainer: gdPropertiesContainer): gdProjectScopedContainers;
  addParameters(parameters: gdParameterMetadataContainer): gdProjectScopedContainers;
  getObjectsContainersList(): gdObjectsContainersList;
  getVariablesContainersList(): gdVariablesContainersList;
  delete(): void;
  ptr: number;
};