// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdResourcesInUseHelper extends gdArbitraryResourceWorker {
  constructor(resourcesManager: gdResourcesManager): void;
  getAllResources(): gdVectorString;
  getAllImages(): gdSetString;
  getAllAudios(): gdSetString;
  getAllFonts(): gdSetString;
  getAllBitmapFonts(): gdSetString;
  getAll(resourceType: string): gdSetString;
  delete(): void;
  ptr: number;
};