// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdReadOnlyArbitraryEventsWorkerWithContextJS extends gdReadOnlyArbitraryEventsWorkerWithContext {
  constructor(): void;
  doOnLaunch(events: gdEventsList): void;
  doVisitEvent(event: gdBaseEvent): void;
  doVisitInstruction(instruction: gdInstruction, isCondition: boolean, projectScopedContainers: gdProjectScopedContainers): void;
  delete(): void;
  ptr: number;
};