// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdRepeatEvent extends gdBaseEvent {
  constructor(): void;
  getConditions(): gdInstructionsList;
  getActions(): gdInstructionsList;
  setRepeatExpressionPlainString(expr: string): void;
  getRepeatExpression(): gdExpression;
  getLoopIndexVariableName(): string;
  setLoopIndexVariableName(name: string): void;
  delete(): void;
  ptr: number;
};