// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdResource {
  constructor(): void;
  clone(): gdResource;
  setName(name: string): void;
  getName(): string;
  setKind(kind: string): void;
  getKind(): string;
  isUserAdded(): boolean;
  setUserAdded(yes: boolean): void;
  useFile(): boolean;
  setFile(file: string): void;
  getFile(): string;
  setMetadata(metadata: string): void;
  getMetadata(): string;
  getProperties(project: gdProject): gdMapStringPropertyDescriptor;
  updateProperty(name: string, value: string, project: gdProject): boolean;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(element: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};