// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdRepeatEvent extends gdBaseEvent {
  constructor(): void;
  getConditions(): gdInstructionsList;
  getActions(): gdInstructionsList;
  setRepeatExpression(expr: string): void;
  getRepeatExpression(): string;
  delete(): void;
  ptr: number;
};