// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdScreenshot {
  getTiming(): number;
  setTiming(timing: number): void;
  getSignedUrl(): string;
  setSignedUrl(signedUrl: string): void;
  getPublicUrl(): string;
  setPublicUrl(publicUrl: string): void;
  delete(): void;
  ptr: number;
};