// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdShapePainterObject extends gdObjectConfiguration {
  constructor(): void;
  setCoordinatesAbsolute(): void;
  setCoordinatesRelative(): void;
  areCoordinatesAbsolute(): boolean;
  setClearBetweenFrames(value: boolean): void;
  isClearedBetweenFrames(): boolean;
  setOutlineSize(size: number): void;
  getOutlineSize(): number;
  setOutlineColor(color: string): void;
  getOutlineColor(): string;
  setOutlineOpacity(val: number): void;
  getOutlineOpacity(): number;
  setFillColor(color: string): void;
  getFillColor(): string;
  setFillOpacity(val: number): void;
  getFillOpacity(): number;
  getAntialiasing(): string;
  setAntialiasing(value: string): void;
  delete(): void;
  ptr: number;
};