// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdShapePainterObject extends gdObject {
  constructor(name: string): void;
  setCoordinatesAbsolute(): void;
  setCoordinatesRelative(): void;
  areCoordinatesAbsolute(): boolean;
  setOutlineSize(size: number): void;
  getOutlineSize(): number;
  setOutlineOpacity(val: number): void;
  getOutlineOpacity(): number;
  setOutlineColor(r: number, g: number, b: number): void;
  getOutlineColorR(): number;
  getOutlineColorG(): number;
  getOutlineColorB(): number;
  setFillOpacity(val: number): void;
  getFillOpacity(): number;
  setFillColor(r: number, g: number, b: number): void;
  getFillColorR(): number;
  getFillColorG(): number;
  getFillColorB(): number;
  delete(): void;
  ptr: number;
};