// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdUnfilledRequiredBehaviorPropertyProblem {
  getSourceProject(): gdProject;
  getSourceObject(): gdObject;
  getSourceBehaviorContent(): gdBehavior;
  getSourcePropertyName(): string;
  getExpectedBehaviorTypeName(): string;
  delete(): void;
  ptr: number;
};