// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVariable {
  constructor(): void;
  getType(): Variable_TYPES;
  setString(str: string): void;
  getString(): string;
  setValue(val: number): void;
  getValue(): number;
  setBool(val: boolean): void;
  getBool(): boolean;
  hasChild(str: string): boolean;
  getChild(str: string): gdVariable;
  removeChild(name: string): void;
  renameChild(oldName: string, newName: string): boolean;
  getAllChildrenNames(): gdVectorString;
  getChildrenCount(): number;
  contains(variableToSearch: gdVariable, recursive: boolean): boolean;
  removeRecursively(variableToRemove: gdVariable): void;
  hasIndex(index: number): boolean;
  getIndex(index: number): gdVariable;
  removeIndex(index: number): void;
  getAllChildrenList(): gdVectorVariable;
  serializeTo(element: gdSerializerElement): void;
  unserializeFrom(element: gdSerializerElement): void;
  delete(): void;
  ptr: number;
};