// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVectorPropertyFolderOrProperty {
  size(): number;
  at(index: number): gdPropertyFolderOrProperty;
  delete(): void;
  ptr: number;
};