// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVectorPlatformExtension {
  size(): number;
  at(index: number): gdPlatformExtension;
  delete(): void;
  ptr: number;
};