// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVectorUnfilledRequiredBehaviorPropertyProblem {
  size(): number;
  at(index: number): gdUnfilledRequiredBehaviorPropertyProblem;
  delete(): void;
  ptr: number;
};