// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVectorExpressionParserError {
  size(): number;
  at(index: number): gdExpressionParserError;
  delete(): void;
  ptr: number;
};