// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVectorExpressionColorationDescription {
  size(): number;
  at(index: number): gdExpressionColorationDescription;
  delete(): void;
  ptr: number;
};