// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVectorPoint {
  constructor(): void;
  push_back(pt: gdPoint): void;
  size(): number;
  at(index: number): gdPoint;
  set(index: number, pt: gdPoint): void;
  clear(): void;
  delete(): void;
  ptr: number;
};