// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdVectorPairStringSharedPtrSerializerElement {
  size(): number;
  getString(id: number): string;
  getSharedPtrSerializerElement(id: number): gdSharedPtrSerializerElement;
  delete(): void;
  ptr: number;
};