// Automatically generated by GDevelop.js/scripts/generate-types.js
declare class gdWholeProjectDiagnosticReport {
  get(index: number): gdDiagnosticReport;
  count(): number;
  delete(): void;
  ptr: number;
};