#ifndef TILEMAPDIALOGSIDS_H
#define TILEMAPDIALOGSIDS_H

enum 
{
    CHANGE_MAP_SIZE_TOOL_ID = 		1001,
    CONFIGURE_TILESET_TOOL_ID = 	1002,
    EDIT_TILE_TOOL_ID = 			1003,
    HIDE_UPPER_LAYERS_TOOL_ID = 	1004,
    ID_MAINPANEL = 					1005,
    ID_TILESETPANEL = 				1006,
    ADD_POINT_TOOL_ID = 			1101,
    COLLIDABLE_TOOL_ID = 			1102,
    EDIT_POINT_TOOL_ID = 			1103,
    REMOVE_POINT_TOOL_ID =			1104,
    RESET_MASK_TOOL_ID = 			1105,
};

#endif