// @flow
import * as React from 'react';
import TestRenderer from 'react-test-renderer';
import {
  getAiRequest,
  getAiRequestStatuses,
  fetchAiSettings,
  getAiRequests,
  type AiRequest,
  type AiRequestUserMessage,
} from '../Utils/GDevelopServices/Generation';
import { type AuthenticatedUser } from '../Profile/AuthenticatedUserContext';
import AuthenticatedUserContext, {
  initialAuthenticatedUser,
} from '../Profile/AuthenticatedUserContext';
import {
  AiRequestContext,
  AiRequestProvider,
  mergeIncrementalAiRequest,
  useAiRequestHistory,
  type AiRequestContextState,
} from './AiRequestContext';
import { act } from 'react-dom/test-utils';

jest.mock('../Utils/GDevelopServices/Generation');

const mockFn = (fn: any): JestMockFn<any, any> => fn;

const POLLING_INTERVAL_IN_MS = 1400;
// After an idle tick the adaptive polling interval backs off ×1.5 (see
// useAdaptivePollingInterval), so later ticks fire after a longer delay.
const POLLING_INTERVAL_AFTER_BACKOFF_IN_MS = Math.round(
  POLLING_INTERVAL_IN_MS * 1.5
); // 2100
const POLLING_INTERVAL_AFTER_2X_BACKOFF_IN_MS = Math.round(
  POLLING_INTERVAL_AFTER_BACKOFF_IN_MS * 1.5
); // 3150

const makeAiRequest = (
  id: string,
  status: 'working' | 'ready' | 'error' | 'suspended',
  parentAiRequestId?: string | null
): AiRequest => ({
  id,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  userId: 'user-1',
  status,
  error: null,
  output: [],
  parentAiRequestId: parentAiRequestId || null,
});

const makeAuthenticatedUser = (): AuthenticatedUser => ({
  ...initialAuthenticatedUser,
  authenticated: true,
  profile: {
    id: 'user-1',
    email: 'fake@example.com',
    username: 'fake-user',
    isEmailAutogenerated: false,
    description: '',
    getGameStatsEmail: false,
    getNewsletterEmail: false,
    isCreator: false,
    isPlayer: false,
    appLanguage: 'en',
    donateLink: null,
    discordUsername: null,
    communityLinks: {},
    createdAt: 0,
    updatedAt: 0,
  },
  loginState: 'done',
  getAuthorizationHeader: () => Promise.resolve('fake-auth-header'),
});

const ContextCapture = ({
  contextRef,
}: {|
  contextRef: { current: AiRequestContextState | null },
|}) => {
  const context = React.useContext(AiRequestContext);
  contextRef.current = context;
  return null;
};

const flushPromises = async () => {
  // Allow chained promises inside the polling tick to resolve.
  // The tick performs several `await`s sequentially, so we flush a few times.
  for (let i = 0; i < 10; i++) {
    // eslint-disable-next-line no-await-in-loop
    await Promise.resolve();
  }
};

const renderProvider = () => {
  const contextRef: { current: AiRequestContextState | null } = {
    current: null,
  };
  const authenticatedUser = makeAuthenticatedUser();
  let renderer;
  act(() => {
    renderer = TestRenderer.create(
      <AuthenticatedUserContext.Provider value={authenticatedUser}>
        <AiRequestProvider>
          <ContextCapture contextRef={contextRef} />
        </AiRequestProvider>
      </AuthenticatedUserContext.Provider>
    );
  });
  return { contextRef, renderer };
};

describe('AiRequestProvider sub-agent polling', () => {
  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequests).mockReset();
    mockFn(getAiRequests).mockResolvedValue({
      aiRequests: [],
      nextPageUri: null,
    });
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  // Covers bug 2 fix: once the sub-agent is in a non-`working` state, the
  // (batched) status-only polling that returns the same status must NOT trigger
  // additional full fetches. Previously the code compared the status against the
  // hardcoded `'working'` and full-fetched on every tick afterward.
  it('does not spam full fetches while a sub-agent stays in `ready` state', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    const subAgentReady = makeAiRequest('sub-1', 'ready');
    mockFn(getAiRequest).mockResolvedValue(subAgentReady);
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'sub-1', status: 'ready', userId: 'user-1' },
    ]);

    // Seed the sub-agent in the storage and mark it as active so the polling
    // loop picks it up.
    await act(async () => {
      // $FlowFixMe[incompatible-use] - contextRef.current is set above.
      contextRef.current.aiRequestStorage.updateAiRequest(
        'sub-1',
        () => subAgentReady
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    // First tick: shouldDoFullFetch is true (lastFullFetch starts at 0).
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(0);

    // Subsequent ticks within the full-fetch window do a (batched) status-only
    // fetch only. Because the status matches the cached status, no additional
    // full fetch should happen. The interval backs off after each idle tick, so
    // advance by the backed-off amount to fire each tick (still within the 7s
    // window: 1400 + 2100 + 3150 = 6650ms).
    for (const intervalMs of [
      POLLING_INTERVAL_AFTER_BACKOFF_IN_MS,
      POLLING_INTERVAL_AFTER_2X_BACKOFF_IN_MS,
    ]) {
      // eslint-disable-next-line no-await-in-loop
      await act(async () => {
        jest.advanceTimersByTime(intervalMs);
        await flushPromises();
      });
    }

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(2);
    // Critical assertion: still only the initial full fetch — the bug
    // would have caused one full fetch per tick after the sub-agent
    // reached `ready`.
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
  });

  // Covers bug 2 fix from the opposite angle: a real status change *must*
  // still trigger an immediate full fetch.
  it('triggers a full fetch immediately when the batched status fetch reports a status change', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    const subAgentWorking = makeAiRequest('sub-1', 'working');
    const subAgentReady = makeAiRequest('sub-1', 'ready');

    // Cached status starts as 'working'.
    mockFn(getAiRequest).mockResolvedValue(subAgentWorking);

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'sub-1',
        () => subAgentWorking
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    // First tick consumes the initial full fetch.
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);

    // Now backend switches the sub-agent to `ready`. The batched status fetch
    // reports the new status, so the polling loop should immediately do another
    // full fetch even though the full-fetch window has not elapsed.
    mockFn(getAiRequest).mockResolvedValue(subAgentReady);
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'sub-1', status: 'ready', userId: 'user-1' },
    ]);

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(1);
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(2);
  });

  // The selected parent and all its active sub-agents are status-polled in a
  // single batched request per tick.
  it('batches the parent and all sub-agents into a single status request', async () => {
    const { contextRef } = renderProvider();
    const context = contextRef.current;
    if (!context) throw new Error('Context not captured');

    mockFn(getAiRequest).mockImplementation((_, { aiRequestId }) =>
      Promise.resolve(makeAiRequest(aiRequestId, 'working'))
    );

    await act(async () => {
      context.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-1', () =>
        makeAiRequest('sub-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-2', () =>
        makeAiRequest('sub-2', 'working')
      );
      context.setSelectedAiRequestId('parent-1');
      context.activateSubAgent('sub-1', 'parent-1', 'call-1');
      context.activateSubAgent('sub-2', 'parent-1', 'call-2');
    });

    // First tick: everyone is due for a full fetch.
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });

    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'parent-1', status: 'working', userId: 'user-1' },
      { id: 'sub-1', status: 'working', userId: 'user-1' },
      { id: 'sub-2', status: 'working', userId: 'user-1' },
    ]);

    // Second tick: everyone is status-only → one batched request for all ids.
    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(1);
    expect(
      mockFn(getAiRequestStatuses).mock.calls[0][1].aiRequestIds.sort()
    ).toEqual(['parent-1', 'sub-1', 'sub-2']);
  });

  // When the batched response reports a single change, only that entity is
  // full-fetched; the unchanged ones are not.
  it('only full-fetches the entity whose status changed', async () => {
    const { contextRef } = renderProvider();
    const context = contextRef.current;
    if (!context) throw new Error('Context not captured');

    mockFn(getAiRequest).mockImplementation((_, { aiRequestId }) =>
      Promise.resolve(makeAiRequest(aiRequestId, 'working'))
    );

    await act(async () => {
      context.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-1', () =>
        makeAiRequest('sub-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-2', () =>
        makeAiRequest('sub-2', 'working')
      );
      context.setSelectedAiRequestId('parent-1');
      context.activateSubAgent('sub-1', 'parent-1', 'call-1');
      context.activateSubAgent('sub-2', 'parent-1', 'call-2');
    });

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(3);

    // Only sub-1 changes; parent and sub-2 stay working.
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'parent-1', status: 'working', userId: 'user-1' },
      { id: 'sub-1', status: 'ready', userId: 'user-1' },
      { id: 'sub-2', status: 'working', userId: 'user-1' },
    ]);

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    expect(mockFn(getAiRequestStatuses)).toHaveBeenCalledTimes(1);
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(4);
    expect(mockFn(getAiRequest).mock.calls[3][1].aiRequestId).toBe('sub-1');
  });

  // An id missing from the batched response (not found / not yet visible) must
  // be left as-is, without crashing or triggering a full fetch.
  it('leaves an entity untouched when it is missing from the batched response', async () => {
    const { contextRef } = renderProvider();
    const context = contextRef.current;
    if (!context) throw new Error('Context not captured');

    mockFn(getAiRequest).mockImplementation((_, { aiRequestId }) =>
      Promise.resolve(makeAiRequest(aiRequestId, 'working'))
    );

    await act(async () => {
      context.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'working')
      );
      context.aiRequestStorage.updateAiRequest('sub-1', () =>
        makeAiRequest('sub-1', 'working')
      );
      context.setSelectedAiRequestId('parent-1');
      context.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_IN_MS);
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(2);

    // sub-1 is omitted from the response.
    mockFn(getAiRequestStatuses).mockResolvedValue([
      { id: 'parent-1', status: 'working', userId: 'user-1' },
    ]);

    await act(async () => {
      jest.advanceTimersByTime(POLLING_INTERVAL_AFTER_BACKOFF_IN_MS);
      await flushPromises();
    });

    const updated = contextRef.current;
    if (!updated) throw new Error('Context not captured');
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(2);
    expect(Object.keys(updated.activeSubAgents)).toEqual(['sub-1']);
  });
});

describe('AiRequestProvider sub-agent cleanup on navigation', () => {
  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(getAiRequestStatuses).mockReset();
    mockFn(getAiRequestStatuses).mockResolvedValue([]);
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequests).mockReset();
    mockFn(getAiRequests).mockResolvedValue({
      aiRequests: [],
      nextPageUri: null,
    });
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  // Covers bug 3 fix: when the user switches away from a parent AI request,
  // its sub-agents must be removed from the active map so they stop polling.
  // Previously the cleanup only ran when the parent transitioned to
  // `suspended`, leaving sub-agents to poll forever after a navigation.
  it('removes sub-agents of the previously selected request when selection changes', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-2', () =>
        makeAiRequest('parent-2', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
    });

    // $FlowFixMe[incompatible-use]
    expect(Object.keys(contextRef.current.activeSubAgents)).toEqual(['sub-1']);

    // Switching to another parent must trigger the cleanup effect of the
    // previous selection and drop its sub-agent.
    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-2');
    });

    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.activeSubAgents).toEqual({});
  });

  // Same fix: navigating away from a parent (no selection at all) must also
  // drop its sub-agents.
  it('removes sub-agents when the selected request is cleared', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-a', 'parent-1', 'call-a');
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-b', 'parent-1', 'call-b');
    });

    // $FlowFixMe[incompatible-use]
    expect(Object.keys(contextRef.current.activeSubAgents).sort()).toEqual([
      'sub-a',
      'sub-b',
    ]);

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId(null);
    });

    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.activeSubAgents).toEqual({});
  });

  // Sub-agents whose parent is *not* the previously selected request must
  // not be affected when the selection changes — guards against an overzealous
  // cleanup that would also drop them.
  it('only removes sub-agents whose parent matches the previously selected request', async () => {
    const { contextRef } = renderProvider();
    if (!contextRef.current) throw new Error('Context not captured');

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest('parent-1', () =>
        makeAiRequest('parent-1', 'ready')
      );
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId('parent-1');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-1', 'parent-1', 'call-1');
      // A sub-agent that belongs to a different parent (e.g. one not
      // currently displayed) - the cleanup must leave it alone.
      // $FlowFixMe[incompatible-use]
      contextRef.current.activateSubAgent('sub-2', 'parent-other', 'call-2');
    });

    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.setSelectedAiRequestId(null);
    });

    // $FlowFixMe[incompatible-use]
    expect(Object.keys(contextRef.current.activeSubAgents)).toEqual(['sub-2']);
  });
});

describe('mergeIncrementalAiRequest', () => {
  const message = (messageId: string) => ({
    messageId,
    type: 'message',
    status: 'completed',
    role: 'user',
    content: [{ type: 'user_request', status: 'completed', text: messageId }],
  });
  const requestWithOutput = (output: Array<any>): AiRequest => ({
    ...makeAiRequest('req-1', 'working'),
    output,
  });

  it('returns the fetched request as-is when there is no outputFromMessageId', () => {
    const fetched = requestWithOutput([message('a'), message('b')]);
    expect(
      mergeIncrementalAiRequest(
        requestWithOutput([message('a')]),
        fetched,
        undefined
      )
    ).toBe(fetched);
  });

  it('splices the incremental slice onto the cached output', () => {
    const previous = requestWithOutput([message('a'), message('b')]);
    // The backend re-sends the tail ('b') plus the new message ('c').
    const fetched = requestWithOutput([message('b'), message('c')]);
    const merged = mergeIncrementalAiRequest(previous, fetched, 'b');
    const mergedOutput = merged.output || [];
    const fetchedOutput = fetched.output || [];

    expect(mergedOutput.map(m => m.messageId)).toEqual(['a', 'b', 'c']);
    // The tail is taken from the fetched response (so in-place updates like
    // suggestions are picked up), not from the cache.
    expect(mergedOutput[1]).toBe(fetchedOutput[0]);
  });

  it('returns the fetched request as-is when it is a full output, not a slice', () => {
    const previous = requestWithOutput([message('a'), message('b')]);
    const fetched = requestWithOutput([
      message('a'),
      message('b'),
      message('c'),
    ]);
    expect(mergeIncrementalAiRequest(previous, fetched, 'b')).toBe(fetched);
  });
});

describe('useAiRequestHistory', () => {
  const userMessage = (text: string): AiRequestUserMessage => ({
    type: 'message',
    status: 'completed',
    role: 'user',
    content: [{ type: 'user_request', status: 'completed', text }],
  });

  const requestWithUserMessages = (
    id: string,
    updatedAt: string,
    texts: Array<string>,
    parentAiRequestId?: string | null
  ): AiRequest => ({
    ...makeAiRequest(id, 'ready', parentAiRequestId),
    updatedAt,
    output: texts.map(userMessage),
  });

  const renderHistoryHook = (aiRequests: { [string]: AiRequest }) => {
    const hookResultRef: { current: any } = { current: null };
    const HookCapture = () => {
      hookResultRef.current = useAiRequestHistory(({ aiRequests }: any));
      return null;
    };
    act(() => {
      TestRenderer.create(<HookCapture />);
    });
    return hookResultRef;
  };

  const navigateUp = (hookResultRef: { current: any }) => {
    let latestText = '';
    act(() => {
      hookResultRef.current.handleNavigateHistory({
        direction: 'up',
        currentText: '',
        onChangeText: text => {
          latestText = text;
        },
      });
    });
    return latestText;
  };

  it('browses only messages sent by the user, skipping sub-agent requests', () => {
    const hookResultRef = renderHistoryHook({
      'orchestrator-1': requestWithUserMessages(
        'orchestrator-1',
        '2024-01-01T00:00:00.000Z',
        ['Make a platformer game']
      ),
      // A sub-agent request: its "user" messages come from the orchestrator.
      'sub-agent-1': requestWithUserMessages(
        'sub-agent-1',
        '2024-01-01T00:01:00.000Z',
        ['Create the player object with animations'],
        'orchestrator-1'
      ),
      'chat-1': requestWithUserMessages('chat-1', '2024-01-01T00:02:00.000Z', [
        'Add coins to collect',
      ]),
    });

    expect(navigateUp(hookResultRef)).toBe('Add coins to collect');
    expect(navigateUp(hookResultRef)).toBe('Make a platformer game');
    // No more history: the sub-agent request message must not appear.
    expect(navigateUp(hookResultRef)).toBe('');
  });
});
