// @flow
import * as React from 'react';
import TestRenderer from 'react-test-renderer';
import {
  getAiRequest,
  fetchAiSettings,
  getAiRequests,
  type AiRequest,
} from '../Utils/GDevelopServices/Generation';
import { type AuthenticatedUser } from '../Profile/AuthenticatedUserContext';
import AuthenticatedUserContext, {
  initialAuthenticatedUser,
} from '../Profile/AuthenticatedUserContext';
import {
  AiRequestContext,
  AiRequestProvider,
  type AiRequestContextState,
} from './AiRequestContext';
import { useLoadSubAgentRequests } from './UseLoadSubAgentRequests';
import { act } from 'react-dom/test-utils';

jest.mock('../Utils/GDevelopServices/Generation');

const mockFn = (fn: any): JestMockFn<any, any> => fn;

const makeAiRequest = (id: string, output: Array<any> = []): AiRequest => ({
  id,
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  userId: 'user-1',
  status: 'ready',
  error: null,
  output,
  parentAiRequestId: null,
});

const makeParentWithSubAgent = (
  parentId: string,
  subAgentAiRequestId: string,
  callId: string
): AiRequest =>
  makeAiRequest(parentId, [
    {
      type: 'message',
      status: 'completed',
      role: 'assistant',
      content: [
        {
          type: 'function_call',
          status: 'completed',
          call_id: callId,
          name: 'run_explorer_agent',
          arguments: '{}',
          subAgentAiRequestId,
        },
      ],
    },
  ]);

const makeAuthenticatedUser = (): AuthenticatedUser => ({
  ...initialAuthenticatedUser,
  authenticated: true,
  profile: {
    id: 'user-1',
    email: 'fake@example.com',
    username: 'fake-user',
    isEmailAutogenerated: false,
    description: '',
    getGameStatsEmail: false,
    getNewsletterEmail: false,
    isCreator: false,
    isPlayer: false,
    appLanguage: 'en',
    donateLink: null,
    discordUsername: null,
    communityLinks: {},
    createdAt: 0,
    updatedAt: 0,
  },
  loginState: 'done',
  getAuthorizationHeader: () => Promise.resolve('fake-auth-header'),
});

const ContextCapture = ({
  contextRef,
}: {|
  contextRef: { current: AiRequestContextState | null },
|}) => {
  const context = React.useContext(AiRequestContext);
  contextRef.current = context;
  return null;
};

const LoadSubAgentHarness = ({
  selectedAiRequest,
}: {|
  selectedAiRequest: ?AiRequest,
|}) => {
  useLoadSubAgentRequests({ selectedAiRequest });
  return null;
};

const flushPromises = async () => {
  // Give the chained `.then` of `refreshAiRequest(...).then(...)` and any
  // re-render triggered by `forceRetry` enough microtask turns to settle.
  for (let i = 0; i < 20; i++) {
    // eslint-disable-next-line no-await-in-loop
    await Promise.resolve();
  }
};

const renderHarness = (selectedAiRequest: ?AiRequest) => {
  const contextRef: { current: AiRequestContextState | null } = {
    current: null,
  };
  const authenticatedUser = makeAuthenticatedUser();
  let renderer;
  act(() => {
    renderer = TestRenderer.create(
      <AuthenticatedUserContext.Provider value={authenticatedUser}>
        <AiRequestProvider>
          <ContextCapture contextRef={contextRef} />
          <LoadSubAgentHarness selectedAiRequest={selectedAiRequest} />
        </AiRequestProvider>
      </AuthenticatedUserContext.Provider>
    );
  });
  return { contextRef, renderer };
};

describe('useLoadSubAgentRequests', () => {
  beforeEach(() => {
    jest.useFakeTimers();
    mockFn(getAiRequest).mockReset();
    mockFn(fetchAiSettings).mockReset();
    mockFn(fetchAiSettings).mockResolvedValue(null);
    mockFn(getAiRequests).mockReset();
    mockFn(getAiRequests).mockResolvedValue({
      aiRequests: [],
      nextPageUri: null,
    });
  });

  afterEach(() => {
    jest.useRealTimers();
  });

  // Sanity check: a single successful fetch loads the sub-agent and is not
  // retried.
  it('loads the sub-agent request once on success', async () => {
    const subAgent = makeAiRequest('sub-1');
    mockFn(getAiRequest).mockResolvedValue(subAgent);

    const parent = makeParentWithSubAgent('parent-1', 'sub-1', 'call-1');
    const { contextRef } = renderHarness(parent);

    await act(async () => {
      await flushPromises();
    });

    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(1);
    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.aiRequestStorage.aiRequests['sub-1']).toEqual(
      subAgent
    );
  });

  // Bug fix: a transient failure must not permanently blacklist the sub-agent.
  // Before the fix, `attemptedFetchRef` was set before `refreshAiRequest` was
  // awaited, so any failed fetch left the id in the blacklist forever.
  it('retries the fetch when it fails and eventually loads the sub-agent', async () => {
    const subAgent = makeAiRequest('sub-1');
    mockFn(getAiRequest)
      .mockRejectedValueOnce(new Error('Network error #1'))
      .mockRejectedValueOnce(new Error('Network error #2'))
      .mockResolvedValueOnce(subAgent);

    const parent = makeParentWithSubAgent('parent-1', 'sub-1', 'call-1');
    const { contextRef } = renderHarness(parent);

    await act(async () => {
      await flushPromises();
    });

    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(3);
    // $FlowFixMe[incompatible-use]
    expect(contextRef.current.aiRequestStorage.aiRequests['sub-1']).toEqual(
      subAgent
    );
  });

  // Bug fix: retries must be bounded — once `MAX_LOAD_SUB_AGENT_REQUEST_ATTEMPTS`
  // failures pile up, the hook must stop calling the backend even though the
  // sub-agent is still missing from the storage.
  it('gives up after a bounded number of failed attempts', async () => {
    mockFn(getAiRequest).mockRejectedValue(new Error('Network error'));

    const parent = makeParentWithSubAgent('parent-1', 'sub-1', 'call-1');
    const { contextRef } = renderHarness(parent);

    await act(async () => {
      await flushPromises();
    });

    // MAX_LOAD_SUB_AGENT_REQUEST_ATTEMPTS = 3 in the implementation.
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(3);
    // $FlowFixMe[incompatible-use]
    expect(
      contextRef.current.aiRequestStorage.aiRequests['sub-1']
    ).toBeUndefined();

    // No further re-renders/fetches even after additional ticks.
    await act(async () => {
      await flushPromises();
    });
    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(3);
  });

  // Sub-agents that are already loaded must not trigger any fetch.
  it('does not fetch sub-agents that are already in the storage', async () => {
    const subAgent = makeAiRequest('sub-1');
    mockFn(getAiRequest).mockResolvedValue(subAgent);

    const { contextRef } = renderHarness(null);

    // Pre-populate the storage with the sub-agent.
    await act(async () => {
      // $FlowFixMe[incompatible-use]
      contextRef.current.aiRequestStorage.updateAiRequest(
        'sub-1',
        () => subAgent
      );
    });

    expect(mockFn(getAiRequest)).toHaveBeenCalledTimes(0);
  });
});
