[versions]
toolchain = "21"
kotlinx-serialization-json = "1.7.3"
kotlinx-coroutines-core = "1.9.0"

[plugins]

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }

[bundles]